### ISSUE TITLE
Add contact information to career path

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#105]
Add contact name, phone, email to career paths. It can go on the left sidebar at the top so it remains consistent with events contact.

We need to be able to add a contact and reuse it many times. Often a contact will change (especially in nursing) and it should be easily changed in one place. There can be more than one contact for a career path.

- [ ] Title (Example: Dean of Nursing)
- [ ] Name
- [ ] Phone
- [ ] Email

https://phsc.edu/academics/degrees-and-programs/health-sciences/registered-nurse-rn

-----------
Per Bob Bade
-----------
When opening a program giving a staff contact name and number for the
students

**Comment by jeppy64** [comment]
@C13L0 
all set. completed!

time to complete: 2 hours

**Comment by C13L0** [comment]
This has been completed
