### ISSUE TITLE
Create moderation workflow for Clubs and Organizations

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#114]
@curtiskphsc 

https://student-life.phsc.edu/programs-and-services/clubs-and-organizations

There is not any moderation in place for Clubs and Organizations. I see this as an area that will be heavily edited due to the meeting dates. Do you want full moderation implemented or just a notification on publish?

Please re-assign to me after your reply.

**Comment by jeppy64** [comment]
@C13L0  @curtiskphsc 

Hi Guys,
Just need a little direction. Do we want to moderate the creation of a new organization or as mentioned with the meeting dates etc, do we want to moderate the organization schedules? Or both?

**Comment by C13L0** [comment]
@jeppy64  The organization node needs to be moderated, so that it's the same process as all other moderation (ie: events).

**Comment by jeppy64** [comment]
@C13L0 
completed and ready for review

time to complete: 30 minutes

**Comment by C13L0** [comment]
@jeppy64 I've verified that the moderation process is working properly. Please close once invoiced.

**Comment by jeppy64** [comment]
@C13L0 

closing as complete
