### ISSUE TITLE
Website list

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#156]
From: Brian Horn
Sent: Thursday, April 19, 2018 06:56 PM
To: Webmaster; Michelle Swingle
Cc: Robert E Bade; Courtney Boettcher; Kevin Curtis; Melissa Harts; Lucy Miller; Stanley Giannet
Subject: Re: Website list
 
Michelle,

Please see Cielo's request below

Brian S. Horn

Vice President of Finance & Auxiliary Services

Pasco-Hernando State College

10230 West Ridge Road

New Port Richey, FL 34654

(727) 816-3458

From: Webmaster
Sent: Thursday, April 19, 2018 5:10 PM
To: Brian Horn
Cc: Robert E Bade; Courtney Boettcher; Kevin Curtis; Melissa Harts; Lucy Miller; Stanley Giannet
Subject: Re: Website list
 

Good afternoon Brian,

The information Lucy is requesting was a requirement for everyone who submitted an RFQ.  I would appreciate if you could provide all website migration RFQ's to Lucy for her review.

Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

From: Lucy Miller
Sent: Thursday, April 19, 2018 04:26 PM
To: Melissa Harts; Webmaster
Cc: Robert E Bade; Courtney Boettcher; Kevin Curtis
Subject: Website list
 
Good afternoon,

Please send along the list of websites created by Jay for colleges and universities.   We would appreciate the opportunity to get a better idea of the work he has produced for higher education institutions.

Thanks for your attention to this request. 

Lucy

Lucy Miller
Executive Director,
Marketing & Communications
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3448
FAX: 727-816-3723
millerl@phsc.edu

**Comment by curtiskphsc** [comment]
@C13L0 Lucy states that she did in fact receive the RFQ's as requested.
