### ISSUE TITLE
2018 Legislative Session Summary

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#158]
From: Michele Fay
Sent: Friday, April 20, 2018 08:57 AM
To: Webmaster
Cc: Rhonda Dodge
Subject: 2018 Legislative Session Summary
 
Dr. Beard would like the attached PDF posted on the College intranet as soon as possible.

Thank you,

Mickey

Michele Fay

Executive Administrative Assistant to the

    Vice President of Student Affairs & Enrollment Management

PHSC

10230 Ridge Road

New Port Richey, FL  34654

727-816-3454

[2018 Legislative Session Highlights.pdf](https://github.com/phsc-edu/2018/files/1932805/2018.Legislative.Session.Highlights.pdf)

**Comment by C13L0** [comment]
@curtiskphsc Please make sure to re-assign the ticket to me so I am notified

**Comment by C13L0** [comment]
From: Webmaster
Sent: Monday, April 23, 2018 08:40 PM
To: Lucy Miller; Michele Fay
Cc: Rhonda Dodge; Stanley Giannet
Subject: Re: 2018 Legislative Session Summary | 158 | Open
 
Good afternoon,



You can now follow your ticket live at https://github.com/phsc-edu/2018/issues/158

As per Marketings comment below...


Are you requesting an intranet announcement or for the document to be added to the intranet?


curtiskphsc commented 7 hours ago
This is not an announcement request that I can see. It looks like a link needs to be posted on this page http://internal.phsc.edu/afc/legislation.php and it is typically requested by the legal department. I do not review or suggest edits to legal department documents. I would recommend changing the copy on the page though as Steve Schroeder is no longer with PHSC. I would suggest some very basic copy such as "Follow these links for additional information about important legislation pertinent to community colleges and other education issues."









Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

**Comment by C13L0** [comment]
@curtiskphsc 
Dr. Beard has requested for an intranet message.

From: Rhonda Dodge
Sent: Tuesday, April 24, 2018 01:38 PM
To: Webmaster; Lucy Miller; Michele Fay
Cc: Stanley Giannet
Subject: Re: 2018 Legislative Session Summary | 158 | Open
 
Hello, Cielo -


Dr. Beard would like the document added to the announcement page of the Intranet.  Thank you!   👍

**Comment by curtiskphsc** [comment]
@C13L0 I have pulled some copy for this announcement directly from the report. I still think it should be posted on the intranet here http://internal.phsc.edu/afc/legislation.php with all the other Legislative Updates as referenced above, and the copy on that page ought to be massaged to eliminate the mention of Steve Schroeder as suggested. A link to that page could be used or you can link to the PDF directly using the last sentence. I will defer to Rhonda for a final decision on whether or not to add it to the page and the suggested edits to the page. Please have the copy reviewed before posting.
**2018 Legislative Update**
The 2018 Florida Legislature adjourned sine die on Sunday evening, March 11, 2018
following a querulous budget process that resulted in the extension of the legislative
session by 2 days and the requisite 72-hour ”cooling-off” period. In the end, the
Legislature approved the General Appropriations Act (GAA), Ch. 2018-119, L.O.F.,
(HB 5001), appropriating an overall budget of $88.7 billion which takes effect July 1,
2018. The Governor vetoed 88 items totaling $64 million. A total of 3,250 bills were
filed this session, with only 196 passing both Chambers, resulting in one of the
lowest number of bills passed in nearly two decades and 49 less than during the
2017 session.
For complete details, view the entire 2018 Legislative Summary Report

**Comment by curtiskphsc** [comment]
@C13L0 Placing it on that page would be in addition to posting it as an announcement of course.

**Comment by C13L0** [comment]
Completed
