### ISSUE TITLE
Giannet Ticket Submission - 2

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#159]
From: Melissa Harts
Sent: Friday, April 20, 2018 12:57 PM
To: Lucy Miller; Stanley Giannet
Cc: Webmaster; Kevin Curtis; Sonia Thorn; Robert E Bade
Subject: Re: Giannet Ticket Submission - 2
 
Good afternoon,

Lucy, you were misinformed about having to put Giving on the top of the website as it was part of your staff's original design based on the Foundation's request. Your content manager has always managed Smart Catalogue from before I was hired almost five years ago when it was then Acalog. 

Simply... can we just post Dr. Giannet's links where he wants them? 

Melissa Harts, Ed.D

Vice President of Technology and Distance Education

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

(727) 816-3466

From: Lucy Miller
Sent: Friday, April 20, 2018 10:34 AM
To: Stanley Giannet
Cc: Melissa Harts; Webmaster; Kevin Curtis; Sonia Thorn; Robert E Bade
Subject: Fw: Giannet Ticket Submission - 2
 
Dr. Giannet,

As an fyi, the seven links allowable on the landing pages that Courtney mentions below are not to be confused with the three hyperlinks that are in the header of all website pages.  

Regarding the three hyperlinks that appear in the headers on the home page and all other website pages,  our marketing department understood that we were limited to three . . . thus the conversations about omitting "Giving" as one of the three.

We were recently told that more hyperlinks could be added to the headers, and are reviewing recommendations and options.  For instance, we will request that the webmaster add catalog to that space.  

Regarding the many broken links in the catalog, we were told that IT would be responsible for fixing the links.  However, the person in IT assigned to fix the links will need credentials to login to SmartCatalog to do so.  I'm assuming that Cielo will be assigned this task, but we will need confirmation from Dr. Harts.

Lucy

Lucy Miller
Executive Director,
Marketing & Communications
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3448
FAX: 727-816-3723
millerl@phsc.edu

From: Courtney Boettcher
Sent: Friday, April 20, 2018 9:54 AM
To: Lucy Miller
Cc: Kevin Curtis
Subject: Re: Giannet Ticket Submission - 2
 
Lucy,

I wanted to address Dr. Giannet's point #3. The decision to combine the Vision and Mission onto the Leadership page was a marketing decision. We made this decision given the parameter from the webmaster that we could only have 7 links on a landing page. Previously, the super menu had 28 links. We had to boil 28 down to 7. The marketing team researched how we could accomplish this while maintaining the integrity of the content -- we looked at what several of our sister institutions present on their sites as well as what universities present. 

If the web parameter limit of 7 links no longer applies and we are able to have more links on a landing page, then certainly we endorse adding a Vision and Mission link. If the link limit is still being enforced by the webmaster, then we can add the Mission and Vision information onto the About PHSC landing page. A confirmation from the webmaster will be needed so that we know which options are available in re-tooling this content.

kind regards,

Courtney Boettcher

Assistant Director, Marketing and Communications

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

boettcc@phsc.edu

727.816.3738

From: Lucy Miller
Sent: Friday, April 20, 2018 9:05 AM
To: Courtney Boettcher; Kevin Curtis
Subject: Fw: Giannet Ticket Submission - 2
 
FYI.

Lucy

Lucy Miller
Executive Director,
Marketing & Communications
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3448
FAX: 727-816-3723
millerl@phsc.edu

From: Stanley Giannet
Sent: Friday, April 20, 2018 8:47 AM
To: Webmaster
Cc: Melissa Harts; Robert E Bade; Lucy Miller; Timothy Beard
Subject: Giannet Ticket Submission - 2
 

Good morning, Webmaster.

I would appreciate your addressing the following website concerns as soon as possible:

1) Please fix the too many to mention broken links from the College Catalog / Student Handbook to the website.  Just a random click of links - especially links to Board rules - will yield to the standard  "Welcome to the new PHSC.edu."  Most notably -  include a separate page that houses all the Board rules and link them to the College Catalog sections accordingly.  This has to be fixed.  From an accreditation perspective, it is imperative based on the SACSCOC standard of Transparency and Institutional Representation  and the standard emphasizing Educational Policies, Procedures and Practices. We are responsible for publishing and disseminating academic policies that accurately represent our programs and services. Due to the absence or malfunction of this capability  (broken link), we are currently non-compliant since the website is the primary public information mechanism for the College.  Assessors will have no appetite for broken links of this magnitude.

2) The employee search-by-name feature is no longer available because the directory is separate from the website.  Please fix this so that when one searches an employee name on the site, it will navigate and provide the link to the employee directory information. 

3) Under the "About PHSC" include a link or include in the body of the narrative, the College's mission and vision statements.  Remove the vision and mission from the "Leadership" link and provide a separate and distinct link.

4) Please continue to address the items requested in the initial Giannet Ticket Submission - from the placement of the links to the removal of the language obviating our responsibility for the content.

Please do contact me via telephone if you have any questions about my request or require clarification. 

Thank you for your urgent attention to this ticket submission.

STANLEY M. GIANNET, PH.D.

Vice President of Academic Affairs & Faculty Development |

College Provost

**Comment by curtiskphsc** [comment]
@C13L0 I have no issue with creating a "Vision and Mission" page that would be included in the links on the About PHSC landing page. That said, the Leadership page will then have very little content. Could you please remind me where in the IA document the links referenced on the Leadership page are located? The one I am looking at does not include a link path past the About PHSC landing page.

**Comment by C13L0** [comment]
@curtiskphsc 

The Vision and Mission has been created at https://phsc.edu/about-phsc/vision-and-mission


> Could you please remind me where in the IA document the links referenced on the Leadership page are located? 

![about-phsc-leadership](https://user-images.githubusercontent.com/3138019/39487273-a63a332c-4d4c-11e8-973c-9564719bfced.png)

**Comment by curtiskphsc** [comment]
@C13L0 Thanks for providing this, however this is not the requested link path. This is only the path to the About PHSC landing page. I requested the IA document showing the link path for the Leadership page https://phsc.edu/about-phsc/leadership

**Comment by curtiskphsc** [comment]
@C13L0 I am requesting the IA document that shows which links were to be included in the left side bar on the Leadership page.

**Comment by C13L0** [comment]
@curtiskphsc The links on the left side bar are children menu items of the parent menu as displayed in the above screenshot. **About PHSC** is the parent menu item.

![39487273-a63a332c-4d4c-11e8-973c-9564719bfced png 1341x677 2018-05-04 09-01-27](https://user-images.githubusercontent.com/3138019/39629429-278436f6-4f7a-11e8-862e-09a45718ad02.png)

**Comment by curtiskphsc** [comment]
@C13L0 Got it. The landing page menu becomes the left side bar menu on those pages.
Added content to Vision Mission page, removed duplicate content from Leadership page.

**Comment by C13L0** [comment]
@curtiskphsc 

This is not ada compliant. Please do not use bold in place of headers and remove ALL CAPS

![not-ada-compliant](https://user-images.githubusercontent.com/3138019/39711576-18857a04-51ee-11e8-832a-9aeef9b2f916.png)

**Comment by C13L0** [comment]
As per Dr. Harts, the content must be removed until ada compliant

**Comment by curtiskphsc** [comment]
@C13L0 It was already on our website in that configuration created on 08/01/2017 - 13:58 by miaDmin
Initial revision. https://phsc.edu/node/37/revisions/37/view
I would suggest that the original content creator make the changes.

**Comment by curtiskphsc** [comment]
@C13L0 The issue was corrected Monday.

**Comment by curtiskphsc** [comment]
@C13L0 Also, I have agreed to assist Dean Thorn and her staff with reestablishing the links in the Catalog. That process has begun.

**Comment by C13L0** [comment]
**Status: Completed**
The employee search-by-name feature is no longer available because the directory is separate from the website. Please fix this so that when one searches an employee name on the site, it will navigate and provide the link to the employee directory information.

**Status: Completed**
Under the "About PHSC" include a link or include in the body of the narrative, the College's mission and vision statements. Remove the vision and mission from the "Leadership" link and provide a separate and distinct link.

**Comment by C13L0** [comment]
**Status: In progress**
> Please fix the too many to mention broken links from the College Catalog / Student Handbook to the website. Just a random click of links - especially links to Board rules - will yield to the standard "Welcome to the new PHSC.edu." Most notably - include a separate page that houses all the Board rules and link them to the College Catalog sections accordingly. This has to be fixed. From an accreditation perspective, it is imperative based on the SACSCOC standard of Transparency and Institutional Representation and the standard emphasizing Educational Policies, Procedures and Practices. We are responsible for publishing and disseminating academic policies that accurately represent our programs and services. Due to the absence or malfunction of this capability (broken link), we are currently non-compliant since the website is the primary public information mechanism for the College. Assessors will have no appetite for broken links of this magnitude.

**Comment by curtiskphsc** [comment]
@C13L0 You should check with Dean Thorn but as far as I know this is 100% regarding the 2018-19 Catalog. All links were updated a few weeks ago. The 2017-18 and 2015-16 Catalogs still need to be fixed though.

**Comment by C13L0** [comment]
Completed
