### ISSUE TITLE
Foundation Web

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#166]
From: Jessica Staller
Sent: Monday, April 23, 2018 09:43 AM
To: Webmaster
Subject: Foundation Web
 
Hi Cielo,

I have two questions. I'm trying to update the sponsors from the Fishing Tournament and it is not showing up on our events section: https://foundation.phsc.edu/department-information/events  It is not even showing up as a past event, so I'm not able to add a few last minute sponsors. Secondly, I added the information for the 2018 golf tournament to be posted on 3/27/18 but it is yet to be approved according to the moderation section. Is there anyway to get this expedited? Thank you! Jessica

**Comment by C13L0** [comment]
@curtiskphsc please look into this request

> Secondly, I added the information for the 2018 golf tournament to be posted on 3/27/18 but it is yet to be approved according to the moderation section. Is there anyway to get this expedited?

**Comment by C13L0** [comment]
> I'm trying to update the sponsors from the Fishing Tournament and it is not showing up on our events section: https://foundation.phsc.edu/department-information/events It is not even showing up as a past event, so I'm not able to add a few last minute sponsors. 

Choosing "Persistent Display" moves the event to Past Events

![edit event 12th annual catch release fishing tournament phsc foundation 2018-04-24 09-23-46](https://user-images.githubusercontent.com/3138019/39189895-6703cb9c-47a1-11e8-932d-40ff46925c01.png)

**Comment by C13L0** [comment]
@curtiskphsc Please re-assign to me when this has been completed

**Comment by curtiskphsc** [comment]
@C13L0 Three screen shots attached. First one shows my email inbox for the date specified (3/27/2018) I received no notification regarding the 2018 Golf Tournament and I do not move or delete emails. They live where they arrive. Second, clicking the supplied link (in this ticket) takes us to the events page where in the right side bar one can access past events that are listed by clicking on them. The Fishing Tournament is listed (at the bottom) and clicking the link takes one to the page where the edit function is available (screen shot 3). 
![foundation](https://user-images.githubusercontent.com/28155245/39207474-09505006-47ce-11e8-8602-bc98896165f9.JPG)
![foundation-events](https://user-images.githubusercontent.com/28155245/39207660-89075cd6-47ce-11e8-9deb-306e0fd7cfe7.JPG)
![foundation-fishing-event](https://user-images.githubusercontent.com/28155245/39207663-8f11e178-47ce-11e8-92ee-cbb4c81e0efa.JPG)
That said, on rollover the link changes color but I barely notice it, so I think we need to look at making those right side bar past event links more easily recognized as links. 
Also, I published the golf tournament event. FYI, the registration link used is https://6408.thankyou4caring.org/golf 
Can you confirm that the actual link used should be https://giving.phsc.edu/golf

**Comment by curtiskphsc** [comment]
@C13L0 I did not reassign this as it is technically not complete. Would you like me to reassign tickets even if they are not complete and the comments have questions?

**Comment by C13L0** [comment]
@curtiskphsc Yes, all tickets need to be assigned to someone and can be assigned to more than one person at a time. I usually filter by what is assigned to me.

**Comment by jeppy64** [comment]
Hey Guys,

There was no notification email sent due to the fact that these events have already been published through moderation.  As Cielo mentioned the newer function of Persistent Display makes them show on the right sidebar on other events. What this does is allow an event node to be used as upcoming and past. The idea was that once these events pass, they can go in and add images.

I think we are seeing a situation where there is too much moderation going on. In this example we'd need a new transition and approval for something that's already published, but the event date has passed and new child node content is being added. We should talk this through.

**Comment by curtiskphsc** [comment]
@jeppy64 @C13L0 The event in question, "9th Annual PHSC Golf tournament" (node/222) has an initial revision date of 3/27/18, so it was not an updated node. It was the first iteration of it, meaning it had not been published yet unless I am completely missing something? See screen shot attached.
![foundation-events-2](https://user-images.githubusercontent.com/28155245/39246544-e170f652-4864-11e8-9e64-7abba3398374.JPG)

**Comment by C13L0** [comment]
@curtiskphsc @jeppy64 

I believe this issue stems from the document double moderation #172 . The Golf Tournament event had a document still in draft, which prevented an email from going out. Emails are only sent on "needs review" and "publish". Once ticket #172 is completed, this issue should correct its self.

**Comment by C13L0** [comment]
@curtiskphsc You are correct, it was a new event =)

**Comment by C13L0** [comment]
@jeppy64 Please see my comments above. Closing this ticket as it will be addressed in #172

**Comment by C13L0** [comment]
From: Webmaster
Sent: Wednesday, April 25, 2018 02:11 PM
To: Jessica Staller
Subject: Re: Foundation Web | 166 | For review
 
Jessica,


Marketing published the Golf Tournament event. There was an issue with the automated outgoing email that we are addressing. Also, please make sure and fill out the revision comment so we know what was changed.


As far as the Fishing Tournament, please checkmark "Persistent display" on any event that you would like to show as a past event. When you want to remove an event, just uncheck persistent display.


You weren't able to see the fishing tournament as it is a past event. I will create a new management view of past events so you can easily find them. I've created a new ticket to address this problem which you can view here:

https://github.com/phsc-edu/2018/issues/177



Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372
