### ISSUE TITLE
(May) Document double moderation

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#172]
@jeppy64 

We have double moderation on documents on all sites which is causing issues. We corrected this issue on career study path but didn't make the change to just regular documents.

We do not need "scheduled documents" on any subdomains. 

- [ ] Remove moderation from document on event 
- [ ] Remove the ability to "Add new node" on document
- [ ] Add the ability to "Add existing node" on document

![edit career study path accounting technology pasco-hernando state college 2018-04-24 09-39-05](https://user-images.githubusercontent.com/3138019/39191059-0014dcd4-47a4-11e8-9208-9c0b8b29cca4.png)

**Comment by C13L0** [comment]
@jeppy64 Here is a screenshot showing document double moderation

![edit event 12th annual catch release fishing tournament phsc foundation 2018-04-24 09-18-30](https://user-images.githubusercontent.com/3138019/39191379-d54cf0f8-47a4-11e8-8df9-f0a138923ecd.png)

**Comment by jeppy64** [comment]
Yep, you hit it right on the head. Double moderation.

The event has its own and so does the document. I think we might want to talk about creating a new bundle called an Event Document. This will allow us to keep functionality on the Scheduled and Unscheduled documents which is crucial to the academics side.

**Comment by C13L0** [comment]
@jeppy64 

Please only work on **one** website and let me review it before making changes to all sites. The custom document moderation email configurations were overwritten when accessibility moderation was added.

**Comment by C13L0** [comment]
@jeppy64 moving this to May work order as we have six hours back!! Yay!!!

**Comment by jeppy64** [comment]
I never updated this. All sites completed.

Time: 1/2 hour

**Comment by jeppy64** [comment]
@C13L0 Completed

**Comment by C13L0** [comment]
@jeppy64 This look great!
