### ISSUE TITLE
Course schedule subject filter

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#174]
From: Artem Geyvandov
Sent: Tuesday, April 24, 2018 12:06 PM
To: Cielo Johnson
Subject: Re: Course schedule subject filter
 
I've checked the file.   it is OK.

I think somethink got out of sink on your end. Just like last time.

You cleared cash, all tables  and loaded all manually after that  .

From: Cielo Johnson
Sent: Tuesday, April 24, 2018 11:59 AM
To: Artem Geyvandov
Subject: Course schedule subject filter
 
Artem,

It looks like there is an issue with the file.
![import 20182 schedule pasco-hernando state college 2018-04-24 11-57-53](https://user-images.githubusercontent.com/3138019/39211670-5e0c0462-47da-11e8-8212-7726025c762f.png)

**Comment by C13L0** [comment]
2018-04-24 16:15:43 | 2018-04-24 16:15:25 | Imported in 18 seconds. | info
-- | -- | -- | --
2018-04-24 16:15:43 | 2018-04-24 16:15:25 | Failed importing 703 nodes. | error
2018-04-24 16:15:43 | 2018-04-24 16:15:25 | Field validation errors in item 'NCP0013':<div class="item-list"><ul><li class="first"><em class="placeholder">Day/Evening</em>: illegal value.</li> <li class="last"><em class="placeholder">Booklet</em>: illegal value.</li> </ul></div>Original itemarray(   'key' => '20183_0302_1',   'yrtr' => '20183',   's-sess' => '20183F',   'seats' => '25',   'seats avail' => '25',   'evn/day' => 'Evening',   'inst-m' => 'On Campus',   'camp' => 'West Campus',   'reqst' => '',   'sect' => '0302',   'course no.' => 'NCP0013',   'title1' => 'Divorce and Impact',   'title2' => 'Divorce and Its Impact on Children',   'crhr' => '',   'sess' => '',   'dates' => '07/18/2018-07/18/2018',   'meeting time' => ' 5:30P- 9:30',   'bldg/room' => 'S-316',   'lab fee' => '35.75',   'instructor' => 'Montgomery J',   'e-mail' => 'Montgoj@phsc.edu',   'division' => 'Non-credit',   'department' => 13695472,   'avail' => 'Open',   'inst-cd' => 'P',   'icstype' => '2003',   'booklet' => 'Y',   'location' => '3003',   'comments' => '',   'st.time-end.time' => '1730-2130',   'inst_id' => 13695260,   'newsec' => 'Y',   'clhr' => '4.00', )Entity(object) array(   'language' => 'und',   'type' => 'slot',   'changed' => 1524600925,   'created' => 1524600925,   'is_new' => TRUE,   'status' => 1,   'promote' => 0,   'sticky' => 0,   'uid' => '1',   'revision' => FALSE,   'log' => 'Created by FeedsNodeProcessor',   'title' => 'NCP0013', )

**Comment by C13L0** [comment]
From: Janice L Scott
Sent: Thursday, April 26, 2018 12:39 PM
To: Webmaster; Melissa Harts; Ingrid Purrenhage; Artem Geyvandov
Cc: Raymond Calvert
Subject: Re: No instructor names showing in schedule
 
Hi artem I was wondering if you could look into the reason that no instructors are showing up on the schedule on the web

Get Outlook for Android

From: Ingrid Purrenhage
Sent: Thursday, April 26, 2018 12:15:44 PM
To: Webmaster; Janice L Scott; Melissa Harts
Cc: Raymond Calvert
Subject: No instructor names showing in schedule
 
Greetings,


I am not sure to whom this question should be directed -- please let me know if I need to ask someone else.


We have noticed that instructor names are no longer showing in the Online Course Schedule (https://info.phsc.edu/?_ga=2.219290256.883995851.1524488012-1946494817.1499954207)


When will this be fixed? This is very important data that is used by students in selecting their courses and by others trying to help pinpoint an instructor name or when a course is meeting. Since we can no longer search by instructor's name (would like that feature back) at least we could scroll down through courses in a subject area to find the information we need.


Thanks for any insight into this,


Ingrid

Ingrid Purrenhage

Associate Director PHSC Porter Campus Library

2727 Mansfield Boulevard

Wesley Chapel, FL 33543

813-527-6690

**Comment by C13L0** [comment]
From: Webmaster
Sent: Thursday, April 26, 2018 03:55 PM
To: Janice L Scott; Melissa Harts; Ingrid Purrenhage; Artem Geyvandov
Cc: Raymond Calvert
Subject: Re: No instructor names showing in schedule
 
Good afternoon,


The course schedule is no longer able to import the following files which affects the subject and teacher filter.

Import 20182 Schedule | Spring 2018
Import 20183 Schedule | Summer 2018
Import 20191 Schedule | Fall 2018

On the development site, I re-imported each file manually in order and the course schedule now returns no results for anything (aka it's completely broken). I'm waiting to hear back from Artem concerning these files.

You can follow this ticket live at https://github.com/phsc-edu/2018/issues/174




Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

**Comment by C13L0** [comment]
@curtiskphsc Just an FYI, this has also affected the Admin Directory. Please don't make any corrections until this issue has been resolved.

**Comment by C13L0** [comment]
@jeppy64 Please make sure and add your hours to this ticket

**Comment by C13L0** [comment]
@jeppy64 Assigning to you to meet with Jan and Artem tomorrow via skype. Let's do whatever it takes to make it work. Hours have been approved by Dr. Harts.

**Comment by jeppy64** [comment]
Sounds good. I'll be on Skype at 9:00 am

**Comment by C13L0** [comment]
Course schedule is currently in maintenance mode. This affects the entire website including the directory

**Comment by C13L0** [comment]
@jeppy64 Thank you! It looks great

**Comment by C13L0** [comment]
@curtiskphsc Assigning to you for Admin directory.
https://info.phsc.edu/directory/administration

**Comment by C13L0** [comment]
@curtiskphsc 

Update on Administration directory:

**Administration checkmark**
Jan will be able to provide us with information which will auto populate the admin directory. 

**Administration work title**
Could you please provide a list of Administration that need their titles updated? Jan said she would work directly with HR to correct them, which will allow us to auto populate the titles again. 

**Administration portrait image**
We are discussing a way to auto show images but it will take a bit of work and I may need to get Jay involved.

This will take time to test and implement. In the meantime, please manually update the Administration Directory.

Thanks!

**Comment by curtiskphsc** [comment]
@C13L0 The admin directory has been rebuilt. Two hours and thirty eight minutes. I used a timer. About an hour was used to discuss the process going forward and determine the appropriate naming convention for the photo files, etc. The rest was re-inputting the info.

**Comment by C13L0** [comment]
completed
