### ISSUE TITLE
Website Question

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#176]
@jeppy64 Could you take a look at Jessica's request? 

- I think part of this issue can be corrected if we remove "Add new node" and only manage Sponsors through the management UI. 

- The only duplicate that I see, is where a sponsor was added twice but with a slight variation of their name. 

- Can you verify that each sponsor will show all events they have sponsored on the sponsor page? https://foundation.phsc.edu/about/sponsors

This is going to look really nice once we get it themed!

--------------

From: Jessica Staller
Sent: Wednesday, April 25, 2018 10:00 AM
To: Webmaster
Subject: Website Question
 
Hi Cielo,

I have a question. I'm updating the sponsors for the Fishing Tournament and several are repeats from other events. If I add them (you can see Unlimited Site Services), it adds another listing of the company which is not necessary. But when I go to our sponsor section (https://foundation.phsc.edu/about/sponsors) I'm not able to edit the sponsors or change them from one event to the next. Is there an easy solution for this? BTW...thank you for getting the fishing back on the site. I appreciate it!

From: Jessica Staller
Sent: Wednesday, April 25, 2018 10:00 AM
To: Webmaster
Subject: Website Question
 
Hi Cielo,

I have a question. I'm updating the sponsors for the Fishing Tournament and several are repeats from other events. If I add them (you can see Unlimited Site Services), it adds another listing of the company which is not necessary. But when I go to our sponsor section (https://foundation.phsc.edu/about/sponsors) I'm not able to edit the sponsors or change them from one event to the next. Is there an easy solution for this? BTW...thank you for getting the fishing back on the site. I appreciate it!

**Comment by C13L0** [comment]
Good afternoon Jessica,

It looks like there was a slight name variation for Unlimited Site Services and Unlimited Site Services, Inc which makes it show as two separate companies.

I think there are a few ways we can make managing vendors a bit easier manage so I've assigned your ticket to our vendor.


You can now follow your ticket live at https://github.com/phsc-edu/2018/issues/176

 
 

Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

**Comment by C13L0** [comment]
From: Jessica Staller
Sent: Wednesday, April 25, 2018 02:14 PM
To: Webmaster
Subject: Re: Foundation Web | 166 | For review
 
Thank you. I appreciate the help. I went on the site and changed Unlimited Site Services to Unlimited Site Services, Inc. and they are both identical now and both showing up. I appreciate any help/suggestions. Thank you again! Jessica

**Comment by C13L0** [comment]
@jeppy64 Please read Jessica's reply

**Comment by C13L0** [comment]
Moving to June due to funding

**Comment by C13L0** [comment]
@jeppy64 Moving this to May work order as we have six hours back!! Yay!!!

**Comment by jeppy64** [comment]
Completed

Time: 1/2 hour

**Comment by C13L0** [comment]
This has been completed. Closing as it is part of monthly contract.
