### ISSUE TITLE
9th Annual Faculty and Staff Summer Art Show

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#178]
From: Maria Rhew
Sent: Wednesday, April 25, 2018 02:29 PM
To: Webmaster
Subject: Re: 9th Annual Faculty and Staff Summer Art Show 
 
Thank you, Cielo! Here is the information for the intranet announcement:

1- Title:

Calling all creative types!

2- Message: 

The 9th Annual Faculty and Staff Summer Art Show will open May 23rd -- but not without your help! From whatever era in your life, in whatever medium or style -- 2D, 3D, digital, video, music, poetry, photography, woodwork, needlework (no tats, please) -- if you created it, please share it! Usual limit is 5 pieces per artist, but exceptions can be made. Please submit work to Maria Rhew at the West campus library, room J-139, by the end of Monday May 21st.

4- Additional:

For details call Maria at 3231 or email  rhewm@phsc.edu

Let me know if you think this is OK. If too long, I can pare it down some.

 ^_^

Maria

From: Webmaster
Sent: Wednesday, April 25, 2018 1:24:20 PM
To: Maria Rhew
Subject: Re: 9th Annual Faculty and Staff Summer Art Show 
 
Hi Maria,

No worries! I'm here when you have time to meet. There is not a form to request an intranet message. You can simply reply to this email with the following information:

Announcement title
Announcement message
Attach any associated file attachment(s) in .pdf format
Additional detailed instructions

Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

From: Maria Rhew
Sent: Wednesday, April 25, 2018 9:21:25 AM
To: Webmaster
Subject: 9th Annual Faculty and Staff Summer Art Show
 
Good morning, Cielo!

Three quick things:

I do apologize for being unable to meet with you about the website right away -- it's a super-busy time of year for me. Would love to do it a little later, though, if you still want to do that.

You're really busy too, but we need faculty and staff submissions for the summer art show, and just the posters may not be quite enough. Where is the form I need to fill in to ask you to post on the intranet? 

Speaking of intranet, I just found out that some staff just never go there anymore, because O365 seems to 'do it all'. This could be a problem, since we rely on the internal page for some important posts. Just passing this on to you, because it's news to me.

Thank you for everything you do for all of us 💮 it IS appreciated, and I wish you a really good day!!! 

 ^_^

Maria

Maria Rhew

Staff Assistant

West Campus Library  

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654  

727.816.3231

rhewm@phsc.edu

“The hardest journey is from the head to the heart.”

Jim Dumont, Ojibway-Anishinabe elder

**Comment by curtiskphsc** [comment]
@C13L0 This is good to go
**Calling All Creative Types!**
The 9th Annual Faculty and Staff Summer Art Show will open Wednesday, May 23 — but not without your help! From whatever era in your life, in whatever medium or style — 2D, 3D, digital, video, music, poetry, photography, woodwork, needlework (no tattoos, please) — if you created it, please share it! The usual limit is 5 pieces per artist, but exceptions can be made. Please submit work to [Maria Rhew](https://info.phsc.edu/course-schedule/bio/maria-rhew) at the West Campus library, room J139, by the end of Monday, May 21.

**Comment by C13L0** [comment]
completed
