### ISSUE TITLE
DE Articulation Agreement

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#179]
@curtiskphsc 

Please work with Admissions to update the content as requested.

From: Kelly Houck
Sent: Wednesday, April 25, 2018 05:05 PM
To: Webmaster
Subject: Re: DE Articulation Agreement
 
I am sorry but I do not see it. I only see the private school and home school info.

Thanks,

Kelly

From: Webmaster
Sent: Wednesday, April 25, 2018 10:31:49 AM
To: Kelly Houck
Subject: Re: DE Articulation Agreement
 
Good morning,

You can find dual enrollment information on the Admissions website at https://admissions.phsc.edu/getting-started/high-school-students

Please let me know if you do not find the information you are looking for and I will send a request to the Admissions department to update their dual enrollment page.

Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

From: Kelly Houck
Sent: Wednesday, April 25, 2018 10:20:25 AM
To: Webmaster
Subject: DE Articulation Agreement
 
I am hoping for assistance in locating the Pasco County Public School Articulation Agreement for Dual Enrollment.

I see the links for home school and non-public, but not the public. 

Thanks,

Kelly Houck

Advisor, West Campus

(727) 816-3383

**Comment by curtiskphsc** [comment]
@C13L0 I have reached out to Dr. Bibbo and as he was not in today he requested I contact Josie Oliver. I called and left her a message around 2 pm today, Thursday, April 26, 2018.

**Comment by curtiskphsc** [comment]
@C13L0 Dean Thorn is working to reestablish these documents on our website. She stated she would work with Admissions to get this accomplished.

**Comment by curtiskphsc** [comment]
@C13L0 I am closing this. Dean Thorn was to work with Admissions directly as I do not have access to the current articulation agreements.
