### ISSUE TITLE
Intranet posting for Tuesday, 5/1 or before

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#184]
From: Claire Cohn
Sent: Thursday, April 26, 2018 10:50 AM
To: Webmaster
Subject: Intranet posting for Tuesday, 5/1 or before
 
Good morning,

The Foundation is participating in Give Day Tampa Bay on May 1st. If it is possible, could you please post the following announcement on or before Tuesday, May 1st? 

The PHSC Foundation will be participating in Give Day Tampa Bay on Tuesday, May 1st, with a goal of meeting matching opportunities and doubling the impact of your donations. If you'd like to get your employee giving commitment out of the way early in 2018 and help us secure additional resources for student scholarships, professional development, and more. Click here for a breakdown of where $1.6 million is budgeted to be invested in the college this year, and here to connect with the PHSC Foundation on Facebook and to make an online gift on #GiveDayTB18. 

Link to the attached pdf where it says "here" above. 

Thanks in advance,

Claire.

**Comment by curtiskphsc** [comment]
@C13L0 Could you please send along the PDF?

**Comment by C13L0** [comment]
@curtiskphsc As a reminder, you can retrieve documents at any time from webmaster email. 
[pie charts flyer.pdf](https://github.com/phsc-edu/2018/files/1961989/pie.charts.flyer.pdf)

**Comment by curtiskphsc** [comment]
@C13L0 How hard is it to just include it in the request? Giving me all of the information associated is very important.

**Comment by curtiskphsc** [comment]
@C13L0 Please link the PDF supplied by Claire to the word "infographic"

**Give Day Tampa Bay**
The PHSC Foundation will be participating in Give Day Tampa Bay on Tuesday, May 1, with a goal of meeting matching opportunities and doubling the impact of your donations. Take advantage of this opportunity to get your employee giving commitment out of the way early in 2018, and help us secure additional resources for student scholarships, professional development, and more. 
View our infographic to see a breakdown of where $1.6 million is budgeted to be invested in the college this year, and connect with the PHSC Foundation on Facebook at [@PHSCFoundation](https://www.facebook.com/PHSCFoundation/) to make an online gift on #GiveDayTB18.

**Comment by C13L0** [comment]
completed

**Comment by C13L0** [comment]
From: Claire Cohn
Sent: Wednesday, May 9, 2018 03:44 PM
To: Webmaster
Subject: Re: Intranet posting for Tuesday, 5/1 or before | 184 | For review
 
This can be taken down whenever it's convenient. 

Thanks,
Claire.

**Comment by C13L0** [comment]
completed
