### ISSUE TITLE
Smarthinking URL is not correct

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#191]
From: Raymond Calvert
Sent: Wednesday, May 2, 2018 11:01 AM
To: Webmaster
Subject: Re: Smarthinking URL is not correct
 
The Smarthinking URL on the page associated with this link https://academic-success.phsc.edu/services/resource-links  still takes a person to the portal landing page for the College instead of to Smarthinking.

Here is a screenshot of the Smarthinking link I am referring to.

Raymond Calvert
Director of Libraries
Pasco-Hernando State College
e-mail: calverr@phsc.edu
phone: 727-816-3418

From: Webmaster
Sent: Wednesday, May 2, 2018 10:52 AM
To: Raymond Calvert; Benjamin Schultze
Subject: Re: Smarthinking URL is not correct
 
Good morning,

I would like to verify this issue has been resolved, so I can close the ticket.

Thanks,

Cielo

Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

From: Webmaster
Sent: Friday, April 27, 2018 9:54:18 AM
To: Raymond Calvert; Benjamin Schultze
Subject: Re: Smarthinking URL is not correct
 
Good morning Ben!

Could you take a look at this link on the ASC website?

@Raymond Calvert Thank you for pointing this out =)

Cielo

Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

From: Raymond Calvert
Sent: Wednesday, April 25, 2018 06:35 PM
To: Webmaster
Subject: Smarthinking URL is not correct
 
The link to Smarthinking on the Academic Success Center's Resource Links page is incorrect. This is the URL I copied from the link https://idp.phsc.edu/nidp/phsc/Staff_portal.html  The link takes you to PHSC's  portal page.

**Comment by C13L0** [comment]
![smarthinking](https://user-images.githubusercontent.com/3138019/39531922-47229bbe-4dfa-11e8-93a4-067ff2424ac8.png)

**Comment by curtiskphsc** [comment]
@C13L0 If I am not mistaken, students must be logged in to myPHSC in order to access SmartThinking, thus the link goes to the portal. It has been over a year since I was a student though, so things could have changed.

**Comment by curtiskphsc** [comment]
@C13L0 The description of the link says "...available 24 hours a day, 7 days a week through myPHSC."

**Comment by curtiskphsc** [comment]
@C13L0 So to answer your question, no. The link should not point to the staff portal. It should point to the student portal.

**Comment by C13L0** [comment]
@curtiskphsc 

From the information you have provided, it sounds like we are using single sign on (SSO) from the student portal to SmartThinking. I will reach out to Jan and Jonathan to confirm. If this is correct, then students should be directed to myPHSC.

**Comment by curtiskphsc** [comment]
@C13L0 That is correct from the way I understand it to work, but again I have not attempted to use SmartThinking in quite some time. The way it used to work, from what I remember as a student, in order  to access SmartThinking students must first login to Canvas, and to login to Canvas they must use the student portal. It could be different now or my memory could be wrong :)

**Comment by C13L0** [comment]
@curtiskphsc I have reached out to Jan and Jonathon and have not heard back. Please either remove the link or find out the correct link

**Comment by curtiskphsc** [comment]
@C13L0 Changed the link to https://myportal.phsc.edu and sent an email to Ben asking for clarification. I think the link text should be tweaked a bit but I need him to respond before I make that change. Received his out of office reply.
"From Benjamin Schultze:
I will be out of the office until Monday, May 14th and I will have limited access to email. If this is urgent, please contact senior office assistant, Kristy Madden, at maddens@phsc.edu. I will reply back when I return on May 14th. 
Thank you."

**Comment by curtiskphsc** [comment]
Benjamin Schultze agreed with the link change and reworked the textual description. Closing this ticket.

**Comment by Computerrat** [comment]
For review

**Comment by C13L0** [comment]
completed
