### ISSUE TITLE
Email notification issue

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#192]
https://student-life.phsc.edu/department-information/events/campus/get-acquainted-day-east-campus
![email-issue](https://user-images.githubusercontent.com/28155245/39549767-156b7e32-4e2d-11e8-8126-f497818b9a78.JPG)

**Comment by C13L0** [comment]
@curtiskphsc Thank you! I will work with Rick Sanders on the email issue first thing in the morning. It's probably affecting all sites.

**Comment by C13L0** [comment]
Watchdog

Message | Error sending e-mail from phscwebmaster@phsc.edu to cielo.email@gmail.com: SMTP Error: Could not authenticate.
-- | --

**Comment by C13L0** [comment]
@curtiskphsc 

This is back up and running. Thank you for notifying me of the issue.
