### ISSUE TITLE
University Partners Saint Leo update

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#197]
@curtiskphsc 

Please work with Sonia Thorn to update University Partners Content and the event for May 10. I've added in the May 8 event. Please be aware there is a bug with the meridiem #196. 

I haven't uploaded the logo as there hasn't been a decision made.

--------

From: Teresa Brabham <Teresa.Brabham@saintleo.edu>
Sent: Thursday, May 3, 2018 02:02 PM
To: Webmaster
Subject: RE: Saint Leo University | Content Updates & Upcoming Events
 
 

Event Contact for ALL Events listed below:

Saint Leo University

(352) 588-8879

phsc@SaintLeo.edu

 

May 3 Description:

Take the opportunity to meet and network with staff, faculty and students. Discuss admissions requirements, course curriculum, financial aid and scholarship opportunities. Don't forget to bring your unofficial transcripts for an on-site review and apply to have your application fee waived - you could be admitted on the spot!

Education Bachelor’s, Master's, Ed Specialist, and Doctoral programs will be represented. Visits with us and have your questions answered about becoming a Lion! Learn more about our Education Center at, http://bit.ly/2r0TYDt.

 

Bitly link: https://www.saintleo.edu/adult-education-center-university-campus

 

 

May 8 Description:

Through the Adult Education Center at Saint Leo University you have the opportunity to take classes on the weekends, in the evenings or online to obtain your degree. We are partners with Pasco-Hernando State College to offer classes on their campuses and bringing additional degree options!

Take this opportunity to meet and network with staff, faculty and students to discuss admissions, course curriculum and financial aid. Don't forget to bring your transcripts for an on-site review and apply to have your application fee waived! You could be admitted on the spot!

RSVP Today: https://www.saintleo.edu/phsc-west.

Refreshments will be provided. #FutureLions

 

May 10 Description:

Take the opportunity to meet and network with staff, faculty and students, discuss admissions, course curriculum and financial aid. Don't forget to bring your transcripts for an on-site review and apply to have your application fee waived! Be admitted on the spot!

Representatives for our undergraduate and graduate degree programs will be in attendance, it doesn't matter if you are pursuing your Bachelor's degree, Master's degree, Educational Specialist or Doctorate - have your questions answered! 

Refreshments will be provided.

 

 

Please let me know if you will need anything else!

 

Best Regards,

 

Teresa Brabham Morris | MBA

Assistant Director of Admissions

Saint Leo University

Adult Education Center at University Campus

Offices located at PHSC | Brooksville, New Port Richey, Porter, & Spring Hill

www.SaintLeo.edu/aec | www.SaintLeo.edu/phsc

 

To Schedule an Appointment Call: (352) 588-8879

 

FB

 

From: Webmaster <webmaster@phsc.edu> 
Sent: Thursday, May 3, 2018 11:59 AM
To: Teresa Brabham <Teresa.Brabham@saintleo.edu>
Cc: Sonia Thorn <thorns@phsc.edu>
Subject: Re: Saint Leo University | Content Updates & Upcoming Events

 

Hi Teresa,

 

It was very nice meeting you! 

 

Thank you for providing updated contact info, website link, and general content information. This will be updated as quickly as possible.

 

We can certainly add upcoming events. Could you please provide contact information and a brief description describing each event? I've attached a screenshot providing an example of what we are looking for.

As far as the logo, we are not able to have two different logo's. Please let me know if you would rather keep the current stacked logo or replace it with Institutional Mark 6.

 

Thanks!

Cielo

 

 

 

 

Cielo Johnson, webmaster

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

727-816-3372

 

From: Teresa Brabham <Teresa.Brabham@saintleo.edu>
Sent: Thursday, May 3, 2018 10:10:29 AM
To: Webmaster
Subject: Saint Leo University | Content Updates & Upcoming Events

 

Hi there,

 

It was wonderful talking with you this morning, and learning some extremely valuable information about the new PHSC website! Based off of our conversation, I wanted to share with you the needed content updates for our Saint Leo University landing page, located off of the University Partners page under the Transfer Programs section on the advising.phsc.edu website. Attached you will find the updates to our contact info, website link and general content sections.

 

Also, as mentioned we do have some UPCOMING EVENTS that we would love to have listed on the page. Those are as follows:

May 3, 2018 | 4:30-7 p.m.

Education Information Session

PHSC New Port Richey Campus: G-110

 

May 8, 2018 |4:30-7 p.m.

Meet Us on the West Side

PHSC New Port Richey Campus: S-307

 

May 10, 2018 | 4:30-7 p.m.

Meet n’ Greet

PHSC Spring Hill Campus: E-108

 

Would it be possible to have a different logo solely on the University Partners landing page for our University? The current “stacked logo” is leaving a lot of extra white space. So if possible, we’d like to use the Institutional Mark 6 in its place, which I have attached in a PNG file. However, we’d like to keep the “stacked logo” as is on this page: https://advising.phsc.edu/transfer-programs/university-partners/saint-leo-university

 

Please let me know the timeline for this to be completed. We truly appreciate your assistance. I look forward to working with you!

 

Best Regards,

 

Teresa Brabham Morris | MBA

Assistant Director of Admissions

Saint Leo University

Adult Education Center at University Campus

Offices located at PHSC | Brooksville, New Port Richey, Porter, & Spring Hill

www.SaintLeo.edu/aec | www.SaintLeo.edu/phsc

 

To Schedule an Appointment Call: (352) 588-8879

**Comment by C13L0** [comment]
Updates
[PHSC SLU Website Updates.docx](https://github.com/phsc-edu/2018/files/1972227/PHSC.SLU.Website.Updates.docx)

**Comment by curtiskphsc** [comment]
@C13L0 Who is the content owner? I think Advising is Chiquita. Can they not make contact updates? I don't mind assisting, but the content owners need to get used to entering and editing content or I will forever be doing it myself.
Also, there are two _past events_ showing as _upcoming_ on the page in the right side bar. https://advising.phsc.edu/transfer-programs/university-partners/saint-leo-university

**Comment by curtiskphsc** [comment]
Completed.
