### ISSUE TITLE
ADA issue

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#202]
@curtiskphsc 
https://policies.phsc.edu/policies-and-procedures/policy-statements/eoe-ada-compliance

--------------

From: Melissa Harts
Sent: Monday, May 7, 2018 12:48 PM
To: Webmaster
Subject: Fw: ADA issue
 
Please submit this as a ticket as per the attorney. This should be added to end of our disclaimer for ADA compliance. Thank you.

As we discussed, to help minimize any legal risk, I recommend that we update the disclaimer to add language stating, “If you are using a screen reader or assistive technologies and have difficulties accessing any content on the College’s website, please email webmaster@phsc.edu for assistance.”

Melissa Harts, Ed.D

Vice President of Technology and Distance Education

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

(727) 816-3466

From: Brian Koji <BKoji@anblaw.com>
Sent: Friday, April 20, 2018 11:39 AM
To: Melissa Harts
Cc: Pamela Nadolski
Subject: RE: ADA issue
 
Dr. Harts:

As we discussed, to help minimize any legal risk, I recommend that we update the disclaimer to add language stating, “If you are using a screen reader or assistive technologies and have difficulties accessing any content on the College’s website, please call [insert number] for assistance.”

**Comment by curtiskphsc** [comment]
@C13L0 If it comes from the attorney, I don't have anything to add. Also, as it is legal language it should be routed to the content owner/editor of the Policies and Governance sub domain and that appears to be Pam Nadolski. I will forward the request to her.

**Comment by curtiskphsc** [comment]
@C13L0 Completed
