### ISSUE TITLE
Disclaimer for Browsers

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#203]
@curtiskphsc 

In addition to reviewing the disclaimer, please provide where the disclaimer should be placed.

From: Melissa Harts
Sent: Monday, May 7, 2018 12:50:24 PM
To: Webmaster
Subject: Disclaimer for Browsers
 
Cielo,

Please submit the following for Marketing review as disclaimer language for the website browsers.  Thank you.

The website displays best in Chrome, Firefox, and Mozilla web browsers. 

Melissa Harts, Ed.D

Vice President of Technology and Distance Education

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

(727) 816-3466

**Comment by C13L0** [comment]
From: Melissa Harts
Sent: Monday, May 7, 2018 01:44 PM
To: Webmaster
Subject: Re: Disclaimer for Browsers
 
Yes. Thank you.


Melissa Harts, Ed.D

Vice President of Technology and Distance Education

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

(727) 816-3466




From: Webmaster
Sent: Monday, May 7, 2018 12:51 PM
To: Melissa Harts
Subject: Re: Disclaimer for Browsers
 
Absolutely! Also, our website displays with no issues in Edge. Would you like that added?



Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

**Comment by C13L0** [comment]
@curtiskphsc 

That is really a marketing decision. As per Dr. Harts, we will temporarily add the disclaimer to the footer.

**Comment by C13L0** [comment]
> This website displays best in Chrome, Firefox, Safari, and Edge web browsers.

**Comment by curtiskphsc** [comment]
@C13L0 That is actually where i would prefer it to live.

**Comment by C13L0** [comment]
completed
