### ISSUE TITLE
Ambassador Application

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#204]
From: John Fey
Sent: Monday, May 7, 2018 02:11 PM
To: Webmaster
Cc: Student Life Core
Subject: Ambassador Application
 
Please create this form for Ambassador Application.

All fields are required.  The responses go to events@phsc.edu.  

This form should be added to the Ambassador webpage https://student-life.phsc.edu/programs/student-ambassador

The Ambassador request form that is currently on the page should be moved to it's own page that can be linked to from the main Ambassador page.

Name 

Phone

Email

Campus (select all that you attend)

Credit hours completed

Credit hours enrolled 

Have you previously attended college?  Where? 

Current program of study 

Current GPA 
Why would you like to be a Student Ambassador? 

What strengths will you bring to the organization as a Student Ambassador? 

What are your goals at Santa Fe College, and when do you plan on completing those goals? 

Please include when you plan to finish your coursework at PHSC: 

What campus or other community organizations are you a member of? 

Will you be employed during the 2018-2019 academic year? If yes, where? 

How many hours/week?

**Comment by C13L0** [comment]
@curtiskphsc Please review the copy at https://student-life.phsc.edu/programs/student-ambassador-request. I simply copied from the old website.

**Comment by curtiskphsc** [comment]
@C13L0 I see no errors and have no issue with the copy as is.

**Comment by C13L0** [comment]
@curtiskphsc excellent! closing
