### ISSUE TITLE
Help and How To Question

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#207]
We are displaying duplicate content on many of our help and how to pages, specifically on financial-aid.phec.edu. 
Ideas on how to avoid this?
![help-how-to](https://user-images.githubusercontent.com/28155245/39761742-df7aa4be-52a6-11e8-9c75-f29796308d7b.JPG)

**Comment by C13L0** [comment]
@curtiskphsc @longc77
This is design/layout. We can address it in #77 

Closing...duplicate
