### ISSUE TITLE
Update auto entity label token cleanup

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#209]
admin/structure/types/manage/eday/auto-label

`[node:field_eday_date:date:relativity_node_title_date] [node:field_eday_start_hour2]:[node:field_eday_start_minute2] [node:field_eday_start_meridiem]`

**Comment by C13L0** [comment]
Note to self: Estimate hours included into #255

**Comment by jeppy64** [comment]
@C13L0 

ticket is completed

**Comment by C13L0** [comment]
Completed
