### ISSUE TITLE
Events for PHSC Mobile

### ISSUE THREAD

**Issue by 10yson** [phsc-edu/2018#210]
The ability to view _upcoming events_ and _key academic dates_ is a popular and useful tool for our PHSC Mobile users.  Please provide a method for our mobile users to see events and dates posted on our college website(s).

**Preferred method:**

- one or more JSON feeds that can be consumed by the app's Calendar module.  This method will provide me with more development options within the app.

**Alternative method:**

- one or more responsive web pages that display the desired calendar items

**Request - High Priority:**

- [ ] the upcoming (unfiltered) events displayed on the main (Marketing) website
(i.e. https://phsc.edu/about-phsc/events )

- [ ] key academic calendar dates
(i.e. https://phsc.edu/about-phsc/events FILTERED BY Deadline)

- [ ] athletic game schedules
(example https://athletics.phsc.edu/sports/womens-volleyball/fall-2017/schedule )

**Request - Normal Priority:**

- [ ] University Partner Events
(i.e .../transfer-programs/university-partner-events )

**_And, in future requests, more subdomain event calendars (like University Partners)_**

**Comment by jeppy64** [comment]
Estimated time: 3 hours

**Comment by C13L0** [comment]
@10yson @jeppy64 Dr. Harts has approved 3 hours for this ticket. It has been tagged as 1, meaning top priority. Please work this at the same time as events!!! 🗡

**Comment by 10yson** [comment]
@jeppy64 Please see attached for some initial test results taken on 6/19. Thanks.

[JsonEventFeedTesting-20180619.pdf](https://github.com/phsc-edu/2018/files/2124969/JsonEventFeedTesting-20180619.pdf)

**Comment by 10yson** [comment]
@jeppy64 - I updated the 6/19 test results document to also include Modo's feedback for End Date and All Day test cases.

[JsonEventFeedTesting-20180619-v2.pdf](https://github.com/phsc-edu/2018/files/2145760/JsonEventFeedTesting-20180619-v2.pdf)

**Comment by 10yson** [comment]
@jeppy64 - Please contact me (10yson) before you spend time on handling a blank end date scenario for this json feed or an "all day" scenario.  Thanks.

**Comment by 10yson** [comment]
@jeppy64 - Hi Jay.  Please connect with me **_in Slack to send me the link_** for the event JSON feed you worked on last week.  I'm unable to find it.  Was it on the Advising site or Academic Success Center site or ??

**Comment by 10yson** [comment]
@jeppy64 - Cielo was able to provide me with the updated JSON link.  Unfortunately, the date fields are still an issue.  I'm at the point in this development phase where I'd like to consider some other options.  I'll discuss more with Cielo.

**Comment by 10yson** [comment]
@jeppy64 - Is it possible to create an RSS feed of the events?  In the RSS I'm hoping you could provide

<title> = the event title
<description> = concatenation of event dates, location, event body.

**Comment by 10yson** [comment]
Examples:

Stanford
http://events.stanford.edu/xml/rss.xml

Georgia Tech
http://www.calendar.gatech.edu/feeds/academic-calendar.xml

**Comment by 10yson** [comment]
I tested the concat RSS file.  Thank you.  I think this will work if we can address the feedback items below.

Feedback:
- In the RSS \<title\> field, please remove the \<a\> HTML tag.  Just use the plain text of the event title.
- In the RSS \<dc:creator\> field (i.e. author), please remove the \<a\> HTML tag.  Just use the plain text of event author. 
- In the RSS \<description\> field:
  - for the link back to event item on main website, the \<link\> tag is not working.  Can you change it to an \<a\> style link?  
  - can you add some additional HTML formatting to this area to break up the content into readable format

**Comment by jeppy64** [comment]
Hi Mark,

Please go ahead and check if I got all your points mentioned. I think you're good to go.

**Comment by jeppy64** [comment]
@10yson  @C13L0 
One last mention:
I removed the old test feed and the new one is at:
https://dev-phsc-marketing.pantheonsite.io/rss-out/events

**Comment by 10yson** [comment]
@10yson @C13L0 
Thanks, Jay.  I was able to successfully consume this feed in the mobile app.  And Cielo, thanks for the additional formatting.  I showed the solution to Dr. Harts.  She thought it was good but she wants to see a few more refinements to the formatting before approving.  I'll share the feedback with Cielo in the next day or so.  Thanks again.

**Comment by jeppy64** [comment]
@10yson @C13L0 
Cool Mark, excellent news!

**Comment by 10yson** [comment]
@jeppy64 @C13L0 

Please make the following two changes

- [ ] (1) Please make a separate RSS feed (at least on the Marketing site) that is a filtered list of "Deadline" events

- [ ] (2) Please make the following changes to the content inside the RSS \<description\> area.

- Add a line break after the date
- Add a "Building: " label in front of building
- Add a "Room: " label in front of room
- Add Audience field, with label "Audience: "
- Remove Contact information
- Change the link text slightly so it reads, "View Full Details >>"


**Example of Expected Result**

> Tue - Jul 24, 2018 - 6:00 pm
> 
> West Campus
> Building: C
> Room: 100
> Audience: Student
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
> 
> View Full Details >>

**Comment by 10yson** [comment]
Test results look great!  Thank you both.  I look forward to implementing these feeds once they are promoted to production.

**Comment by jeppy64** [comment]
@C13L0  @10yson 

this feature has been completed on all sites against ticket #255 

mentioned above, the athletics feed will be automatically completed upon completion of ticket #259

**Comment by 10yson** [comment]
Thank you.  I've reviewed the All Events feed and the Deadline feed produced on the main (Marketing) site as well as those same feeds produced on a few other sub-domains.  The feeds meet the objective and work as expected.
