### ISSUE TITLE
Administration Page

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#215]
From: Janice L Scott
Sent: Tuesday, May 8, 2018 09:38 AM
To: Melissa Harts; Kevin Curtis; Webmaster; Cielo Johnson
Cc: Lucy Miller
Subject: Re: Administration Page
 
Good Morning,

We can differentiate Administrators by looking at the pay grade in the HR system.  That will help us determine their Admin status.

We now have a full title that is 100 characters in length to cover the position titles that are long so there should be no issue there.  We also did that on the department as well.

Cielo, Is there a place in the file that we can use to show who is Admin?

**Comment by C13L0** [comment]
From: Janice L Scott
Sent: Wednesday, May 9, 2018 11:11 AM
To: Webmaster; Cielo Johnson
Cc: Melissa Harts
Subject: Follow-up for the Changes needed for the Admin Director
 
Good Morning,


I wanted to send a follow-up email regarding our discussion yesterday for changes needed on the Bio file to help support the Administrator page.


 We will add a column that will have an A for each employee that is an Administrator
You will send me the path and filenames of the pictures for the Administrators.  I need for the file name to be consistent with the data we have in HR so I will be matching the file names with the lastname, first name, MI in HR to come up with the appropriate file name.  Some file names will probably need to be changed but we need to make sure there is a consistent manner for us to determine what the file name will be. We will then add a column for the file name and path
Please send me the list of Titles that are incorrect so that I can work with HR to correct them.
Is there any other data that you will need for the administrator page that we are not sending in the file?

**Comment by C13L0** [comment]
From: Janice L Scott
Sent: Thursday, May 10, 2018 09:47 AM
To: Dave Mayler
Cc: Webmaster; Cielo Johnson; Melissa Harts; Vivian Friend; Kevin Curtis; Lucy Miller
Subject: Changes to BIO file for Website Directory
 
Good Morning,


I populated the CLS.MGTCAT with an A for all people that need to be on the Administrator page.  


We need to add 2 columns to the file:


 Administrator - Populate with an "A" if the CLS.MGTCAT is = to "A".
url for the picture:  The filename of the picture will be ERMST FIRSTNAME-LASTNAME. png.   The full url will be https://info.phsc.edu/sites/default/files/styles/bio_portrait_165/public/bio/image/<filename>.png

Example is https://info.phsc.edu/sites/default/files/styles/bio_portrait_165/public/bio/image/william-shustowski.png

This way we will be able to derive the file name from values in CHRS.

If you have any questions,  please let me know.

Thank you!

Jan..

**Comment by DrivinDave** [comment]
Good afternoon Dave,

FYI~

A potential Paramedic applicant was unable to view the TC-PARA application and checklist so he came into our office today for assistance. Karen Dittman and myself tried to click to link to view/print both for the student and were unable to do so. It appears the link may be broken.


We, however, were able to view/print the link after removing the index.php that you recommended

**Comment by C13L0** [comment]
@DrivinDave Thank you for that info. It belongs in ticket #175

**Comment by DrivinDave** [comment]
@C13L0  I have placed the comment in the proper area. Thanks

**Comment by C13L0** [comment]
Assigning to @jeppy64

**Comment by jeppy64** [comment]
Estimated time: 3 hours

**Comment by C13L0** [comment]
@jeppy64 This has been approved for 3 hours this ticket. It has been given a priority of 2. Please complete after ticket 255 has been completed

**Comment by C13L0** [comment]
@jeppy64 I have this file. Ping me when ready =)

----------

Good Morning Cielo,

Attached is the Bio File (Directory) with the new fields for the Admin Directory.  The Schedule file for the new field that will designate the Current Term (Default Term) is already in the files you are getting from us for the Schedule on the Web.  Remember, please do not open and save with Excel as you will remove the leading zeros for the ID number.

**Comment by C13L0** [comment]
@jeppy64 

--------

From: Webmaster
Sent: Monday, August 6, 2018 03:35 PM
To: Janice L Scott; jeppy64@gmail.com
Subject: Administration page | 215 | Open
 
Hi Jan,

There are quite a few issues with the new bio file which has the new administration information. Jay would like to do a skype screenshare in order to go over the file. 

When is a good time to meet? It shouldn't take too long to review.


Thanks,

Cielo

**Comment by jeppy64** [comment]
@C13L0 
Happy to report the new bio file is pristine :) On my side of things it's a definite go!

We have a little challenge on the admin directory images where if the bio feed file borks, we have to manually upload all bio records tagged as admin.

Here's what I'd like to do:
1: Create a new directory in the course schedule file storage system (portrait_images) under sits/default/files
2: Bulk upload all of our newest portrait images to that new directory
3: Install the Feeds Image Grabber module https://www.drupal.org/project/feeds_imagegrabber/releases/7.x-1.x-dev
4: Config the grabber to populate our existing Portrait Image field (which includes image cache, views styling etc)

So really, we will store a portrait image in 2 places, once in the new source directory (becomes our feed image source) and a 2nd time in the existing image style buckets within drupal's files.

If the bio file chokes and all users are wiped we will always be pulling the image back in on the feed fully automated with an intact user build and an intact admin directory build.

**Comment by C13L0** [comment]
@jeppy64 Artem added the new bio file to the live feed and it runs like a champ. This is approved, please invoice.

**Comment by C13L0** [comment]
@curtiskphsc The new automated directory has been completed and tested. However, you will still need to manually upload admin images. 

Please send me the default image you would like to be used when someone doesn't have an image available.

**Comment by curtiskphsc** [comment]
@C13L0  Place holder icon for admin with no actual image ![admin-profile-icon](https://user-images.githubusercontent.com/28155245/44150885-e0c2e08c-a06e-11e8-8fb4-2c328a830670.png)

**Comment by C13L0** [comment]
@curtiskphsc Default image has been added

**Comment by curtiskphsc** [comment]
@C13L0 The current admin directory is incorrect. The last time I rebuilt it, Lucy requested that the following individuals be added. These individuals were added to the admin directory at that time and are now absent.
Darcy McDowell
David McCain
John Collins
Jonathon Myers
Keith Braun
Wayne Miller

**Comment by C13L0** [comment]
Since we are now automating the Admin Directory, all changes must go through HR. We cannot manually add them as it will just be overwritten in 2 hours when cron runs.

**Comment by curtiskphsc** [comment]
@C13L0 @boettcc Okay, thanks for the info. Also, I see an option to add information to the bios such as degrees earned and links to those institutions as the old directory once displayed. If this information is added:
a) Will it display on the bio page and where?
b) Will it be overwritten when cron runs if we add it manually?

We currently have no way of knowing who has earned degrees and constantly have to reference an archived catalog that is several years old or contact HR. It would be spectacular to at least show this info on the admin directory if possible.

Also, I do appreciate everyone's hard work on automating the admin directory. A giant thank you to all involved.

**Comment by C13L0** [comment]
@curtiskphsc Any bio information that is manually added will be deleted on cron run. This would have to come directly from HR.
