### ISSUE TITLE
Cindy Bellamy Retirement Celebration

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#216]
From: Edith Buffington
Sent: Thursday, May 10, 2018 12:59 PM
To: Webmaster
Subject: Cindy Bellamy Retirement Celebration
 
Please post this announcement on the internal webpage prior to the event. 

Thank you 

Cindy Bellamy will be retiring from the College after 35 years of service.  Please join us in celebrating Cindy’s retirement by stopping by West Campus E-206 Conference room on June 26th, 2018 from 1:00 pm to 3:00 pm.   RSVP to Rhonda Dodge 727-816-3401 for this special occasion.

**Comment by curtiskphsc** [comment]
Good to go.
**Cindy Bellamy Retirement Celebration**
Cindy Bellamy will be retiring from the College after 35 years of service. Please join us in celebrating Cindy’s retirement at the West Campus on June 26, 2018 from 1-3 p.m in E206 (conference room). RSVP to Rhonda Dodge at 3401 for this special occasion.

**Comment by C13L0** [comment]
Completed-
Message will run from 6-1 to 6-26

**Comment by C13L0** [comment]
From: Edith Buffington
Sent: Wednesday, May 30, 2018 11:10 AM
To: Webmaster
Subject: Cindy Bellamy Retirement Celebration
 
Changes to Cindy Bellamy Retirement Celebration -  New Date - June 25th, 2018.   New Location - Conference Center West Campus Bldg R-151.  Same time - 1-3 pm.  Celebrating 35 years services. RSVP to Rhonda Dodge at 3401 for this special occasion. 



If we can post this as soon as possible.  
Thanks

**Comment by C13L0** [comment]
completed
