### ISSUE TITLE
Correction to Website

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#218]
https://phsc.edu/about-phsc/news/press-release/phsc-offers-martial-arts-and-self-defense-course-health-care

From: Karen Strouthopoulos
Sent: Wednesday, May 16, 2018 08:17 AM
To: Webmaster
Subject: Re: Correction to Website
 
Webmaster,

Please make correction regarding Room # for the Martial Arts course being offered.  It should read: R-151

**Comment by curtiskphsc** [comment]
completed
