### ISSUE TITLE
remove FA form

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#221]
From: Kim Williams
Sent: Thursday, May 10, 2018 10:26 AM
To: Webmaster
Subject: remove FA form
 
Hi Cielo;

I wanted to remove this 2017-2018 form from our web page and wasn't certain I did that request correctly?  Here is the URL for the form I want removed , , lol , , thanks! https://financial-aid.phsc.edu/sites/default/files/documents/2017-2018-childcare-grant-application.pdf

**Comment by curtiskphsc** [comment]
@C13L0 Just so I am 100% certain of the process. Only the content author has delete permissions?
This has been completed.

**Comment by C13L0** [comment]
@curtiskphsc Just temporarily. As soon as we roll out the updated document moderation (scheduled and unscheduled) then they will be able to remove/delete any document. Currently, 

---
Closing ticket
