### ISSUE TITLE
10K bach

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#223]
From: Janice L Scott
Sent: Tuesday, May 15, 2018 04:34 PM
To: Kevin Curtis; Stanley Giannet
Cc: Lucy Miller; Cielo Johnson; Webmaster
Subject: Re: 10K bach
 
This is awesome!  Thank you Kevin for turning this around so quickly.  I appreciate it.  

As soon as we know the url than Dr. Giannet, we can complete the survey.

Janice L. Scott
Executive Director of Management Information Services
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
Telephone (727)816-3424
Fax (727)816-3315
email scottj@phsc.edu

From: Kevin Curtis
Sent: Tuesday, May 15, 2018 3:49 PM
To: Janice L Scott; Stanley Giannet
Cc: Lucy Miller; Cielo Johnson; Webmaster
Subject: Re: 10K bach
 
Adjusted copy per Dr. Giannet's request attached.

As soon as the page is created I will drop in the attached copy.

Kevin

From: Janice L Scott
Sent: Tuesday, May 15, 2018 3:26:33 PM
To: Stanley Giannet; Kevin Curtis
Cc: Lucy Miller; Cielo Johnson; Webmaster
Subject: Re: 10K bach
 
Thank you so much!  and Stan, excellent news on the two new concentrations.

Janice L. Scott
Executive Director of Management Information Services
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
Telephone (727)816-3424
Fax (727)816-3315
email scottj@phsc.edu

From: Stanley Giannet
Sent: Tuesday, May 15, 2018 3:25 PM
To: Kevin Curtis; Janice L Scott
Cc: Lucy Miller; Cielo Johnson; Webmaster
Subject: Re: 10K bach
 

I approve the content and the placement of the link in the location suggested by Kevin.

One change - please add the two new concentrations to the existing three- cyber and aviation, and remove the "coming soon" and "pending sacscoc accreditation" references.  

We recently received the approval from SACSCOC. 
___________

Cielo - Please create a separate page that will link to the /academics page entitled "$10,000 Baccalaureate Degree"

Kevin will send the revised copy for inclusion.
__________

Thank you all for working on this.

STANLEY M. GIANNET, PH.D. 
Vice President of Academic Affairs & 
Faculty Development  |  College Provost 
Pasco-Hernando State College

**Comment by curtiskphsc** [comment]
@C13L0 Content has been added to the page.

**Comment by C13L0** [comment]
completed
