### ISSUE TITLE
Financial Aid FAQ and "Help" title

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#226]
@curtiskphsc I wasn't sure if you wanted a ticket or not. Feel free to close it if you feel it isn't needed.

-----

From: Kevin Curtis
Sent: Wednesday, May 16, 2018 11:45 AM
To: Lucy Miller; Corey Long; Courtney Boettcher; Kim Williams
Cc: Webmaster
Subject: Re: Financial Aid FAQ and "Help" title
 
Good Morning,

I am going to take a look at the analytics on this for the Financial Aid sub domain. I plan to also look at our other sub domain data regarding this link. 

Also, the help and how to (FAQs) were just recently completed so it is possible that the "Help" link click count will be low as anyone clicking the link before the FAQs were completed would not be likely to try it again. 

Kevin

From: Lucy Miller
Sent: Wednesday, May 16, 2018 9:44:41 AM
To: Corey Long; Kevin Curtis; Courtney Boettcher; Kim Williams
Cc: Webmaster
Subject: Fw: Financial Aid FAQ and "Help" title
 
Good morning, all . . . Please see Kim's request for drawing attention to Financial Aid "help" info.  

Kim, what suggestions did you have that weren't workable -- and did you learn that from our team? 

Maybe we can start with that idea and come up with an alternative suggestion.  At least this may be a good place to start.  

Lucy

Lucy Miller
Executive Director,
Marketing & Communications
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3448
FAX: 727-816-3723
millerl@phsc.edu

From: Webmaster
Sent: Wednesday, May 16, 2018 8:12 AM
To: Kim Williams; Lucy Miller
Subject: Re: Financial Aid FAQ and "Help" title
 
Good morning Kim,

This is certainly a discussion to have with Marketing. I will be happy to make any changes they request regarding "Help".

Thanks!

Cielo

Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

From: Kim Williams
Sent: Tuesday, May 8, 2018 11:14 AM
To: Webmaster
Subject: Financial Aid FAQ and "Help" title
 

Hi Cielo;

I am wondering if there is a creative way we can direct students to the "Help" tab so they understand that we keep numerous important financial aid FAQ information on that page? I really wish that "Help" tab could be changed to something that better reflects our FAQ information, but I was told that wasn't an option. 

Can you think of some other way to better inform students that important reference information is available on this "Help" tab? From the feedback I have gathered to date, students are telling me they do not see the "Help" tab or page as a place where they would go to look for this information. 

I am thinking you might have some ideas for me? To direct students to our awesome "Help" page!! 😊

Sincerely,

Kim Williams
Associate Director-Financial Aid
Pasco-Hernando State College 
10230 Ridge Road
New Port Richey, FL  34654
727.816.3195

**Comment by C13L0** [comment]
Ticket cleanup: Please review or close

**Comment by curtiskphsc** [comment]
@C13L0 This is a bigger picture issue and we should probably review it more thoroughly at a later date. I plan to perform a comprehensive review of all menu items and their use numbers after November 30, 2018. At that time we can look at what changes we might want to make to menu items and link text.
