### ISSUE TITLE
Library hours

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#229]
From: Raymond Calvert
Sent: Thursday, May 17, 2018 10:40 AM
To: Webmaster
Subject: Library hours
 
Summer library hours for all campuses is 8 am to 7:30 pm Monday through Thursday.  We will be closed Friday through Sunday and on the two designated holidays (Memorial Day and Fourth of July) when the College is closed.  

As the libraries do synchronize to the same hours each week I recommend there be a single area on the library website describing the hours rather than publishing the hours for each library.    That would simplify the the process of updating that information.

Raymond Calvert
Director of Libraries
Pasco-Hernando State College
e-mail: calverr@phsc.edu
phone: 727-816-3418

**Comment by curtiskphsc** [comment]
@C13L0 The hours and contact info on this page https://phsc.edu/student-life/libraries used to populate directly from our old directory. When the content was migrated, all of the visible content on the page was copied and then pasted into the new page as body text. I have changed this to link to the "department listings" page to find hours. Also, I swear I already changed the library hours back when we went to summer hours. I called Ray directly on May 7 to verify and made hour changes that day and evening on all department listings. Anyway, done now.
