### ISSUE TITLE
SLR workshop proposal

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#231]
https://student-life.phsc.edu/department-information/news/announcement/call-student-leadership-retreat-slr-workshop-proposals

Link to submit workshop proposal form is not correct. It should link to an event deadline which contains the workshop proposal form. The workshop proposal form is generic and can be used for any event.

**Comment by curtiskphsc** [comment]
@C13L0 Okay, but the call for proposals is not an "event" and should not be listed in the events. It is an announcement. I guess they should just visit the RSVP page then?

**Comment by curtiskphsc** [comment]
@C13L0 but technically, it is not an "event" in the true definition of the word as there is no location and no actual start time. SLR is an event, but the call for SLR proposals is simply an announcement. So, to open a webform we must always create an "event"? Which has a required date, and date start time/end time. For the date we would select the deadline date I assume of June 21, 2018. For the time, it would be just the end time which is end of day June 21 (11:55:00 PM) but a start time is a required entry.
![webform-date](https://user-images.githubusercontent.com/28155245/40321562-7d7e2ce8-5cfd-11e8-8540-5b946598500f.JPG)

**Comment by C13L0** [comment]
@curtiskphsc I would recommend putting end of business day

**Comment by C13L0** [comment]
@curtiskphsc The system doesn't know the difference between start/end time =)

**Comment by curtiskphsc** [comment]
@C13L0 Yes, but a start time is a "required" entry and there is no start time for the deadline on June 21, only and end time.

**Comment by C13L0** [comment]
@curtiskphsc Put the end time into the start time slot

**Comment by curtiskphsc** [comment]
@C13L0 I just used the start time for the deadline time but our content editors are very literal and will not understand this concept. The deadline time should probably be the "end time"
