### ISSUE TITLE
Academic Success Center: Complete video tutorial page

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#234]
This was not completed during phase 1

--------
https://academic-success.phsc.edu/services/video-tutorials

**Comment by C13L0** [comment]
@longc77 Once built, this will also need to be themed.

**Comment by longc77** [comment]
@C13L0 I have this 3-column design for video and we talked about it being easy to make it 2-column. Would this work for this or is this something we need to discuss on Thursday at our meeting?

[3-column Wireframe Mock.pdf](https://github.com/phsc-edu/2018/files/2023354/3-column.Wireframe.Mock.pdf)

**Comment by jeppy64** [comment]
Estimated time: 3 hours

**Comment by C13L0** [comment]
Video page layout and design provided by Marketing 

[Writing.Center-Video.Library-Mock.pdf](https://github.com/phsc-edu/2018/files/2336620/Writing.Center-Video.Library-Mock.pdf)

**Comment by jeppy64** [comment]
@C13L0 

Ticket completed and ready for review.

Time to complete: 3 hours as estimated above.

Steps to complete:
Added new content type for Video Tutorial
Added mgmt and block views
Set permissions

**Comment by C13L0** [comment]
@jeppy64 Video subjects needed

Developmental Math
College Level Math
Developmental Reading & Writing
MLA & APA Composition
Nursing
Science
Humanities
Foreign Language
Technology

**Comment by jeppy64** [comment]
@C13L0 
all set and ready for review

**Comment by C13L0** [comment]
@jeppy64 Signing off on this. Theming has been completed. Please close after invoicing.

**Comment by C13L0** [comment]
@jeppy64 Can this be closed?

**Comment by jeppy64** [comment]
@C13L0 

closing as complete
