### ISSUE TITLE
Phone and network outage at Spring Hill

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#241]
@curtiskphsc 

There is a phone and network outage at Spring Hill. Spectrum is working on the issue. Dr. Harts has asked for a message to be posted on the website.

**Comment by curtiskphsc** [comment]
@C13L0 This is what we used last time and Mark also placed a mobile app banner message I believe.
I have published the announcement to the website.

**Important Information: Technical Issues, Spring Hill Campus**

The Spring Hill Campus is currently experiencing an interruption of internet and phone service. The service provider, Spectrum, is experiencing technical issues in the Spring Hill area. They are aware of the interruption of service and are working to restore it as quickly as possible.

**Comment by C13L0** [comment]
Looks great! Thank you very much.

**Comment by C13L0** [comment]
Removed message as per Dr. Harts

> From: Jeff D. House
> Sent: Monday, May 21, 2018 5:12 PM
> To: Jonathan Myers
> Cc: Melissa Harts; Adam Christiansen
> Subject: Spring Hill connectivity Up
>  
> Hello, due to the power outage and losing the network, the circuit is back up again and ups units show online. 
> 
> Thanks
> Jeff
