### ISSUE TITLE
2018-2019 Basketball Schedule and Roster

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#244]
@jeppy64 

From: Micheal Jones
Sent: Tuesday, May 22, 2018 10:24 AM
To: jeppy64@gmail.com; Webmaster
Subject: 2018-2019 Basketball Schedule and Roster
 
Good morning!

Let me know when we can start adding our new schedule for this season coming up.  Keep me posted.  

Thanks.

**Comment by C13L0** [comment]
@jeppy64 This issue should be solved once #195 is completed

**Comment by C13L0** [comment]
Note to self: The approved estimate is included in ticket #255

**Comment by C13L0** [comment]
@jeppy64 Can this be closed?

**Comment by jeppy64** [comment]
@C13L0 
closing as complete
