### ISSUE TITLE
Notice on Intranet

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#247]
@curtiskphsc I'm creating a ticket as I haven't been provided any information concerning the electronic Marketing request form.

From: Karin Glessner
Sent: Tuesday, May 22, 2018 04:28 PM
To: Webmaster
Cc: Vivian Friend
Subject: Notice on Intranet
 
Hello, Cielo:

as per Ms. Friend's instructions, I'm enclosing a statement to be posted on the PHSC Intranet:

"Our sincere sympathies go to Spring Hill Campus VA advisor, David Stroud, and his wife, Karen, who lost their son, Talon (21), on May 16, 2018. Talon was working toward his Bachelors in Public Health at Florida Gulf Coast University in Ft. Meyers. He graduated from Dover High School in Dover, Delaware, and loved nature and spending time outdoors with his family, going on camping fishing and hiking trips. A gathering of family and friends was held on May 21, 2018. Our thoughts and prayers are with his family during this difficult time."

Thank you for your assistance,

Karin

**Comment by curtiskphsc** [comment]
@C13L0 Courtney was working on tweaking the language I think as well as working with Mark on a Sharepoint form. She is not in today. I will ask about it tomorrow.

**Comment by curtiskphsc** [comment]
@C13L0 In the meantime, go ahead and post with this as is.

**Condolences**
Our sincere sympathies go to Spring Hill Campus VA advisor, David Stroud, and his wife, Karen, who lost their son, Talon (21), on May 16, 2018. Talon was working toward his Bachelors in Public Health at Florida Gulf Coast University in Ft. Meyers. He graduated from Dover High School in Dover, Delaware, and loved nature and spending time outdoors with his family, going on camping fishing and hiking trips. A gathering of family and friends was held on May 21, 2018. Our thoughts and prayers are with his family during this difficult time.

**Comment by C13L0** [comment]
completed
