### ISSUE TITLE
Course schedule default semester

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#249]
Jan has provided a new column to map the current semester. 

From: Janice L Scott
Sent: Wednesday, May 9, 2018 3:28 PM
To: Artem Geyvandov; Cielo Johnson
Cc: Melissa Harts
Subject: Re: New field for schedule file
 
Thank you Artem.  Cielo this is so you can work on the Default Term filter.  If you need any assistance please let us know!

Janice L. Scott
Executive Director of Management Information Services
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
Telephone (727)816-3424
Fax (727)816-3315
email scottj@phsc.edu

From: Artem Geyvandov
Sent: Wednesday, May 9, 2018 1:01 PM
To: Cielo Johnson
Cc: Janice L Scott
Subject: New field for schedule file
 
Cielo,

I've added new field "CTERM" to schedule file as  last column.

The value "C"  in this column will specify that file record  is for  current term.

Starting from next upload  (2pm - 3pm) this field will be populated.

Artem.

**Comment by jeppy64** [comment]
Estimated time: 4 hours

**Comment by C13L0** [comment]
@jeppy64 Dr. Harts has approved 4 hours for this ticket. It has been prioritized as 2. Please work on this after ticket 255 has been completed.

**Comment by jeppy64** [comment]
@C13L0 

this has been completed.

total time: 4 hours

**Comment by C13L0** [comment]
Completed. @jeppy64 please close once invoiced

**Comment by jeppy64** [comment]
invoiced
