### ISSUE TITLE
Announcement of Updated IMMS and Board Rules

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#252]
From: Pamela Nadolski
Sent: Wednesday, May 23, 2018 02:25 PM
To: Webmaster
Cc: Donna Burdzinski; Brian Horn
Subject: Announcement of Updated IMMS and Board Rules
 
Cielo,

We need to do another announcement of updated IMMs and Board rules on the INTRANET Page.  Therefore please see the below.

Office of Policies and Governance announces that the following IMMs were recently updated and are posted on the PHSC Intranet site:  IMM 1-1, IMM 1-19, IMM 1-30, IMM 1-31, IMM 2-30, IMM 2-31, IMM 3-1, IMM 3-3, IMM 3-4, IMM 3-8, IMM 7-2. 

Office of Policies and Governance announces that the following Board Rules were recently updated and are posted on PHSC's website:  6Hx19-1.14, 6Hx19-1.19, 6Hx19-1.20, 6Hx19-1.21, 6Hx19.1.22, 6Hx19.1.33, 6Hx19-2.551, 6Hx19-2.56, 6Hx19-3.04, 6Hx19-3.06, 6Hx19-3.10, 6Hx19-3.25, 6Hx19-5.01, 6Hx19-5.05, 6Hx19-5.06, 6Hx19-5.11, 6Hx19-5.12, 6Hx19-5.14, 6Hx19-5.16, 6Hx19-5.26, 6Hx19-5.28, 6Hx19-5.31, 6Hx19-5.32, 6Hx19-5.33, 6Hx19-5.45, 6Hx19-6.03, 6Hx19-6.06, 6Hx19.6.07, 6Hx19-6.38, 6Hx19-6.43, 6Hx19-7.06.  Many changes were minor.  The Board Rules that had more substantive changes were 6Hx19-1.20, 6Hx19-1.33 and 6Hx19-2.56.

If you have any questions, please do not hesitate to call Pam Nadolski in the Office of Policies and Governance at Extension 3746.

Pamela A. Nadolski, FRP ACP

**Comment by curtiskphsc** [comment]
@C13L0 Good to go
**Recent IMM and Board Rule Changes**
The Office of Policies and Governance announces that the following IMMs were recently updated and are posted on the PHSC Intranet site: IMM 1-1, IMM 1-19, IMM 1-30, IMM 1-31, IMM 2-30, IMM 2-31, IMM 3-1, IMM 3-3, IMM 3-4, IMM 3-8, IMM 7-2.

The Office of Policies and Governance announces that the following Board Rules were recently updated and are posted on PHSC's website: 6Hx19-1.14, 6Hx19-1.19, 6Hx19-1.20, 6Hx19-1.21, 6Hx19.1.22, 6Hx19.1.33, 6Hx19-2.551, 6Hx19-2.56, 6Hx19-3.04, 6Hx19-3.06, 6Hx19-3.10, 6Hx19-3.25, 6Hx19-5.01, 6Hx19-5.05, 6Hx19-5.06, 6Hx19-5.11, 6Hx19-5.12, 6Hx19-5.14, 6Hx19-5.16, 6Hx19-5.26, 6Hx19-5.28, 6Hx19-5.31, 6Hx19-5.32, 6Hx19-5.33, 6Hx19-5.45, 6Hx19-6.03, 6Hx19-6.06, 6Hx19.6.07, 6Hx19-6.38, 6Hx19-6.43, 6Hx19-7.06. Many changes were minor. The Board Rules that had more substantive changes were 6Hx19-1.20, 6Hx19-1.33 and 6Hx19-2.56.

If you have any questions, please do not hesitate to call Pam Nadolski in the Office of Policies and Governance at 3746.

**Comment by C13L0** [comment]
completed
