### ISSUE TITLE
Relativity Core Event Restructure for Domain Specific Events

### ISSUE THREAD

**Issue by jeppy64** [phsc-edu/2018#256]
Domain Specific events are:
<s>Academic Success Center: Tutor Schedule, Tutor Time Slot</s> This is being addressed in #233 

Advising: University Partner Schedule, University Partner Event Day - Completed (get the map in sb1)
Athletics: Athletic Competition - Completed
Financial Aid: Financial Aid Calendar - Completed
Student Life: Organization Schedule - Completed
Equity Services: Programs - (no specific events)

The following, existing tickets are all part of this initiative:
Ticket #122 - Completed
Ticket #177
Ticket #209 - Completed
Ticket #210 - Completed
Ticket #230 - Waiting for input/approval
Ticket #255 (master initiative)

Estimated time including migrations of upcoming events: 40 hours.

**Comment by C13L0** [comment]
@jeppy64 As per our discussion, please make sure that core events remains in it's own view. Special configs per site should have their own view.

**Comment by C13L0** [comment]
Example:
https://admissions.phsc.edu/

![event-example](https://user-images.githubusercontent.com/3138019/40501190-29cc746a-5f55-11e8-8ec6-5fe16ec40c0d.png)

**Comment by C13L0** [comment]
Note to self: The approved estimate is included in ticket #255

**Comment by C13L0** [comment]
Completed
