### ISSUE TITLE
Add "Help" to Safety and Security

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#257]
Add help back to the main menu

**Comment by C13L0** [comment]
@curtiskphsc This has been completed.

**Comment by C13L0** [comment]
Assigning to @curtiskphsc to work with David on https://safety.phsc.edu/help

**Comment by curtiskphsc** [comment]
David and I are supposed to be meeting soon to discuss this. Waiting for a meeting confirmation.

**Comment by C13L0** [comment]
@curtiskphsc 
Ticket cleanup: Please review

**Comment by curtiskphsc** [comment]
@C13L0 I have reached out to David and will do so again.

**Comment by curtiskphsc** [comment]
@C13L0 email communication sent 8-1-2018 requesting a meeting with David.

**Comment by curtiskphsc** [comment]
@C13L0 David has been trained in person on how to enter content. He is aware the Help section requires content and is to contact the Webmaster for any specific Help categories he may need.
