### ISSUE TITLE
Relativity Athletics Restructure

### ISSUE THREAD

**Issue by jeppy64** [phsc-edu/2018#259]
Based on Steve, Micheal and Tom's feedback since launch:

- Merge a sport schedule and their individual competition records into a single step rather than first creating competitions, then adding them to the schedule one by one.

- Merge a sport roster and their individual athletic profiles into a single step rather than first creating all the athletic profiles, then adding them one by one to their roster.

- Allow  each sport to create their own season start and end dates.

- Allow each sport to have more than one season per year (ex; baseball exhibition is fall, but real season is spring) but always default to one unless overridden.

- Create new athletics front page upcoming calendars per sport.

- Add new front card to easily get to the archives to see previous seasons, rosters and season records.
Create JSON data feeds of upcoming competitions for consumption by the PHSC mobile app and for import (via Migrate module) into the main phsc website. (single site data entry).

- Decide if we are going to show a list of transfers or remove this concept totally.

- Decide if we are going to show a list of "In the Pros"

- Decide if the current Season Recap should be removed 

This ticket also involves ticket #256 as competitions and seasons will require new date/time formatting.

This references the following previous tickets:
Ticket #3 
Ticket #244

Existing time estimate was at 48 hours. Let's leave it at that until we get further feedback on direction to see if we can keep the estimate as is, or if there are additional requests or changes. This estimate is above and beyond ticket #256 which is directly related only to date/timestamp handling.

**Comment by C13L0** [comment]
From: Steve Winterling
Sent: Thursday, May 31, 2018 08:56 AM
To: Webmaster; jeppy64@gmail.com
Cc: Melissa Harts
Subject: Sport Web Pages
 
Cieo and Jay,


I notice on each of the sport pages that the "About the Coach" bios are shown twice.  Also seeing that as well on the "Season Recap" page for cross country.  Can this be fixed?


Steve Winterling

**Comment by C13L0** [comment]
From: Steve Winterling
Sent: Wednesday, May 30, 2018 05:29 PM
To: Webmaster; jeppy64@gmail.com
Subject: Cross Country 2018
 
The 2018 cross country fall roster and 2018 fall schedule have been created.  We just need to remove 2017 and add these new links.  I believe you have to do this.  Would that be correct?


Steve Winterling

**Comment by C13L0** [comment]
Cielo and Jay,


Is there any way we can link the camp/application forms together and also put a camp registration link on each sport page?  I'm getting several calls from people that can find the camp information, but not the applications and camp consent forms.  It is confusing.  Any help is appreciated.


Thanks,


Steve Winterling

**Comment by C13L0** [comment]
@jeppy64 Can you please update your estimate to include the following requests?

**Comment by jeppy64** [comment]
Hi Steve,

You're all set on the menu links from the 2017 season. Also good to go on the content showing twice when landing on sport's main page and recap page.

**Comment by C13L0** [comment]
Just want to make sure this doesn't get forgotten:
Steve Winterling
Thu 5/31, 08:56 AM
Webmaster;jeppy64@gmail.com;Melissa Harts
Cieo and Jay,

I notice on each of the sport pages that the "About the Coach" bios are shown twice.  Also seeing that as well on the "Season Recap" page for cross country.  Can this be fixed?

Steve Winterling
Athletic Director/Head Baseball Coach
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3362 (office)
727-816-3354 (fax)

**Comment by C13L0** [comment]
From: Steve Winterling
Sent: Tuesday, August 7, 2018 04:00 PM
To: Webmaster
Cc: Dominique Phillips-Alvarez; Deann Newton; Jacki Wachtel; Thomas Ryan; Micheal Jones; Lyndon Coleman
Subject: Athletic Web Pages
 
Dear Webmaster:


The PHSC Athletic Department Information needs correcting as we have several changes among our staff.  We also need links for the Fall 2018 rosters and schedules set and Spring 2019 rosters and schedules.  Volleyball and cross country start their seasons in a couple of weeks.  I don't know how you want to proceed, so please let everyone know.


Thanks,


Steve Winterling

Athletic Director

**Comment by jeppy64** [comment]
@C13L0 athletics restructure has been completed and all data handling as well.

I had a conference call with Steve to serve as a training and all went well. Once he and staff go in and finish up the data side I'm sure there will be additional requests, but the core architecture, legacy data, current data, logic and displays are completed to the scope of this ticket.

The following tickets are all related to this ticket and can be closed when this ticket is approved:
Ticket #358 
Ticket #356 
Ticket #3

**Comment by C13L0** [comment]
@jeppy64 Please invoice this ticket. Any additional work will be added to ticket #371. 
Closing
