### ISSUE TITLE
content editing issue

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#260]
On the safety.phsc.edu sub domain, I have no option to edit the department hours node or add a new one.
![department-hours-issue](https://user-images.githubusercontent.com/28155245/40505112-3dc12554-5f61-11e8-968f-e0b320bfa127.JPG)

**Comment by C13L0** [comment]
@curtiskphsc This was a permissions issue, please try again!

**Comment by curtiskphsc** [comment]
@C13L0 Thanks! Why is the edit layout different on Financial Aid department hours? Has a radio button for "closed" and it is all the way at the bottom after selecting your hours. The others have a drop down selector that is above the hours. These display properly when selecting closed nothing else populates. The other layout still shows the hours when selecting closed.

**Comment by curtiskphsc** [comment]
@C13L0 Closing this as my last comment was addressed today in #269
