### ISSUE TITLE
ANSI characters

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#261]
![ansi-characters](https://user-images.githubusercontent.com/28155245/40506071-49f6559e-5f64-11e8-859b-b1052eba1274.JPG)

**Comment by curtiskphsc** [comment]
![ansi-characters-2](https://user-images.githubusercontent.com/28155245/40506128-81e676dc-5f64-11e8-88e4-757e3637dbd5.JPG)

**Comment by C13L0** [comment]
This ticket is actually related to #248 
When a user logs in, the title will auto correct. We are working at adding groups which will auto update every user on cron run.

**Comment by C13L0** [comment]
@jeppy64 Please confirm that this will be corrected once the sites can auto update on cron run. I know that Jan has fixed the issue on their end. The issue is that these particular users have not logged in since the MIS update.

**Comment by C13L0** [comment]
Duplicate of https://github.com/phsc-edu/2018/issues/275
