### ISSUE TITLE
Summer Department Hours

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#269]
From: Kevin Curtis
Sent: Wednesday, May 30, 2018 11:36 AM
To: Kim Williams
Cc: Webmaster
Subject: Re: Summer Department Hours
 
For reference, two screenshots. Academic Success Center-titled "Department hours"vs Financial Aid-titled "Business hours"

From: Kim Williams
Sent: Wednesday, May 30, 2018 8:04:17 AM
To: Kevin Curtis
Cc: Webmaster
Subject: Re: Summer Department Hours
 
Hello Cielo and Kevin;

When I try to make the changes to our department hours for the summer semester, I do not have the "none" option available for office hours that Kevin refers to in his instructions.  Can you please review and assist? 

We do need to change our Friday hours to "closed" for the summer! 😞 Thanks for your help!

Sincerely,

Kim Williams
Associate Director-Financial Aid
Pasco-Hernando State College 
10230 Ridge Road
New Port Richey, FL  34654
727.816.3195

From: Kevin Curtis
Sent: Thursday, May 24, 2018 4:03 PM
To: Kim Williams
Subject: Summer Department Hours
 
Kim,

Please log in and update your department hours when you get a chance. I have included a "How To" document for you. It is important that we follow the document instructions to maintain consistency. I did many of the other sub domains but I am unsure of your summer hours (other than Friday closed) and did not want to make any errors on your site.

Thank You,

Kevin Curtis

Web Content Manager

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

Phone: 727-816-3159

Building/Room: C205-B

**Comment by C13L0** [comment]
@curtiskphsc This has been corrected. Spring hill has been updated. Please verify this is working as expected

**Comment by curtiskphsc** [comment]
@C13L0 The only issue I see is that the word "Closed" is being forced to a second line. I assume that is because we are hiding the hour, minute, meridian-which is actually still there next to Friday, but just not being displayed. I am pleased that the information is now hidden :) It makes a world of difference as far as how it reads and presents to the visitor. Thanks!
![fin-aid-department-info-hours](https://user-images.githubusercontent.com/28155245/41000984-b2f18258-68dd-11e8-9915-e616fb60677b.JPG)

**Comment by curtiskphsc** [comment]
@C13L0 Sounds good.

**Comment by C13L0** [comment]
From: Kim Williams
Sent: Tuesday, June 5, 2018 07:07 PM
To: Webmaster
Subject: Re: Summer Department Hours | 269 | For review
 
Hello Cielo;


Thank you for your assistance!  All Financial Aid Offices are closed on Fridays for college summer hours. Unfortunately, I am not able to work on the web pages at this time. We are in full fall awarding and processing status and that is consuming all of my time. 


Is there any way you could please help me update our department schedule for all campuses to show we are closed on Fridays?  I would greatly appreciate your help with this. I hope to get back to the web pages as soon as possible to review the FAQ's and make some necessary updates. 😊


Sincerely,

Kim Williams
Associate Director-Financial Aid

**Comment by C13L0** [comment]
@curtiskphsc Can you take care of this for her?

**Comment by curtiskphsc** [comment]
@C13L0 This is done. Thanks again for working on the changes.

**Comment by curtiskphsc** [comment]
@C13L0 I checked all of the other sub domains to make sure summer hours were displaying and I noticed they do not roll "Closed" to a second line. If it is a theming issue, it appears that only financial aid's sub domain is doing it. 
![business-hours](https://user-images.githubusercontent.com/28155245/41055892-73375882-6990-11e8-9fe4-0028f7c64562.JPG)

**Comment by C13L0** [comment]
Completed
