### ISSUE TITLE
Campus Budget Meetings

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#271]
From: Cynthia L Bellamy
Sent: Monday, June 4, 2018 03:10 PM
To: Webmaster
Subject: Campus Budget Meetings
 
This message is for posting on the Intranet.

Dr. Beard and Mr. Horn will be presenting the DBOT approved 2018-2019 budget to each campus. A handout will be provided at the meetings.  If you are unable to attend one of the meetings, extra copies of the handouts will be available in the Provost's Office.  Below is a schedule of the meetings:

6/19/18
WC - R-151, 10:00 a.m.
SHC - B-105, 1:00 p.m.
NC - B-104, 3:30 p.m.

6/20/18
EC - A-240, 9:00 a.m.
PC - B-303, 11:00 a.m.
WC, M-101, 3:00 p.m.

Cindy Bellamy
Exec. Admin. Asst. to the
VP, Finance & Auxiliary Srvs. &
AVP, Facilities Mgmt. & Admin. Srvs.
727-816-3441

**Comment by curtiskphsc** [comment]
@C13L0 This is good to go. I only made style guide changes.
**Campus Budget Meetings**
Dr. Beard and Mr. Horn will be presenting the DBOT approved 2018-2019 budget to each campus. A handout will be provided at the meetings. If you are unable to attend one of the meetings, extra copies of the handouts will be available in the Provost's Office. Below is a schedule of the meetings:

Tuesday, June 19
West Campus - R151, 10 a.m.
Spring Hill Campus - B105, 1 p.m.
North Campus - B104, 3:30 p.m.

Wednesday, June 20
East Campus - A240, 9 a.m.
Porter Campus - B303, 11 a.m.
West Campus, M101, 3 p.m.

For more information contact Cindy Bellamy at 3441.

**Comment by C13L0** [comment]
completed

**Comment by C13L0** [comment]
From: Cynthia L Bellamy
Sent: Wednesday, June 13, 2018 12:50 PM
To: Webmaster
Subject: Fw: Another Location Change to Campus Budget Meeting
 
Sorry that I was confused about where to send a message. Here is the one I sent to you on Monday.


Thank you!


From: Cynthia L Bellamy
Sent: Monday, June 11, 2018 9:02 AM
To: Cielo Johnson; Kevin Curtis
Subject: Another Location Change to Campus Budget Meeting
 
Hi Cielo,

North Campus has relocated their meeting to the McKethan Room C-120 on 6/19 (instead of B-104).  


Last week, I emailed you about SH relocating their meeting to E-107 on 6/19.


Thank you.

Cindy Bellamy

Exec. Admin. Asst. to the

VP, Finance & Auxiliary Srvs. &

AVP, Facilities Mgmt. & Admin. Srvs.

727-816-3441

**Comment by C13L0** [comment]
completed
