### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#272]
From: Webmaster
Sent: Tuesday, June 5, 2018 04:16 PM
To: Gina Phillips
Subject: Re: Directory
 

Hi Gina,

Thank you for alerting us to this issue. The directory is updated every two hours through our HR system.  I spoke with Jan Scott (MIS) concerning the missing data and she is looking into it.

Cielo Johnson, webmaster
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
727-816-3372

From: Gina Phillips
Sent: Tuesday, June 5, 2018 4:13:50 PM
To: Cielo Johnson; Webmaster
Subject: Directory
 
Good Afternoon,

I'd like to relay some frustration with our online directory. I am attempting to search people by their departments, but the only way it seems I am able to look someone up is if I know their name, campus or type. This doesn't help if I don't know the persons name and don't want to go through pages of people to find someone in a specific department.

For example, if I go to the directory and put in the following information:

Name:
Anderson

Campus:
West Campus

Type:
Staff

Department:
Human Resources

It says "your last filter selection returned no results", even though there is a Maria Anderson in the Human Resources Department. 

Am I doing something wrong? 

Thanks!
Gina M. Phillips
Administrative Assistant III, Provost, Spring Hill Campus
450 Beverly Ct.
Spring Hill, FL 34604
(352)340-4802

**Comment by Computerrat** [comment]
Completed
