### ISSUE TITLE
S10,000 Baccalaureate Webpage

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#280]
From: Sonia Thorn
Sent: Tuesday, June 12, 2018 01:44 PM
To: Webmaster
Cc: Stanley Giannet; Chiquita Henderson
Subject: S10,000 Baccalaureate Webpage
 

Dear Cielo,

https://www.phsc.edu/academics/10000-baccalaureate-degree

Please update this page to state for more information about enrolling, please contact Student Affairs at https://advising.phsc.edu/services/academic-coaching.

**Comment by curtiskphsc** [comment]
@C13L0 Completed and ready for review.

**Comment by C13L0** [comment]
completed
