### ISSUE TITLE
Condolences

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#281]
@C13L0 Please post this today if possible. He passed on Sunday.

**Condolences**
It is with great sadness that we announce the recent passing of longtime PHSC employee Christopher (Chris) Wilt. Chris, a production engineer, was employed at PHSC for 17 years and was a tireless advocate for the staff, faculty, and students. He will be sorely missed. We extend our condolences to his family, friends, and colleagues, and especially to his partner Carole Wouters.

Final arrangements have not yet been made. We will update this post as soon as those details become available.

**Comment by C13L0** [comment]
@curtiskphsc completed

**Comment by curtiskphsc** [comment]
@C13L0 I am going to create a new announcement and ticket for the memorial service details. I thought this was still visible but I see it has dropped.
