### ISSUE TITLE
Cafe's summer vacation

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#282]
From: John Collins
Sent: Wednesday, June 13, 2018 11:29 AM
To: Melissa Rushton; Cielo Johnson
Cc: Brian Horn; Roy Honaker
Subject: Cafe's summer vacation
 
Hello all
If you would be so kind to post that the WC Cafe' will be taking their annual vacation July 27th
through  Aug 12th 2018. At that time they will be closed.

 Aug 13th to Aug 17th the WC Café will reopen from 8AM to 2PM
After Aug 19th the Café will return to normal operating hours.
Thank you.

**Comment by curtiskphsc** [comment]
@C13L0 Please have this reviewed before posting.
**PHSC Café Summer Vacation**
The PHSC Café at West Campus will be closed for their annual summer vacation Friday, July 27 through Sunday, August 12. The Café will reopen Monday, August 13 with 8 a.m. to 2 p.m. operating hours through Friday, August 17. Normal business hours will resume on Monday, August 20.

**Comment by C13L0** [comment]
This will post on 7-1-2018
