### ISSUE TITLE
Chris Wilt Memorial Service

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#283]
**Chris Wilt Memorial Service**
A memorial service for Chris Wilt will be held at the West Campus in the Conference Center (R) on Monday, July 2, from 7 to 8 p.m.

**Comment by C13L0** [comment]
Completed

**Comment by curtiskphsc** [comment]
The deceased's loved ones have requested that we update this with the following details.

In lieu of flowers, donations are requested for either the The Humane Society of the United States or Eckerd Connects.

**Comment by C13L0** [comment]
completed
