### ISSUE TITLE
(June) Athletic Camp Forms and Downloads

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#285]
@jeppy64 can you please take a look at Athletics document permissions? They should all be able to upload and delete documents.

From: Steve Winterling
Sent: Monday, June 25, 2018 10:41 AM
To: Webmaster
Subject: Fw: Athletic Camp Forms and Downloads
 

Steve Winterling

Athletic Director/Head Baseball Coach

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

727-816-3362 (office)

727-816-3354 (fax)

From: Steve Winterling
Sent: Monday, June 25, 2018 10:41 AM
To: Kevin Curtis
Cc: Cielo Johnson; jeppy64@gmail.com; Robert E Bade
Subject: Athletic Camp Forms and Downloads
 
Kevin,

Can you please remove all camp forms except Run Camp Application, Run Camp Consent Forms, Baseball Camp Application and Baseball Camp Consent Form?  Everything else has expired and it will make it easier for the public to find the upcoming camp information.  Thank you for your help.  The system doesn't allow me to do this or I would.

Steve Winterling

Athletic Director/Head Baseball Coach

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

727-816-3362 (office)

727-816-3354 (fax)

**Comment by jeppy64** [comment]
should be good to go.... give it a whirl

**Comment by jeppy64** [comment]
15 minutes to complete

**Comment by jeppy64** [comment]
@C13L0 Completed

**Comment by C13L0** [comment]
Completed
