### ISSUE TITLE
Financial Aid Sub Domain Issue

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#287]
Received a revision notice on this node yesterday at 4:03 pm. The revision request was "Please delete" as highlighted in the first screen shot. I deleted the node shortly thereafter. Now, this morning, that revision log entry is gone and the deleted node has come back. See screen shot 2.
![revision-log-missing-node-112](https://user-images.githubusercontent.com/28155245/41983674-d67492d0-79fc-11e8-9670-62faac3d9f02.JPG)
![revision-missing](https://user-images.githubusercontent.com/28155245/41983684-da9814ea-79fc-11e8-8994-242a25cb698d.JPG)

**Comment by C13L0** [comment]
@curtiskphsc Please delete the node again. I'm not sure what you want me to do.

**Comment by curtiskphsc** [comment]
@C13L0 I ma only passing it along as a ticket as you request I do so when issues arise. I find it concerning that something reverted without our knowledge.

**Comment by C13L0** [comment]
This issue cannot be replicated for troubleshooting. Closing
