### ISSUE TITLE
Intranet Announcement Request

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#288]
Submitted PDF is blurry and upside down. Waiting for new pdf that is readable.

-------

From: Carla Rossiter-Smith
Sent: Wednesday, June 20, 2018 07:28 AM
To: Webmaster; Cielo Johnson
Cc: Sonia Thorn
Subject: Intranet Announcement Request
 
Hello Cielo,

I would like to request that the announcement below be posted to the intranet as soon as possible.  Please note that the announcement should include a hyperlink from "FAQs" to the attached pdf document.  I have also attached the image to accompany the announcement.  Please let me know if you need anything further from me.

 Have you heard that the College is moving to a new Course/Instructor Evaluation System?  Did you know that we will begin piloting the system this Fall?  Please be on the lookout for emails and webinars for more information.   In the meantime, check out this list of FAQs for more information.

Kind regards,

Carla Rossiter-Smith, MSM, PMP
Associate Dean of Institutional Effectiveness
Pasco-Hernando State College
727-816-3190
rossitc@phsc.edu

**Comment by C13L0** [comment]
@curtiskphsc Here is the updated pdf
[Class Climate FAQs.pdf](https://github.com/phsc-edu/2018/files/2156680/Class.Climate.FAQs.pdf)

**Comment by Computerrat** [comment]
Completed
