### ISSUE TITLE
AFC Bylaws Update

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#289]
From: Kathy MacLenna
Sent: Wednesday, June 20, 2018 11:37 AM
To: Webmaster
Subject: AFC Bylaws Update
 Hello,

Attached is an updated version of the AFC Bylaws.  Please replace in the internal site.

http://internal.phsc.edu/afc/f/bylaws.pdf

Thank you,

Kathy

**Comment by Computerrat** [comment]
Emailed Kathy to request further information on July 9, 2018

**Comment by Computerrat** [comment]
completed
