### ISSUE TITLE
Link for Fall Term 2019-1

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#290]
@curtiskphsc 
After meeting with Christine, concerning this ticket, it was decided the efaculty website will hold content and events for faculty and adjuncts. The content will not be specific to the e part of efaculty which Christine says is misleading. She is working on who will have access to this site and will let me know in the near future. In the meantime, please add this event to efaculty site. I've created a webform called "North Campus Adjunct Meeting" that can be attached to this event.

---------------

Good Morning!

Please find attached our Adjunct Meeting Invitation letter for our fall term 2019-1. We are in need of a link for the reply from our instructors.

> July 30, 2018
> 
> Dear ,
> 
> We invite you to attend our North Campus Fall Semester Adjunct Faculty meeting which will be held on Tuesday, August 14, 2018, in Building B, Rooms 104/105. Check-in will begin at 5:00 p.m. and dinner will be served from 5:00 to 5:30 p.m. Dr. Stanley Giannet, Vice President of Academic Affairs and Faculty Development, and Dr. Bob Bade, Vice President of Student Affairs and Enrollment Management, will be here to provide you with important division updates. We also have invited your College department chairs, who will provide you with departmental updates and expectations. We anticipate that this adjunct faculty meeting will last until approximately 8:30 p.m. Please complete your online RSVP to attend the Symposium by Wednesday, August 8, 2017 at http://phsc.edu/rsvp/adjunct-faculty-symposium
> 
> The purpose of this meeting is to provide you with the necessary updates, training, and professional development to perform your job duties well as an adjunct instructor at PHSC. This meeting also gives you the opportunity to interact with our North Campus staff and other adjuncts. These meetings are important to your success in the classroom, and I encourage you to attend. If you are unable to attend, please call Ms. Amy Eichelberger, my Administrative Assistant, at (352) 797-5002.
> 
> Please know how much we appreciate you as an adjunct member of our North Campus teaching team. We are pleased that you will be helping us to meet the College’s mission of providing outstanding teaching and creating an optimal learning environment for our students during the upcoming semester! Our focus is on student retention and college completion – and your role in helping students to achieve these goals is key.
> 
> Should you have any questions prior to this meeting, please feel free to contact me at any time at (352) 797-5001 or via email at burdzid@phsc.edu. Alternatively, you may also wish to contact Mr. Reggie Wilson, Associate Dean, North Campus, at (352) 797-5004 or via email at wilsonr@phsc.edu. We look forward to seeing you on Monday, August 14th!
> 
> Cordially,
> 
> Donna Burdzinski, Ed.D.
> 
> Provost, North Campus

**Comment by curtiskphsc** [comment]
@C13L0 I am a bit confused as to why I am being asked to create this content as 
a) the Academic Technology department is the sub domain owner and 
b) they have several employees listed as "Department Editor"

**Comment by C13L0** [comment]
@curtiskphsc Please work with Academic Technology the same as you work with other departments on their website content.

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

Joyce Myers called and is taking a new position in West Campus. She would like to mail out the letters as soon as possible so everything will be in order for the person that is hired to take her place.

**Comment by C13L0** [comment]
@curtiskphsc @boettcc I'm moving this to "Rush"

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

Joyce called this morning and has requested the event url as quickly as possible. Wednesday will be her last day at North Campus.

**Comment by C13L0** [comment]
From: Webmaster
Sent: Monday, July 23, 2018 12:39 PM
To: Kevin Curtis
Cc: Courtney Boettcher
Subject: Rush tickets 305 and 290
 
Good morning Kevin,


I hope you had a relaxing vacation =)

There are two tickets that are marked as "rush". It would be appreciated to address these as quickly as possible.


Admin Directory

https://github.com/phsc-edu/2018/issues/305


Link for Fall Term 2019-1
https://github.com/phsc-edu/2018/issues/290



Thank you,
Cielo

**Comment by curtiskphsc** [comment]
Joyce states the letter is not mailing until Monday, July 30. In the interest of the affected party, I have created this event although IMM 1-24 clearly states the sub domain owner is responsible for content creation. I am also sending Christine Smith a very detailed walk through/how to guide for creating events so that her department can have the knowledge required to create events going forward. That said, members of her staff (hidalgob and pakhomm) have recently logged in to the sub domain and made content edits, so I am still confused as to why this task was assigned to marketing. That question was posed 20 days ago and there was no explanation provided. https://efaculty.phsc.edu/department-information/events/campus/north-campus-fall-semester-adjunct-faculty-meeting Additionally, Joyce states the webform is not displaying although it is marked as "open."

**Comment by C13L0** [comment]
completed
