### ISSUE TITLE
February Newsclips

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#291]
- [ ] February 2018

[February_Newsclips.zip](https://github.com/phsc-edu/2018/files/2156640/February_Newsclips.zip)

--------

From: Tracy Horn
Sent: Thursday, June 21, 2018 03:33 PM
To: Webmaster
Subject: February Newsclips
 
Good afternoon,

 Please upload the following news clips to the intranet under marketing.

Thank you 😊

**Comment by C13L0** [comment]
March 2018
[March_2018_Newsclips.zip](https://github.com/phsc-edu/2018/files/2156664/March_2018_Newsclips.zip)

**Comment by C13L0** [comment]
April 2018
[April_2018Newsclips.zip](https://github.com/phsc-edu/2018/files/2156667/April_2018Newsclips.zip)

**Comment by C13L0** [comment]
- [ ] May 2018

[May_2018_Newsclips.zip](https://github.com/phsc-edu/2018/files/2156669/May_2018_Newsclips.zip)

**Comment by Computerrat** [comment]
All months through May 18 have been posted. Completed
