### ISSUE TITLE
Computer Lab Summer Hours

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#293]
From: Matthew Neadly
Sent: Wednesday, June 27, 2018 08:15 AM
To: Webmaster
Subject: Computer Lab Summer Hours
 
URL: https://phsc.edu/about-phsc/departments

The hours under the computer lab section should be

SH Campus
Monday - Thursday 8:00AM - 6:00PM
Closed Friday
East Campus
Monday - Thursday 9:00AM - 7:00PM
Closed Friday
Porter Campus
Monday - Thursday 8:00AM - 6:00PM
Closed Friday
West Campus
Monday - Thursday 8:00AM - 6:00PM
Closed Friday
North Campus
Monday - Thursday 7:30AM - 5:00PM
Closed Friday
Thanks,
Matthew Neadly,
Laboratory Technician, Computer Labs
Pasco-Hernando State College

**Comment by curtiskphsc** [comment]
@C13L0 completed

**Comment by Computerrat** [comment]
completed
