### ISSUE TITLE
(June) Foundation Golf Event

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#296]
@jeppy64 Please remove document double moderation. Also remove "Add new" and replace with "Add existing".

<img width="535" alt="double-moderation" src="https://user-images.githubusercontent.com/3138019/42186190-a532a66e-7e19-11e8-90ed-7d9b0f10a62a.png">

-----------

From: Jessica Staller
Sent: Monday, July 2, 2018 09:03 AM
To: Webmaster
Subject: Foundation Golf Event
 
Hi Cielo,

I was trying to put the golf tournament brochure on the wepage: https://foundation.phsc.edu/department-information/events/foundation/9th-annual-phsc-foundation-golf-tournament

When I attached the file I received the Error: 

This entity (node: PHSC Golf Tournament Brochure) cannot be referenced.                 

Am I doing something wrong? Thanks Jessica

Jessica Staller
Coordinator of Foundation Events & Marketing

District Office
10230 Ridge Road, New Port Richey, FL 34654

727-816-3110   Fax: 727-816-3450

stallej@phsc.edu

**Comment by jeppy64** [comment]
Completed

**Comment by jeppy64** [comment]
@C13L0 Completed

**Comment by C13L0** [comment]
@jeppy64 This was not completed...there is still moderation on the event document. In addition, the document doesn't show on the event. 

Also related to #255

**Comment by C13L0** [comment]
@jeppy64 Closing this! I logged in as content editor and everything was good =)
