### ISSUE TITLE
Posting for the Intranet - East Campus

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#297]
From: Courtney Benito
Sent: Monday, July 2, 2018 04:15 PM
To: Webmaster
Cc: Lisa Richardson
Subject: Posting for the Intranet - East Campus
 
Is the request for the intranet or main phsc.edu website?: Intranet
Announcement title: Employee Anniversary Celebration
Announcement message: Join the East Campus in celebrating our Employees' many years of success.
Attach any associated file attachment(s) in .pdf format: N/A
Provide URL for page to modify.: N/A
Additional detailed instructions: Date: October 17, 2018  Time: 3:00 p.m. - 4:00 p.m.
Thanks, 

Courtney Benito

Senior Office Assistant, Faculty Support, East Campus

**Comment by curtiskphsc** [comment]
@C13L0 This event is in October. Also, Courtney did not provide a building designation/location. It just says East Campus, so we need to know what building/room it will be held in.

**Comment by Computerrat** [comment]
I am so sorry about that. This will be held in room A-240, Conference Center.

Thanks, 

Courtney Benito
Senior Office Assistant, Faculty Support, East Campus
Pasco-Hernando State College
36727 Blanton Road
Dade City, FL 33523
Phone: 352-518-1314
Fax: 352-518-1225

**Comment by C13L0** [comment]
Assigning to @curtiskphsc for the intranet message

**Comment by curtiskphsc** [comment]
@C13L0 @Computerrat I have transferred this request over to Courtney Boettcher via email. She will be handling it from there, thus I am closing this ticket.
