### ISSUE TITLE
PHSC Foundation: Needs review - PHSC Foundation Welcomes New Board Member

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#298]
From: Jessica Staller
Sent: Tuesday, July 3, 2018 10:48 AM
To: PHSC Webmaster
Subject: Re: PHSC Foundation: Needs review - PHSC Foundation Welcomes New Board Member
 
This photo needs to be included with the news item below. It is too large for me to attach online and I do not have the appropriate graphic tools to adjust. Thank you

From: PHSC Webmaster
Sent: Tuesday, July 3, 2018 10:46 AM
To: Webmaster
Subject: PHSC Foundation: Needs review - PHSC Foundation Welcomes New Board Member
 
PHSC Foundation Welcomes New Board Member is ready for review
at https://foundation.phsc.edu/node/270

Submitted by: stallej on Tuesday - Jul 03, 2018 - 10:46 am

![img_0496](https://user-images.githubusercontent.com/3138019/42228063-00dde9f0-7eb1-11e8-8fef-130a06132411.JPG)

**Comment by C13L0** [comment]
@curtiskphsc @longc77 I wasn't sure who to assign this to =)

**Comment by curtiskphsc** [comment]
@C13L0  completed

**Comment by Computerrat** [comment]
copmpleted
