### ISSUE TITLE
Athletics: Re-architecture and Quick Links

### ISSUE THREAD

**Issue by jeppy64** [phsc-edu/2018#3]
Steve's Notes: Currently, there are four steps to get to the teams.  It would be nice to have links across the top of the athletic page that takes you directly to the sport you want to see.  Also, there is so much scrolling that people miss information.  This is some of the feedback I have received from local fans.
The basketball schedule also needs to be examined. Currently, it is split into two seasons and it should be one schedule so the record will be correct.  For the fall it has the record as 2-12 and spring record as 1-2.  It should show the record is 3-14.  It would also be nice if the schedules could be condensed more, so we can see all of the results on one page.  Here is a link that looks good as an example: http://thefcsaasports.com/sports/mbkb/2017-18/schedule?teamId=d2ye7gtfipelrt19

The Plan:
1: Add front page quick links dropdown to go to Sport Landing Pages
1a: Alternate to above: Add new Card per sport to front page to replace current cards
2: Merge schedule nodes into one per sport spanning multiple semesters
3: Add athletic competition views to front page
4: Change date and time entities to allow for Add to Calendar
5: Update all nodes when done with architecture additions
6: Correct all athletic profiles added into wrong season

Est Time: 30 hours

**Comment by C13L0** [comment]
@jeppy64 Please review and update estimate to include associated tickets #244 and #195

**Comment by C13L0** [comment]
Note to self: The approved estimate is included in ticket #259

**Comment by C13L0** [comment]
@jeppy64 I think we can close this ticket as it was included in #259

**Comment by C13L0** [comment]
@jeppy64 Can we close this ticket?

**Comment by jeppy64** [comment]
@C13L0 
closing as complete
