### ISSUE TITLE
Admin Directory

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#305]
@curtiskphsc @boettcc 

As per the issue below, Administrators need to be added back to the Administration Directory. https://info.phsc.edu/directory/administration

As soon as @jeppy64 has completed Events ticket #255 he will begin working with MIS on ticket #215 to make the Administration directory automated.

-----------------

From: Janice L Scott
Sent: Monday, July 23, 2018 10:27 AM
To: Cielo Johnson
Subject: Directory and Course Schedule Instructor
 
Good Morning,  Happy Monday.  We made a mistake last week with the bio file and added two column headings that were not supposed to be there.  We are fixing the file and need for you to manually run your chron job.  Can you run this now?

Janice L. Scott
Executive Director of Management Information Services
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
Telephone (727)816-3424
Fax (727)816-3315
email scottj@phsc.edu

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 
Marking this as "Rush" due to high visibility

**Comment by C13L0** [comment]
From: Webmaster
Sent: Monday, July 23, 2018 12:39 PM
To: Kevin Curtis
Cc: Courtney Boettcher
Subject: Rush tickets 305 and 290
 
Good morning Kevin,


I hope you had a relaxing vacation =)

There are two tickets that are marked as "rush". It would be appreciated to address these as quickly as possible.


Admin Directory

https://github.com/phsc-edu/2018/issues/305


Link for Fall Term 2019-1
https://github.com/phsc-edu/2018/issues/290



Thank you,
Cielo

**Comment by curtiskphsc** [comment]
Completed. 1 hour 17 minutes plus Courtney spent 30 minutes reviewing the completed list for accuracy. Round trip total: 1 hour and 47 minutes.

**Comment by C13L0** [comment]
Completed
