### ISSUE TITLE
Update Logo on All PHSC pages

### ISSUE THREAD

**Issue by longc77** [phsc-edu/2018#310]
@C13L0 Dr. Beard has approved a new PHSC master logo that aligns with our Spirit brand. The Marketing and Communications office has already started implementing it in our materials. Please update the logos on the site to reflect this change. I've included a ZIP file containing the SVG files. 

Thank you,
Corey
[site logos 2018.zip](https://github.com/phsc-edu/2018/files/2224981/site.logos.2018.zip)

**Comment by longc77** [comment]
Here are screenshots
![screen shot 2018-07-24 at 2 47 56 pm](https://user-images.githubusercontent.com/38913763/43159935-c5f6ba54-8f51-11e8-9f39-b0039c74f919.png)
![screen shot 2018-07-24 at 2 45 15 pm](https://user-images.githubusercontent.com/38913763/43159937-c60b2cdc-8f51-11e8-8214-ff86e30f9cda.png)

**Comment by C13L0** [comment]
- [ ]  Academic Success Center 
- [ ]  Admissions 
- [ ]  Advising 
- [ ]  Athletics
- [ ]  Career Services
- [ ]  Educator Preparation Institute
- [ ]  eFaculty Support
- [ ]  Equity Services
- [ ]  eStudent Support
- [ ]  Financial Aid
- [ ]  Financial Services
- [ ]  Foundation
- [ ]  Legal Department
- [ ]  Marketing
- [ ]  Office of Disabilities
- [ ]  Safety and Security
- [ ]  Student Life
- [ ]  Testing Services
- [ ]  Writing Center

**Comment by Computerrat** [comment]
All sites updated except marketing.

**Comment by longc77** [comment]
Thank you @C13L0!!

**Comment by Computerrat** [comment]
@longc77 
All sites are updated. Just an FYI, I had to clear my browser's cache for the main site to refresh.

**Comment by C13L0** [comment]
Completed
