### ISSUE TITLE
CAPTCHA session reuse attack detected 

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#313]
Students are reporting this on screen message "CAPTCHA session reuse attack detected" after submitting the West Campus GAD webform and are concerned that their submission has not been received as a result. https://student-life.phsc.edu/department-information/events/campus/get-acquainted-day-west-campus

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 
Please provide the student name and email address so I can research

**Comment by C13L0** [comment]
@curtiskphsc 
Ticket cleanup: Please review or close

**Comment by curtiskphsc** [comment]
@C13L0 The student's submission was in fact logged. Faith Graves, submission number 93

**Comment by C13L0** [comment]
@curtiskphsc awesome! The student should have also received an confirmation email that the webform went through.

Closing...working as designed
