### ISSUE TITLE
DE document 

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#317]
This document was first uploaded containing an error. After the error was corrected, the original document was deleted from the Admissions sub domain. The new document was then uploaded with the same file name because the link must be the same due to a mass communication. The document name is displaying correctly on the forms and downloads page yet the link now has a _1 at the end of it. Any suggestions on how we can correct this? https://admissions.phsc.edu/sites/default/files/documents/18-19-fall-de-online-faq_1.pdf
![de-forms-page](https://user-images.githubusercontent.com/28155245/43291774-b480572a-9100-11e8-9362-7dbb52828f15.JPG)
@boettcc

**Comment by C13L0** [comment]
@curtiskphsc 

I tested this as a document editor on the admissions website site and cannot reproduce.

Steps taken in an attempt to reproduce reported error:
1. Removed sar65b.pdf and saved
2. Added updated document with same name sar65b.pdf and saved

**The updated document updated with the correct name of sar65b.pdf.**

> Monday - Jul 30, 2018 - 12:48 pm 
> 
> johnsoc published Dual Enrollment Home School Articulation Agreement
> Information Form at https://dev-phsc-admissions.pantheonsite.io/node/327.

<img width="657" alt="sar65b-screenshot" src="https://user-images.githubusercontent.com/3138019/43411488-4a21c3b4-93f8-11e8-9560-96b25c70ad44.png">
