### ISSUE TITLE
DBOT list question

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#320]
On the DBOT members page here, https://policies.phsc.edu/district-board-trustees we have to rearrange the list order yearly. The chair is always listed first followed by the Vice Chair, and the remaining are listed in order of service longevity. Robin Schneider is Chair and should be at the top followed by Vice Chair Alvaro Hernandez. Rao Musunuru should be listed 3rd now and the rest remain where they are. Is there a way to reorder this list?
![legal-profiles](https://user-images.githubusercontent.com/28155245/43406093-7c50d082-93e9-11e8-8e8e-5df63a68e49a.JPG)

**Comment by curtiskphsc** [comment]
@C13L0 @longc77 I have rebuilt the entire list to reflect the changes in DBOT leadership for the 2018-2019 year. It would be great to have some drag handles or a numbering system as was created by @jeppy64 for the front page feature cards in order to avoid this pain point in the future. As it stands, I had to delete each entry and re-enter them in the correct order.

**Comment by C13L0** [comment]
@jeppy64 Assigning to you for draggable views. Please see Ticket #240 for design/layout.

**Comment by jeppy64** [comment]
@C13L0 

After troubleshooting I'm seeing a core regression bug.

I added a new sorting display field to allow for setting the display weight. Updated DBOT nodes and views.

Please review and close if good to go.

**Comment by curtiskphsc** [comment]
@C13L0  The new display weighting appears to work as described. I was able to reorder the list by using "edit" in manage legal profiles, and then selecting a display position. Thanks for working to improve this as it will save significant time going forward.

**Comment by C13L0** [comment]
@jeppy64 Looks good and @curtiskphsc says it is working. approved for invoice
Assigning to myself for theming #240
