### ISSUE TITLE
Career Path Documentation

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#335]
https://dev-phsc-marketing.pantheonsite.io/

@Computerrat Please review and update the current documentation for Career Paths. Login to the dev site to verify documentation and for updated screenshots. In addition, the updated pdf should be accessible. =)

This documentation is for the main website phsc.edu, please update the url too.

[marketing-careerpath.docx](https://github.com/phsc-edu/2018/files/2264251/marketing-careerpath.docx)

**Comment by Computerrat** [comment]
Changed <p> tags to h2 and h3. Verified site links.
[marketing-careerpath (3).pdf](https://github.com/phsc-edu/2018/files/2336832/marketing-careerpath.3.pdf)

**Comment by C13L0** [comment]
@Computerrat Can you please provide the updated document in word format? I need to add documentation of new features. =)

**Comment by Computerrat** [comment]
[marketing-careerpath.docx](https://github.com/phsc-edu/2018/files/2447280/marketing-careerpath.docx)

**Comment by Computerrat** [comment]
[Career Path.docx](https://github.com/phsc-edu/2018/files/2447714/Career.Path.docx)

**Comment by C13L0** [comment]
Completed!
Thank you @c
