### ISSUE TITLE
Foundation events

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#337]
Foundation needs a static event page for each of their main events. Static event page should show upcoming event along with a link to fully intact past events. This way, they do not have to manually choose which past events to display.

In Jay's words "Create event day occurrence".

This is a new ticket in reference to Foundation manage past events #177

**Comment by C13L0** [comment]
@jeppy64 

todo

- [ ] Create Annual Event management view 
- [ ] Create Annual Event Contact management view
- [ ] Create Annual Event view for the front page

**Comment by jeppy64** [comment]
@C13L0  the above 3 tasks are complete

Overall ticket resolution
Added new bundle for Annual Event
Added new bundle for Annual Event Contact
Added new bundle for Foundation Event
Migrate existing past and future Events to Foundation Event bundle
Create Annual Event nodes as wrapper
Added management views for all
Added display views duped as regular Events to retain styling

total time to complete: 26 hours
Ready for review and approval

**Comment by C13L0** [comment]
Completed
