### ISSUE TITLE
Foundation remove duplicate sponsors

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#338]
Sponsor should show all events they sponsor

<img width="667" alt="sponsors" src="https://user-images.githubusercontent.com/3138019/43777040-a7d73e58-9a1f-11e8-8442-e2d20e9e2260.png">

**Comment by C13L0** [comment]
@jeppy64 Can this be closed?

**Comment by jeppy64** [comment]
@C13L0 
closing as complete
