### ISSUE TITLE
PHCC in application document

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#341]
@curtiskphsc @boettcc Educator Preparation Institute application has PHCC on several pages 
https://educator-prep.phsc.edu/sites/default/files/documents/application-packet2018.pdf

<img width="624" alt="application-packet2018" src="https://user-images.githubusercontent.com/3138019/43797431-59ccfcee-9a55-11e8-922e-8a4a00911d53.png">

**Comment by C13L0** [comment]
From: Webmaster
Sent: Thursday, September 6, 2018 09:53 AM
To: PHSC Marketing and Communications Office
Cc: Melanie Waxler; Lucy Miller; Melissa Harts
Subject: Re: Educator Preparation Institute: Published - 2019 Application and Information Packet
 
Good morning,


This document still contains references to PHCC. All content should be reviewed and audited before being approved and published.

From: PHSC Webmaster
Sent: Thursday, September 6, 2018 08:45 AM
To: Webmaster
Subject: Educator Preparation Institute: Published - 2019 Application and Information Packet

Thursday - Sep 06, 2018 - 8:45 am

curtisk published 2019 Application and Information
Packet at https://educator-prep.phsc.edu/node/39.

Revision Log Message: Published


There is an open ticket on this since August 7, 2018 
https://github.com/phsc-edu/2018/issues/341




Thank you,

Cielo

**Comment by curtiskphsc** [comment]
@C13L0 This content was reviewed and the appropriate individuals were notified. I will gladly contact Dr. Burr again and thanks so much for bringing this to our attention.

**Comment by curtiskphsc** [comment]
Webmaster,
It appears that Sandra Anderson has publish privelages. She recently published updates to admissions.phsc.edu without content review. Please provide a current list of all users and their permission levels. If we have users publishing content without review it makes it fairly difficult to review all content.
Thank You,
Kevin Curtis
Web Content Manager
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
Phone: 727-816-3159
Building/Room: C205-B
________________________________

**Comment by boettcc** [comment]
I updated all the docs for Dr. Burr in early August. I sent her back both word files and I created pdf files for her.

**Comment by C13L0** [comment]
Verified this has been completed. Closing
