### ISSUE TITLE
eFaculty content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#343]
### Please check the following links for accessibility problems. ###

https://efaculty.phsc.edu/canvas/external-apps/zoom
![zoom _ efaculty support - google chrome 2018-08-08 11 58 45](https://user-images.githubusercontent.com/31025634/43852590-9a0c5348-9b0b-11e8-81f0-7fdf3065d226.png)

----------------
https://efaculty.phsc.edu/eteaching/community-practice/edutech-training-series
![edutech training series _ efaculty support - google chrome 2018-08-08 12 06 19](https://user-images.githubusercontent.com/31025634/43852636-bdf1ee62-9b0b-11e8-9bcf-9f5436c61f86.png)

-----------------

https://efaculty.phsc.edu/eteaching/faculty-procedures/end-term-procedures
![end of term procedures _ efaculty support - google chrome 2018-08-08 12 15 23](https://user-images.githubusercontent.com/31025634/43852700-e44252a0-9b0b-11e8-9ad6-0dda237dc131.png)
![end of term procedures _ efaculty support - google chrome 2018-08-08 12 16 55](https://user-images.githubusercontent.com/31025634/43852711-ea9b8cb6-9b0b-11e8-950e-62ce85fd282f.png)

---------------

https://efaculty.phsc.edu/eresources/elearning-centers
![elearning centers _ efaculty support - google chrome 2018-08-08 12 43 11](https://user-images.githubusercontent.com/31025634/43852785-2907dcde-9b0c-11e8-9456-68c361b7e398.png)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please correct the two accessibility issues as documented above.

**Comment by curtiskphsc** [comment]
@Computerrat @C13L0 Ready for review

**Comment by C13L0** [comment]
@Computerrat Please review changes for accessibility and close ticket once verified.

**Comment by Computerrat** [comment]
Verified changes
