### ISSUE TITLE
Equity services content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#344]
### Please check the following links for accessibility problems.

https://equity-services.phsc.edu/programs/linking-faith-and-education-life
![linking in faith and education life _ global and multicultural awareness - google chrome 2018-08-08 13 22 17](https://user-images.githubusercontent.com/31025634/43854042-c43b7d7a-9b0f-11e8-851d-8737adfbcc96.png)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please correct the two accessibility issues as documented above.

**Comment by curtiskphsc** [comment]
@C13L0 @Computerrat Ready for review

**Comment by C13L0** [comment]
@Computerrat Please review changes for accessibility and close ticket once verified.

**Comment by Computerrat** [comment]
Verified changes
