### ISSUE TITLE
eStudent Support

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#345]
### Please check the following links for accessibility problems.

https://online.phsc.edu/online-learning/support
![support _ estudent support - google chrome 2018-08-08 14 33 43](https://user-images.githubusercontent.com/31025634/43857043-2b8acab4-9b18-11e8-9772-4196d62bdbbb.png)

-------------------

https://online.phsc.edu/support
![support _ estudent support - google chrome 2018-08-08 14 36 59](https://user-images.githubusercontent.com/31025634/43857192-9616e3f4-9b18-11e8-8be6-97d88c126429.png)

---------------

https://online.phsc.edu/department-information
![department information _ estudent support - google chrome 2018-08-08 14 38 50](https://user-images.githubusercontent.com/31025634/43857284-df0acee0-9b18-11e8-9bf1-21163ef7fb61.png)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please correct the two accessibility issues as documented above.

**Comment by curtiskphsc** [comment]
@C13L0 @Computerrat ready for review

**Comment by C13L0** [comment]
@Computerrat Please review changes for accessibility and close ticket once verified.

**Comment by Computerrat** [comment]
Verified changes
