### ISSUE TITLE
Request to add another Contact

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#350]
The office of Global & Multicultural Awareness has now two Pre-Collegiate Program Coordinators that can be contacted for the Out-Reach Students Events. However, the system for events only can hold  the information for one contact. Is there a way that you can add one more contact?  Please let us know.

Blessings!   

Concepcion M. Tijerino
Office Assistant 

Global & Multicultural Awareness

Pasco-Hernando State College 

Phone: 727-816-3193

Fax: 727-816-3199

**Comment by jeppy64** [comment]
@C13L0 

All sites with configuration updates and data migration.

Time to complete: 8.5 hours - ready for review

**Comment by C13L0** [comment]
@jeppy64 Approved for invoicing
