### ISSUE TITLE
HR job contacts

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#351]
Pat has requested to have the ability to add contacts in the sidebar instead of in the body field. This way, she can re-use contacts over and over.

This would be identical to contact added to career paths, with the ability to add more than one contact to a job.

**Comment by C13L0** [comment]
No problem, I will close the ticket. =)



From: Patricia McGee
Sent: Thursday, September 6, 2018 09:52 AM
To: Webmaster
Cc: Vivian Friend; David Velazquez
Subject: Re: HR job contacts | 351 | Open
 
Cielo,


I am still not sure why I would request this. We do not put employees' name, location, etc. on our postings. We only include location with address. If it's an adjunct position, we put the Dean's title, location and fax number. Please provide additional clarification. 


Thanks!

Pat

**Comment by Computerrat** [comment]
Hi Cielo,

Please see the requested information attached. Please let me know, if I am missing anything.

Have a great day!
Pat

**Comment by Computerrat** [comment]
North Campus in Brooksville

Associate Dean of Academic Affairs &

Retention Services, North Campus

Pasco-Hernando State College

11415 Ponce de Leon Blvd.

Brooksville, FL 34601

Phone: 352-797-5004

Fax: 352-797-5133

Spring Hill Campus

Associate Dean of Academic Affairs &

Retention Service, Spring Hill Campus

Pasco-Hernando State College

450 Beverly Court

Spring Hill, FL 34606

Phone: 352-340-4805

Fax: 352-340-4967

Porter Campus at Wiregrass Ranch in Wesley Chapel

Associate Dean of Academic Affairs &

Retention Services, Porter Campus at Wiregrass Ranch

Pasco-Hernando State College

2727 Mansfield Blvd.

Wesley Chapel, FL 33543

Phone: 813-527-6629

Fax: 813-527-6912

West Campus in New Port Richey

Dean of Arts & Sciences

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

Phone: 727-816-3322

Fax: 727-816-3321

East Campus in Dade City

Associate Dean of Academic Affairs &

Retention Service, East Campus

Pasco-Hernando State College

36727 Blanton Road

Dade City, FL 33523

Phone: 352-518-1315

Fax: 352-518-1225

Dean of Workforce Development and

Career & Technical Education

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

Phone: 727-816-3263

Fax: 727-816-3301

Associate Dean of Nursing Programs

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

Phone: 727-816-3136

Fax: 727-816-3309

**Comment by C13L0** [comment]
Pat has provided the required information. Assigning to @jeppy64

**Comment by jeppy64** [comment]
@C13L0 

Added new job contact bundle with specified fields, new mgmt. and block display. And added content from above.

Time to complete: 2 hours. Ready for review.

**Comment by C13L0** [comment]
@jeppy64 This is approved for invoicing
