### ISSUE TITLE
(August) Ticket Submissions

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#355]
@jeppy64 

Can you please take a look at this? =)

-------------

Good morning,

I would like to submit tickets for the following:

<strike>I would like to have the following personnel removed from the Advising Subdomain Department Information Page (https://advising.phsc.edu/department-information) since they are not in Advising:
Amy McCain
Pangri Mehta
Rakesh Shah</strike>

I cannot update the business hours on the Advising Subdomain Department Information Page (https://advising.phsc.edu/department-information).  See screen shot below:

I am not able to select any of the choices.

![pastedimage](https://user-images.githubusercontent.com/3138019/44032412-0814a774-9ed5-11e8-8ae9-bd202b783f5d.png)

Thank you,

Melissa

**Comment by C13L0** [comment]
Assigning to myself

----------

I would like to have the following personnel removed from the Advising Subdomain Department Information Page (https://advising.phsc.edu/department-information) since they are not in Advising:
Amy McCain
Pangri Mehta
Rakesh Shah

**Comment by jeppy64** [comment]
Restored Day of Week taxonomy and terms. Verified entity reference on Department Hours bundle to term reference. 

time to complete: 1 hour

**Comment by C13L0** [comment]
Completed. @jeppy64 please invoice then close this ticket

**Comment by jeppy64** [comment]
@C13L0 
should go under maintenance I believe. feel free to close if agreed

**Comment by C13L0** [comment]
@jeppy64 Agreed. Updated title and label to reflect change
