### ISSUE TITLE
2018 Roster and Schedule Links

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#356]
From: Steve Winterling
Sent: Monday, August 13, 2018 08:29 AM
To: Webmaster; jeppy64@gmail.com
Subject: 2018 Roster and Schedule Links
 
Good morning!

I see cross country has the 2018 roster and schedule links on the web page.  We need the links for the other sports.  The volleyball roster and schedule are ready to go.  They play their first scrimmage on Wednesday.  Please keep me posted.

We can also remove the Cheerleading from the athletic pages.  We won't be having them this year.

Steve Winterling

Athletic Director

**Comment by C13L0** [comment]
@jeppy64 Can this be closed? I would prefer to just keep #259 open.

**Comment by jeppy64** [comment]
@C13L0 

closing as complete
