### ISSUE TITLE
Foundation events map and moderation 

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#357]
@jeppy64 

- [ ] Department editor is able to publish events

stallej published PHSC Performing Arts Series: Rocketman-Tribute to Elton John at https://foundation.phsc.edu/node/244.

- [ ] Event map is displaying twice on events

![double-map](https://user-images.githubusercontent.com/3138019/44043835-cf48a3e2-9ef1-11e8-93a8-339636454eeb.png)

**Comment by C13L0** [comment]
@jeppy64 Can this be closed?

**Comment by jeppy64** [comment]
@C13L0 
closing as complete
