### ISSUE TITLE
Athletic Competitions - Edits

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#358]
Good afternoon!

I'm trying to change the St. Leo Basketball game date.

It should show as "Scrimmage", but it shows as an exhibition?  Not sure what that is.

New date and time is 

Nov. 3rd at 7:30pm at St. Leo Univ.  Scrimmage.   

Let me know your thoughts

https://athletics.phsc.edu/node/747/edit?destination=/admin/manage/athletic-competitions%3Ffield_acom_semester_season_ref_target_id%3D13%26field_acom_sport_ref_target_id%3D8

Thanks. 

Micheal L. Jones Sr.  SSC., MA., MS., D.D.   

Co-Curricular Specialist: Psychology Instructor

Head Men's Basketball Coach: FCSAA Region 8/NJCAA Div. II

Club Advisor: MOE & FCA West Campus

Pasco Hernando State College: West Campus

10230 Ridge Rd. New Port Richey, FL. 34654

Email: jonesm@phsc.edu

Phone: 727-816-3340

Fax: 727-816-3354

**Comment by C13L0** [comment]
@jeppy64 Can this be closed?

**Comment by jeppy64** [comment]
@C13L0 
closing as complete
