### ISSUE TITLE
Financial Aid content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#360]
### Please check the following links for accessibility problems.

https://financial-aid.phsc.edu/help/faq/dynamic-forms/i-see-dynamic-forms-link-my-wise-account-cant-access-online-form
![i see the dynamic forms link on my wise account but can t access the online form_ _ financial aid - google chrome 2018-08-08 15 53 21](https://user-images.githubusercontent.com/31025634/44050200-4c35b158-9f04-11e8-9030-9e65d61875bc.png)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please correct the accessibility issues as documented above.

**Comment by C13L0** [comment]
@Computerrat Please review changes for accessibility and close ticket once verified.

**Comment by Computerrat** [comment]
Verified changes
