### ISSUE TITLE
(August) Department Hours-Day of Week Not Listed

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#367]
Attempted to update for Fall Friday hours https://phsc.edu/admin/manage/campus-directory-listings and it looks like it is listing all content as "day of week" selections rather than actual days of week.
![day-of-week-designation](https://user-images.githubusercontent.com/28155245/44268961-18d3c980-a201-11e8-854f-52934c64ca3f.PNG)

**Comment by C13L0** [comment]
@jeppy64 Same issue as Advising. Can you please take a look?

**Comment by jeppy64** [comment]
@C13L0  @curtiskphsc 
all sites have been checked for the regression. replaced Day of Week vocabulary and terms on 9 sites. data entry/edit ready

time to complete: 1 hour

**Comment by C13L0** [comment]
@curtiskphsc This has been completed
