### ISSUE TITLE
Event Session Unpublished

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#368]
Attempting to add sessions to event. Used the "update session" button and received "This entity cannot be referenced" and I assume this happens because the node is unpublished? Is there supposed to be a publish button?
![session-unpublished](https://user-images.githubusercontent.com/28155245/44277579-29903980-a219-11e8-9243-84363eff4f8e.PNG)
![no-publish-button](https://user-images.githubusercontent.com/28155245/44277591-32810b00-a219-11e8-9688-a606ecd0a32c.PNG)

https://student-life.phsc.edu/node/1617

**Comment by C13L0** [comment]
@jeppy64 Can you please take a look at this?

**Comment by jeppy64** [comment]
@curtiskphsc  @C13L0 

please try it again. There's a bug in the core workflow module that sets previously non-moderated node types to not be published by default node add. This looks like it's a repeat of that. I went in and forced Sessions to publish on creation and verified that it did stick. Bottom line is when that flag is set to off it makes a double moderation and the child node is unpublished hence not being able to reference it.

**Comment by C13L0** [comment]
@jeppy64 Thank you!!

**Comment by curtiskphsc** [comment]
@jeppy64 @C13L0 Perfection! Thanks :)
