### ISSUE TITLE
Intranet - Academic Calendar

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#370]
Dear Cielo,

Please update the link for Academic Calendar on the website to the 2018-19 catalog:

http://phsc.smartcatalogiq.com/en/2018-2019/Catalog-and-Student-Handbook/College-Calendar/Fall-2018

**Comment by C13L0** [comment]
@Computerrat Please use this link instead of the one provided.

http://phsc.smartcatalogiq.com/en/current/Catalog-and-Student-Handbook

**Comment by Computerrat** [comment]
Completed
