### ISSUE TITLE
Missing event contact information 

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#373]
@curtiskphsc 

Event deadlines are missing contact phone and email. 
Filter by Deadline
https://phsc.edu/about-phsc/events

<img width="658" alt="event-contact" src="https://user-images.githubusercontent.com/3138019/44410189-e6dca300-a531-11e8-9a6f-5b072a010276.png">

**Comment by curtiskphsc** [comment]
This has been brought to the attention of Dean Henderson as they do not have one individual to route the calls and emails to. Melissa Rushton is also aware and they are working on a solution.

**Comment by curtiskphsc** [comment]
@C13L0 For this type of a deadline, Melissa Rushton stated they would **NOT** want to use the Information Center as the point of contact. As stated, she was working with Dean Henderson to come up with a solution. That is the update I have and it will not change until Dean Henderson or the new Information Center Coordinator decide to take action or provide us with guidance.

**Comment by C13L0** [comment]
@curtiskphsc Please add the Information Center information to events missing a phone and email.

----------

From: Chiquita Henderson
Sent: Wednesday, September 19, 2018 6:26:53 PM
To: Cielo Johnson
Subject: Re: Contact information for student drop/add/withdrawal deadlines
 
Hello Cielo,

I would recommend the Information Center.  My initial thought was to list all five campuses Student Affairs offices but wasn't sure if that was an option.  The Information Center Representative can always direct the student to Student Affairs if they don't know the answer (but they know everything, right).  Let me know if this helps. 

Regards,

Chiquita 

Chiquita Henderson, MPA. MS

Dean of Student Affairs & Enrollment Management 

Title IX Coordinator

**Comment by curtiskphsc** [comment]
@C13L0 The Information Center has been notified. When they report the edits have been made I will provide further comment.

**Comment by curtiskphsc** [comment]
@C13L0 "Good afternoon Kevin,

I have updated all of the deadline events to include a contact number and email. I agree with Dean Henderson that the Information Center would be the most appropriate contact for deadlines, as we can answer general questions and, if necessary, refer them to Student Affairs on their respective campus.

Thank you!

Melissa

 
~~~~~~~~~~~~~~~~~~~~~~~~~
Pasco-Hernando State College
Information Center 
1-855-NOW-PHSC
1-855-669-7472"

**Comment by C13L0** [comment]
Completed
