### ISSUE TITLE
Subdomain current user database–Please update

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#377]
Please update the current user database document. It appears Deann Newton has publishing permissions as content is being pushed to the front page of Athletics.phsc.edu without review and it does not meet our publishing standards nor comply with our style guide. Additionally, some domains have no department admin or editors listed.
https://docs.google.com/spreadsheets/d/1qZ66YW5fkdQ7L6ovBB-570UbNz3aRSjDhYUxh-t4cHw/edit#gid=613628905

**Comment by C13L0** [comment]
No

**Comment by C13L0** [comment]
This is not a user database document. The referenced document was used to during the development phase in 2017 for access to the dev sites. There is nothing to update.

**Comment by curtiskphsc** [comment]
@C13L0 Where can I access the current user database? I need to know who to contact for content updates.

**Comment by C13L0** [comment]
@curtiskphsc Every user listed on the Department Information page is a content editor

**Comment by curtiskphsc** [comment]
@C13L0 First, that is not useful information as it does not tell me when they last logged in or what permission level they have. As **Web Content Manager**, I need to know what permission levels the **content** creators have in order to do my job effectively. As you can clearly see, I do have permission to use/view the "People" module on info.phsc.edu and I had access to it on the main phsc.edu site prior to the migration to Drupal 8. Critical information is easily accessible to me in one place such as last date of access and their role (permissions.) Incidentally, the second person on this list, Gary Leonard, was terminated several months ago and should not be on the list at all, let alone be listed as "active."
![people-module](https://user-images.githubusercontent.com/28155245/44526126-01895600-a6b1-11e8-95ba-afeab62ae08d.JPG)

**Comment by C13L0** [comment]
@curtiskphsc **All** content editors have the ability to edit and save to draft or needs review.

**Comment by C13L0** [comment]
@curtiskphsc You are correct. While we were working on updates to Athletics, content was approved for testing purposes. In the future, we will clearly comment that the content was published for testing. As Marketing Admin, you can always edit/delete the content or contact Steve Winterling.
