### ISSUE TITLE
Bad Links in Search

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#379]
@curtiskphsc Do you want all FAQ's deleted from info.phsc.edu?

From: Rick Casey
Sent: Thursday, August 16, 2018 01:59 PM
To: Webmaster
Subject: Bad Links in Search
 
Hello Cielo,

Chiquita asked me to have links removed from our website search that point to our old website.  For instance, when you search for "PERT Exemption," the following bad links are listed.

https://info.phsc.edu/faq/career-and-testing-services/who-must-take-pert (This links is a top hit for the search for "PERT" as well.)

https://info.phsc.edu/faq/87924?_ga=2.51994793.1465533516.1534165446-1885840786.1518207937

https://info.phsc.edu/faq/career-and-testing-services/what-pert?_ga=2.51994793.1465533516.1534165446-1885840786.1518207937

https://info.phsc.edu/faq?_ga=2.214010647.1465533516.1534165446-1885840786.1518207937

Is there a way to disable these pages or links from the search?

Regards,

Rick

Rick Casey

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

The FAQs can either be updated or deleted. You have permissions on the site to do both.

**Comment by curtiskphsc** [comment]
@C13L0 No

**Comment by C13L0** [comment]
@curtiskphsc @boettcc This is giving us bad SEO due to bad links. Please update or delete old FAQs

**Comment by C13L0** [comment]
Simple Google Custom Search Engine \| Drupal.orgwww.drupal.orgProject information. Module categories: Search 8 sites report using this module 197 downloads; This project is not covered by the security advisory policy. Use at your own risk! ...
--

**Comment by C13L0** [comment]
@curtiskphsc As **Web Content Manager**, you have full permissions to update or delete this content.

> Unfortunately do not have an accurate account of who exactly has content edit and creation rights on our subdomains and therefore do not know who to contact to affect the content migration. I have requested the user database document be updated but that request was denied and the ticket closed. You can view it here https://github.com/phsc-edu/2018/issues/377

**Comment by curtiskphsc** [comment]
@C13L0 This is about a long-term solution to this obvious issue. The content owners are responsible for making sure said content is accurate. I do not know who who owns/edits/creates content on our multitude of web properties. This is **critical** information and as **Webmaster** you control that. On some web properties I do have access to this critical information. Unfortunately, on the subdomains rolled out last November, and the marketing site, I do not have the proper permissions to view this information. I would appreciate access to the proper module(s) so I can view it myself as well as access tot he data logging module so I can research issues related to content. Continually stonewalling these requests makes it near impossible to do my job effectively.

**Comment by curtiskphsc** [comment]
@C13L0 Also, it would be very helpful for the folks involved in this conversation who are not familiar with SEO best practices to know exactly why this is adversely affecting our SEO. As you stated this is causing a problem for our SEO, could you please take the time to thoroughly explain this for the benefit of those not well-versed in such things? And for the record, I am attaching a screen shot from info.phsc.edu that clearly shows I do have access to the "people" module on that web property, as well as a second screen shot showing that I am being denied access to said module on phsc.edu. This is consistent across all phsc.edu subdomains. Again, without knowing who has access and what permission level they have, doing my job effectively becomes difficult at best and asking for access to something that I once had on the main site, and currently have on other web properties, does not seem to be an unreasonable request.
Please note that Gary Leonard (2nd from the top-leonarg) was terminated earlier this year and should not be on this list.
![people-module](https://user-images.githubusercontent.com/28155245/44526915-5a59ee00-a6b3-11e8-889e-fdce56d99279.JPG)
![access-denied-people-mod](https://user-images.githubusercontent.com/28155245/44527096-e9670600-a6b3-11e8-8981-6af82ce90d3b.PNG)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

Kevin,

Thank you for pointing out the security issues on the info.phsc.edu site. I will make sure and correct those asap.

Please remember, you have always had Marketing Administration access, which has permission to edit, delete, and publish content. This is all that's needed to not only manage web content but to update the links on the FAQs. Again, please update the links as soon as possible.

**Comment by curtiskphsc** [comment]
@C13L0 I will definitely send an email to the content owner and ask that they log in and fix these issues. The content owners are responsible per IMM 1-24 and as such they need to be updating links and content regularly, or we simply block Google from crawling that directory. We need to have a strategy in place to migrate said content and in the mean time stop it from popping up in search results. Furthermore, the info.phsc.edu site in no way resembles our current site. The logo is incorrect, the colors are incorrect, etc. We really don't want people visiting it if it does not accurately reflect our brand.

**Comment by curtiskphsc** [comment]
@C13L0 The record of this FAQ https://info.phsc.edu/faq/career-and-testing-services/who-must-take-pert shows that your former intern Kyle is the author and you were the last to revise it. Please update the link(s) per IMM 1-24 as your department created the FAQ and you were the last to revise it. Also, IMM 1-24 says "A. Oversight
All official PHSC websites, including www.PHSC.edu and all other sites hosted
under the PHSC domain name, its contents and links, are the responsibility of the
Institutional Technology department and the Webmaster, working with the
assistance and guidance of the Marketing and Public Relations department"
![faq-screen-shot-1](https://user-images.githubusercontent.com/28155245/44529330-d35c4400-a6b9-11e8-9278-65b6455a3425.PNG)

**Comment by curtiskphsc** [comment]
@C13L0 I want to also bring attention back to the original request from Rick Casey which I went in to great detail answering for him via email. My response was in fact completely relevant to the "bad links" as his request was to stop the **pages** from showing up in our **search** He never requested the links on those pages be updated, he wants them blocked.

"Hello Cielo,
Chiquita asked me to **have links removed from our website search** that point to our old website.  For instance, when you search for "PERT Exemption," the following bad links are listed.
https://info.phsc.edu/faq/career-and-testing-services/who-must-take-pert (This links is a top hit for the search for "PERT" as well.)
https://info.phsc.edu/faq/87924?_ga=2.51994793.1465533516.1534165446-1885840786.1518207937
https://info.phsc.edu/faq/career-and-testing-services/what-pert?_ga=2.51994793.1465533516.1534165446-1885840786.1518207937
https://info.phsc.edu/faq?_ga=2.214010647.1465533516.1534165446-1885840786.1518207937

**Is there a way to disable these pages or links from the search?**

Regards,

Rick

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

Deleting them, will remove them from google search. =)

**Comment by curtiskphsc** [comment]
@C13L0 Deleting them also means they are gone forever unless you have a copy of the originally submitted documents? This content is critical for our students and as stated should be migrated to the new subdomains. That said, Courtney Boettcher has volunteered to create an archive Word document for the Career and Testing FAQs. Once that document is complete, the Career and Testing FAQs **only** may be deleted.

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

Kevin, you have full permissions to delete any FAQ when you are ready.

**Comment by curtiskphsc** [comment]
@C13L0 @boettcc Marketing did not want them deleted and only wanted them to be removed from our search results as Rick Casey requested. As Courtney and I have volunteered to archive all of the FAQs so they do not disappear, your assistance with deleting them would be greatly appreciated. After all, IT is responsible for all web property content and links as stated in the IMM and is to work with the assistance and guidance of marketing. Delete Admissions FAQs and Career and Testing FAQs at your will. We plan to finish the remainder tomorrow.

**Comment by C13L0** [comment]
@curtiskphsc  @boettcc  As requested, all Admissions and Career and Testing FAQs have been deleted. It will take some time for google to reindex and remove them from search.
> Delete Admissions FAQs and Career and Testing FAQs

**Comment by curtiskphsc** [comment]
@C13L0 All FAQs on info.phsc.edu have been archived. Feel free to do whatever you deem necessary to keep them from popping up in Google Search. 
@boettcc Thanks for your assistance with saving this content.

**Comment by C13L0** [comment]
From: Information Center
Sent: Monday, August 27, 2018 12:42 PM
To: Webmaster
Subject: Re: Please update outgoing email message
 
Done!  Thank you for letting us know!


~~~~~~~~~~~~~~~~~~~~~~~~~
Pasco-Hernando State College
Information Center 
1-855-NOW-PHSC
1-855-669-7472



From: Webmaster
Sent: Monday, August 27, 2018 12:40 PM
To: Information Center
Subject: Please update outgoing email message
 
Good afternoon,


Marketing has requested that all FAQs be removed from https://info.phsc.edu/faq. I would appreciate if the following sentence can be removed from the Information Center outgoing email message.


In addition, you may view our comprehensive list of Frequently Asked Questions online: https://info.phsc.edu/faq



Thank you very much!
Cielo

**Comment by C13L0** [comment]
All FAQs have been deleted
