### ISSUE TITLE
Student Accessibility Services

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#383]
The contact list title is incorrect https://accessibility-services.phsc.edu/department-information and I don't seem to have access to change it. Needs to read "Student Accessibility Services"
![accessibility-department-page](https://user-images.githubusercontent.com/28155245/44421669-3d0c0f00-a54f-11e8-825d-59f5fd33bac4.PNG)

**Comment by C13L0** [comment]
@curtiskphsc completed
