### ISSUE TITLE
Information Center Coordinator (Job # 0780) - INTERNAL

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#385]
From: Patricia McGee
Sent: Tuesday, August 21, 2018 03:52 PM
To: Webmaster; Kevin Curtis
Cc: Linda Santella
Subject: Information Center Coordinator (Job # 0780) - INTERNAL
 
Cielo,

Please post this position announcement under “Internal Vacancies” on our Access (intranet) home page, and provide a link to the online application for this internal position.

Thanks…Pat

Job #: 0780
Position: Information Center Coordinator (Internal Vacancy)
Location: New Port Richey 
Application deadline: August 29, 2018

JOB DESCRIPTION: YES
SUMMARY OF BENEFITS: YES

**Comment by C13L0** [comment]
@Computerrat completed this ticket

**Comment by C13L0** [comment]
From: Patricia McGee
Sent: Wednesday, August 22, 2018 08:42 AM
To: Webmaster; Kevin Curtis
Cc: Linda Santella
Subject: Re: Information Center Coordinator (Job # 0780) - INTERNAL | 385 | For review
 
Good morning!


Can you change the job description to this attached version. I needed to make a correction.


Thanks a Million!

Pat

**Comment by C13L0** [comment]
completed

**Comment by Computerrat** [comment]
Hi Cielo & Kevin,

The title is incorrect on the Intranet for this position. I don't know if this was missed during my review. Please correct asap. 

Incorrect title posted Advisor 

Correct title should read Information Center Coordinator

Thanks a Million!
Pat

**Comment by C13L0** [comment]
Completed
