### ISSUE TITLE
Policies Website Editor Questions

### ISSUE THREAD

**Issue by 10yson** [phsc-edu/2018#389]
Cielo, regarding the Policies subdomain, please contact me to review some questions I have related to: 

1. guidance for displaying the DBOT meeting schedule
2. verification of my Dashboard menu options

**Comment by C13L0** [comment]
@10yson You should now be able to view the Content in Moderation link. I did see an event sitting in draft. =)

**Comment by 10yson** [comment]
@C13L0 I now see the Moderation link.  Thank you.

Couple follow-up items:
1. Looks like I only have Read permissions within this moderation section.  Does that sound correct?  When I click the link, "Revisions list for this node", on the one item in Draft, I get "You are not authorized to access this page." message.

2. On the home screen of the Policies site (https://policies.phsc.edu/), the "View all Events" link gets a "Page not found"

**Comment by 10yson** [comment]
@C13L0 I verified the "View all Events" link works as expected.  Much appreciated.
