### ISSUE TITLE
Financial Services content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#391]
## **Please check the following links for accessibility problems.**

----------

https://financial-services.phsc.edu/purchasing/purchase-order-terms-and-conditions
![purchase order terms and conditions _ financial services - google chrome 2018-08-23 10 30 34](https://user-images.githubusercontent.com/31025634/44536497-a2383f80-a6ca-11e8-9d19-a6d06c97e849.png)

![purchase order terms and conditions _ financial services - google chrome 2018-08-23 10 36 21](https://user-images.githubusercontent.com/31025634/44536522-ae240180-a6ca-11e8-9ff1-d74553bec899.png)

![purchase order terms and conditions _ financial services - google chrome 2018-08-23 10 36 56](https://user-images.githubusercontent.com/31025634/44536541-bb40f080-a6ca-11e8-954d-2b5b276c3714.png)

![purchase order terms and conditions _ financial services - google chrome 2018-08-23 10 38 04](https://user-images.githubusercontent.com/31025634/44536562-c85ddf80-a6ca-11e8-94b9-e6230581e374.png)

------------

https://financial-services.phsc.edu/student-financial-services/delinquent-accounts-collections

![delinquent accounts collections _ financial services - google chrome 2018-08-23 10 47 20](https://user-images.githubusercontent.com/31025634/44536658-f4796080-a6ca-11e8-995c-60e5fe360f72.png)

---------------

https://financial-services.phsc.edu/student-financial-services/florida-prepaid

![florida prepaid _ financial services - google chrome 2018-08-23 10 50 38](https://user-images.githubusercontent.com/31025634/44536728-1ffc4b00-a6cb-11e8-8f94-88e131ebfc70.png)

![florida prepaid _ financial services - google chrome 2018-08-23 10 52 13](https://user-images.githubusercontent.com/31025634/44536754-27bbef80-a6cb-11e8-96b9-936436da7e74.png)

--------------

https://financial-services.phsc.edu/student-financial-services/tax-information

![tax information _ financial services - google chrome 2018-08-23 10 55 52](https://user-images.githubusercontent.com/31025634/44536974-a44ece00-a6cb-11e8-8135-b6a38418f950.png)

--------------

https://financial-services.phsc.edu/student-financial-services/third-party-billing

![third party billing _ financial services - google chrome 2018-08-23 10 56 36](https://user-images.githubusercontent.com/31025634/44537041-d3fdd600-a6cb-11e8-8c42-caa67e6c6c12.png)

-----------------

https://financial-services.phsc.edu/department-information

![department information _ financial services - google chrome 2018-08-23 11 07 30](https://user-images.githubusercontent.com/31025634/44537400-b715d280-a6cc-11e8-9add-a7731213273f.png)

---------------

https://financial-services.phsc.edu/student-financial-services/tuition-installment-plan

![tuition installment plan _ financial services - google chrome 2018-08-23 11 02 14](https://user-images.githubusercontent.com/31025634/44537574-2e4b6680-a6cd-11e8-8293-ce453ce516f4.png)

![tuition installment plan _ financial services - google chrome 2018-08-23 11 01 17](https://user-images.githubusercontent.com/31025634/44537998-23dd9c80-a6ce-11e8-9203-6bb683069d06.png)

-----------------

https://financial-services.phsc.edu/help/faq/student-financial-services/tuition-installment-plan-adjustments

![tuition installment plan adjustments _ financial services - google chrome 2018-08-23 11 42 07](https://user-images.githubusercontent.com/31025634/44537451-d9a7eb80-a6cc-11e8-970f-9c781b5b3572.png)

-------------

https://financial-services.phsc.edu/help/faq/student-financial-services/understanding-1098t-form
![understanding the 1098t form _ financial services - google chrome 2018-08-23 11 43 49](https://user-images.githubusercontent.com/31025634/44538109-7028dc80-a6ce-11e8-9684-4df31ad4261f.png)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please correct the accessibility issues as documented above.

**Comment by curtiskphsc** [comment]
@Computerrat @C13L0 Ready for review

**Comment by C13L0** [comment]
@Computerrat Please review changes for accessibility and close ticket once verified.

**Comment by Computerrat** [comment]
Verified changes
