### ISSUE TITLE
Foundation content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#392]
## **Please check the following link for accessibility problems.** ##

---------------------------------------------

https://foundation.phsc.edu/about
Embedded video has closed captioning option, but no transcript

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please work with the Foundation to add a transcript to make this video accessible.

**Comment by curtiskphsc** [comment]
@C13L0 Video removed. Foundation will need to provide the transcript.

**Comment by C13L0** [comment]
Video has been removed. Closing
