### ISSUE TITLE
Legal Department(Policies and Governance) content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#393]
## **Please check the following link for accessibility problems.** ##

--------
https://policies.phsc.edu/accreditation

![accreditation _ policies and governance - google chrome 2018-08-23 13 31 49](https://user-images.githubusercontent.com/31025634/44543617-09abba80-a6de-11e8-927e-0fd9b8d568f3.png)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please correct the accessibility issues as documented above.

**Comment by curtiskphsc** [comment]
@C13L0 Ready for review.

**Comment by C13L0** [comment]
@Computerrat Please review changes for accessibility and close ticket once verified.

**Comment by Computerrat** [comment]
Verified changes
