### ISSUE TITLE
Student Accessibility content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#394]
## **Please check the following link for accessibility problems.** ##

----------

https://accessibility-services.phsc.edu/help/step-step-instructions/student-accessibility-services-where-to-begin

![student accessibility services-where to begin _ student accessibility services - google chrome 2018-08-23 15 58 30](https://user-images.githubusercontent.com/31025634/44549076-f7d21380-a6ed-11e8-8edf-57b57ded0d25.png)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please correct the accessibility issues as documented above.

**Comment by curtiskphsc** [comment]
@C13L0 Ready for review.

**Comment by C13L0** [comment]
@Computerrat Please review changes and close ticket once verified.

**Comment by Computerrat** [comment]
verified changes
