### ISSUE TITLE
Financial Aid: Published - I see the Dynamic Forms link on my WISE account but can't access the online form?

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#398]
Hi Kevin;

I am having trouble removing a form from our financial aid page https://financial-aid.phsc.edu/forms-and-downloads. Is there any way you can help me have this form removed from the page? 

Here is the form URL https://financial-aid.phsc.edu/sites/default/files/documents/2017-2018-appeal-request.pdf

Thanks for any help you can give! 😊

Sincerely,

Kim Williams
Associate Director-Financial Aid
Pasco-Hernando State College 
10230 Ridge Road
New Port Richey, FL  34654
727.816.3195
 
@curtiskphsc

**Comment by curtiskphsc** [comment]
@Computerrat This document was authored by webintern and thus Kim cannot delete it. Please delete _only_ the document referenced in her email. I will communicate with her regarding the others that were authored by webintern and see what she wants to do with those.
![fin-aid-forms-delete](https://user-images.githubusercontent.com/28155245/44727448-0e8ab880-aaa8-11e8-8543-c659a262f424.PNG)

**Comment by C13L0** [comment]
@curtiskphsc 

Permissions have been corrected. Department editor can delete any document. 

The web-intern role does not have permissions to edit content on the production site. This was done on the development site when originally migrating content over from the old website.

**Comment by C13L0** [comment]
@curtiskphsc This is a follow to find out where you are with this ticket.

**Comment by curtiskphsc** [comment]
The requester did not respond. Close this ticket.

**Comment by C13L0** [comment]
Completed
