### ISSUE TITLE
Website Correction

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#401]
Hi Cielo,

I noticed on the pages https://phsc.edu/about-phsc/campuses  and https://m.phsc.edu/default/map/map?feed=north&id=&_ga=2.194955822.2082616142.1535380802-564569275.1511202628

B Building was dedicated in 2016 at Drs. Richard C. and Beatrice S. Braun Classroom Building.

They are donors and should have the recognition. I've attached a copy of the building for verification. Thank you. 
![image](https://user-images.githubusercontent.com/31025634/44731328-f53a3a00-aab0-11e8-8649-3f981311c26a.png)

Jessica Staller
Coordinator of Foundation Events & Marketing

District Office
10230 Ridge Road, New Port Richey, FL 34654

727-816-3110   Fax: 727-816-3450

stallej@phsc.edu

@curtiskphsc

**Comment by curtiskphsc** [comment]
@Computerrat I made the change on the page. The content in the Google maps is generated by Google directly and we have no way of physically going in and adding the building designation. That said, anyone that uses Google Locate can visit the building and tell Google what the building is called and Google will eventually add it to the map. I would suggest the someone from the Foundation do that the next time they visit that location.
