### ISSUE TITLE
Safety and Security content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#406]
## **Please check the following link for accessibility problems.** ##
----------

https://safety.phsc.edu/procedures/reporting-child-abuse
![reporting child abuse _ safety and security - google chrome 2018-08-28 15 12 51](https://user-images.githubusercontent.com/31025634/44745755-a30c0f80-aad6-11e8-9ab1-9b37b79c66f9.png)

-------------

Not related to accessibility, but in the reporting child abuse section, Porter Campus is not listed.

![reporting child abuse _ safety and security - google chrome 2018-08-28 15 27 13](https://user-images.githubusercontent.com/31025634/44745876-ea929b80-aad6-11e8-94c6-47bec415d44f.png)

**Comment by C13L0** [comment]
@curtiskphsc Please correct the above accessibility issues.

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Kevin, this is a follow up to find out where you are with this ticket.

**Comment by curtiskphsc** [comment]
@C13L0 updated the page and sent a communication to David letting him know.

**Comment by C13L0** [comment]
@curtiskphsc 

> As per my previous reminders, I would like to remind you to follow the same ticket procedures as you have the past few years.  Once a ticket has been completed it needs to be assigned to me (@C13L0) for review. Not following procedure prevents the ticket from going through review and being properly closed. This also holds up the reply process to the person that initiated the ticket.

**Comment by curtiskphsc** [comment]
@C13L0 I thought you told me **not** to reassign tickets? I will gladly reassign tickets going forward.
