### ISSUE TITLE
Student Life content accessibility audit

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#407]
## **Please check the following links for accessibility problems.** ##
----------
https://student-life.phsc.edu/programs/awards

![awards _ student life - google chrome 2018-08-28 15 43 17](https://user-images.githubusercontent.com/31025634/44747837-2aa84d00-aadc-11e8-8a09-df3c3202805d.png)

-----------

https://student-life.phsc.edu/programs/peer-mentor

![peer mentor _ student life - google chrome 2018-08-28 15 47 05](https://user-images.githubusercontent.com/31025634/44747873-4e6b9300-aadc-11e8-8a9f-f4de1ddf9ebe.png)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc Please correct the above accessibility issues.

**Comment by curtiskphsc** [comment]
@C13L0 completed

**Comment by C13L0** [comment]
@curtiskphsc This headings on this page are still not compliant.

Using Headings Correctly
https://webaim.org/techniques/semanticstructure/
> Do not use text formatting, such as font size or bold to give the visual appearance of headings - 
> use actual heading (h1 - h6) for all content headings. Assistive technologies and other 
> browsers rely upon the literal markup of the page to determine structure. Items that are bolded or display in a bigger font are not interpreted to be structural elements.

**Comment by C13L0** [comment]
Completed
