### ISSUE TITLE
Staff access review

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#433]
Cielo,

Here is the changes that need to be made for access to the course schedule admin reports:

Remove:

- [x] Patricia Campbell
- [x] Jason Wetherington
- [x] Connie Frankel
- [x] Karen Davis
- [x] Patricia Rocco
- [x] Faustine Judd
- [x] Cathy Honaker
- [x] Pamela Medley
- [x] Jennifer Veloff
- [x] Lisa Richardson

Add:

- [x] Gerene Thompson
- [x] Joe McIntosh
- [x] Christine Smith
- [x] Dennis Feltwell
- [x] Michelle Godwin
- [x] Marcia Austin
- [x] Alysen Heil
- [x] Luther Buie
- [x] Laura Santomenno

Thank you and let me know if you need any additional information.

Kind regards,
Sonia

 
Sonia R. Thorn
Dean of Academic Affairs & Institutional Accreditation

**Comment by C13L0** [comment]
Completed
