### ISSUE TITLE
Porter Campus Link Broken

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#436]
https://phsc.edu/about-phsc/campuses

![campuses _ pasco-hernando state college - google chrome 2018-09-04 15 58 12](https://user-images.githubusercontent.com/31025634/45055163-08bf4500-b05d-11e8-8274-82b0855ab82f.png)

**Comment by curtiskphsc** [comment]
@C13L0  Updated link from 
https://student-life.phsc.edu/department-information/events/campus/porter-campus-tour

to
 
https://student-life.phsc.edu/department-information/events/campus-tour/porter-campus-tour

**Comment by C13L0** [comment]
Completed
