### ISSUE TITLE
Admin Photos

### ISSUE THREAD

**Issue by curtiskphsc** [phsc-edu/2018#438]
We have photos missing that have been populating to the Admin Directory for quite some time. All photos were added during the last iteration and now some that had been displaying fine for years have disappeared. I have updates to make soon with new employees coming on. I don't want to add any new photos until we know why these went away.

https://info.phsc.edu/course-schedule/bio/keith-braun
https://info.phsc.edu/course-schedule/bio/margie-burnham
https://info.phsc.edu/course-schedule/bio/ray-calvert (I think this one is a photo file naming issue. Should be "raymond-calvert" I am including it only because it went away with the rest of them)
https://info.phsc.edu/course-schedule/bio/john-collins
https://info.phsc.edu/course-schedule/bio/ed-goolsby (was populating fine before update)
https://info.phsc.edu/course-schedule/bio/david-mccain
https://info.phsc.edu/course-schedule/bio/darcy-mcdowell
https://info.phsc.edu/course-schedule/bio/wayne-miller
https://info.phsc.edu/course-schedule/bio/jonathan-myers
https://info.phsc.edu/course-schedule/bio/lisa-richardson (was populating fine before update)

New photos coming soon:
https://info.phsc.edu/course-schedule/bio/marcia-austin
https://info.phsc.edu/course-schedule/bio/michele-godwin
https://info.phsc.edu/course-schedule/bio/alysen-heil
https://info.phsc.edu/course-schedule/bio/gerene-thompson
https://info.phsc.edu/course-schedule/bio/melanie-waxler

**Comment by C13L0** [comment]
@curtiskphsc As stated in ticket https://github.com/phsc-edu/2018/issues/215#issuecomment-412901955 you will need to manually maintain admin images.

> However, you will still need to manually upload admin images.

**Comment by curtiskphsc** [comment]
@C13L0 What I am saying is, I **did** manually upload **all** of the images. They have since disappeared. What would be causing this? The images should be uploaded once. I should not have to continually re-upload the same images over and over.

**Comment by C13L0** [comment]
@curtiskphsc You will have to manually maintain the image directory.  The technical explanation is the same as always, when there is an issue with the file from MIS they will have to be uploaded again. CLOSING
