### ISSUE TITLE
#58 Writing Center - Cielo

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#442]
Hi, Cielo.

Should the attached have headings and clump information intended to be read together in one paragraph box to be accessible?

Thanks, Ann

Ann Bunting, Ph.D.

Professor, Language Arts

Pasco-Hernando State College

727 816-3331 (office)

727 514-2135 (cell)

**Comment by Computerrat** [comment]
Please review the following document for accessibility. I added alt text and tried to correct any tag errors I could see. Wasn't sure how to handle TOC
[APA_Handout.pdf](https://github.com/phsc-edu/2018/files/2358409/APA_Handout.pdf)

**Comment by C13L0** [comment]
Note -  url is not correct on document

**Comment by C13L0** [comment]
As per @Computerrat document was reworked...closing
