### ISSUE TITLE
Financial Aid Department staff change and web site update

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#443]
Hello Cielo;

Can you please make the following changes to this web page?  https://financial-aid.phsc.edu/department-information

Please delete the staff name of Gail Badger as she is no longer working for the college. Please add Isaac Hernandez and his email hernani@phsc.edu in Gail's spot on the web page. Isaac was hired to fill Gail's position so the phone extension and office locations are the same. 

Thanks for your help! 😊

Sincerely,

Kim Williams
Associate Director-Financial Aid
Pasco-Hernando State College 
10230 Ridge Road
New Port Richey, FL  34654
727.816.3195

**Comment by C13L0** [comment]
completed
