### ISSUE TITLE
Request to add a link under Library Resources

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#447]
Please add the following link under Library Resources at https://phsc.edu/student-life/libraries

The link should go between Electronic Library Resources and Course Reserves.  The title of the link should be Library hours and services.

Raymond Calvert
Director of Libraries
Pasco-Hernando State College
e-mail: calverr@phsc.edu
phone: 727-816-3418

![library resources](https://user-images.githubusercontent.com/3138019/45237989-36e79380-b2ae-11e8-80ec-b61e0e4e1ad9.png)

**Comment by curtiskphsc** [comment]
@C13L0 completed

**Comment by C13L0** [comment]
@curtiskphsc This needs to be linked to a clean url for accessibility purposes, not to the node id. phsc.edu/**node/1081**

**Comment by curtiskphsc** [comment]
@C13L0  completed

**Comment by C13L0** [comment]
Completed

**Comment by C13L0** [comment]
From: Raymond Calvert
Sent: Friday, September 14, 2018 03:05 PM
To: Webmaster
Subject: Re: Request to add a link under Library Resources | 447 | For review
 
This is the URL - http://libguides.phsc.edu/library-services

Thanks Cielo.  I am not sure what my e-mail is doing with the links.

Raymond Calvert
Director of Libraries
Pasco-Hernando State College
e-mail: calverr@phsc.edu
phone: 727-816-3418
From: Webmaster
Sent: Friday, September 14, 2018 2:33:08 PM
To: Raymond Calvert
Subject: Re: Request to add a link under Library Resources | 447 | For review
 
Hi Ray,


Which url would you like to use?



From: Raymond Calvert
Sent: Friday, September 14, 2018 2:26:03 PM
To: Webmaster
Subject: Re: Request to add a link under Library Resources | 447 | For review
 
Could we use this URL for Library Hours and Services?


Raymond Calvert
Director of Libraries
Pasco-Hernando State College
e-mail: calverr@phsc.edu
phone: 727-816-3418

**Comment by curtiskphsc** [comment]
As there was no link supplied with the original request, I linked to the "department" page for hours. I have changed the link as requested to http://libguides.phsc.edu/library-services

**Comment by C13L0** [comment]
Completed
