### ISSUE TITLE
Fw: PHSC Foundation: Needs review - Annual Catch & Release Fishing Tournament

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#449]
Hi Cielo,

Do you know why Shelley is receiving notification of adjustments to the webpage?

Thanks Jessica
 Hi Cielo,

I'm not sure whether I mentioned it when we spoke the other day, but I cannot add new sponsors to the sponsor page. I have several new ones to add for the upcoming golf event. I know I told you I needed more sponsorship listings too.Right now I have available: Ace, Co Presenting, Dinner, Gold Team, Goodie Bag, Individual, and Silver.

The sponsorship's i need are: 

Co Presenting, Team, Station, Scholarship, Gold, Silver, Team.

Thank you

Jessica Staller

**Comment by Computerrat** [comment]
FYI...all staff members of the Foundation are receiving the update. This has not occurred in the past.

**Comment by C13L0** [comment]
This has been completed

**Comment by C13L0** [comment]
Completed
