### ISSUE TITLE
Student Life Peace Week accessibility issues

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#455]
@curtiskphsc @boettcc 

Please correct the accessibility issues on https://student-life.phsc.edu/programs/peace-week

<img width="635" alt="student-life-peace-week" src="https://user-images.githubusercontent.com/3138019/45564440-6c483000-b81e-11e8-8ff0-7292dc613f51.png">

**Comment by curtiskphsc** [comment]
@C13L0 Actually miaDmin created this content. Whoever that is needs to correct the accessibility issues.
![miadmin-peace-week](https://user-images.githubusercontent.com/28155245/45569407-69087080-b82d-11e8-9eb5-6bd303029b8e.JPG)

**Comment by C13L0** [comment]
@curtiskphsc @boettcc 

As always, please work with department to correct the accessibility issues on this page

**Comment by C13L0** [comment]
@curtiskphsc This is a followup to find out where you are with this ticket

**Comment by curtiskphsc** [comment]
@C13L0 @boettcc As stated above, and as shown in the screen shot attached, the record shows that miAdmin created this content. We are under the impression that miAdmin is the Webmaster. I requested that the content creator of record make the necessary edits.

**Comment by curtiskphsc** [comment]
@C13L0 All caps removed 
![peace-week](https://user-images.githubusercontent.com/28155245/46154012-4705e980-c242-11e8-843b-4e0a64718e65.JPG)

**Comment by C13L0** [comment]
completed
