### ISSUE TITLE
Links on phsc.edu Testing Services page don't open charts

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#460]
When I go this this page: https://testing-services.phsc.edu/tests and click on PERT or TABE, the Student Testing and Placement Chart for PERT and the TABE Exit Requirements for Career and Technical Certificate Programs chart for TABE opens to a page cannot be found.

James Friend
Computer Network/Support Specialist
Office: 352-518-1253

**Comment by C13L0** [comment]
Assigning to @curtiskphsc to work with the department to correct the broken links.

**Comment by curtiskphsc** [comment]
completed

**Comment by C13L0** [comment]
Closing
