### ISSUE TITLE
PHSC Foundation: Needs review - 9th Annual Heart of Gold Donor Appreciation Luncheon

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#462]
9th Annual Heart of Gold Donor Appreciation Luncheon is ready for review
at https://foundation.phsc.edu/node/392

Submitted by: stallej on Tuesday - Sep 18, 2018 - 10:44 am

Revision Log Message: Can we get the name changed to 9th Annual Heart of Gold
Donor Appreciation Luncheon instead of 7th Annual?  Currently the 7th Annual
is showing for the Annual event with information about Leslie Barnwell, but
that information is dated. Thank you!

**Comment by C13L0** [comment]
This was completed during the moderation process
