### ISSUE TITLE
Intranet Announcement Homepage Request -- Funeral Service for Dr. Judson

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#465]
Hi Cielo,

Please post the following marketing approved announcement on the Intranet homepage:

Funeral Service Planned for Former PHSC President Robert W. Judson Jr., Ed.D.
 
A funeral service is planned for Robert W. Judson Jr., Ed.D., former president of Pasco-Hernando State College. The service will be held on Saturday, September 29, 2018 at 12:30 p.m. at Hopewell Baptist Church, in Pompano Beach, 890 NW 15th St.
 
PHSC is planning a memorial service to honor Dr. Judson for Tuesday, October 9, 2018 at 1 p.m. at the PHSC Performing Arts Center on West Campus in New Port Richey, 10230 Ridge Road. More information on this event will be announced soon.

Please post as soon as possible and leave up until 9/28.

Many thanks,

Courtney

Courtney Boettcher

Associate Director, Marketing and Communications

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

**Comment by Computerrat** [comment]
completed

**Comment by C13L0** [comment]
From: Courtney Boettcher
Sent: Friday, October 5, 2018 10:19 AM
To: Webmaster
Cc: Lucy Miller; Lisa Richardson
Subject: Add information to Judson Memorial Service Intranet Announcement
 
Good Morning Cielo,


Please add the following information to the existing intranet announcement: Robert W. Judson, Ph.D., Celebration of Life and Memorial Service posted on 10/4.


To honor Dr. Judson, you may consider a donation to the Robert & Ellen Judson Scholarship. Please make check payable to the PHSC Foundation and list scholarship fund #1659 in the memo section of the check.

This information can be added at the end of the original announcement.

Many thanks,

Courtney
