### ISSUE TITLE
Request to add additional content to our eFaculty site

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#467]
Hello,

Please see the approved changes list below. 

Please let me know if there is anything else you need.

Thank you,
Maya

From: Christine Smith
Sent: Wednesday, September 19, 2018 2:43 PM
To: Maya Pakhomova
Subject: Re: Request to add additional content to our eFaculty site
 
Yes, I approve, for now.  When we hire another ID we will update that site.  FYI - The linked page in your original email is out of sorts.  
From: Maya Pakhomova
Sent: Wednesday, September 19, 2018 2:38:38 PM
To: Christine Smith
Subject: Request to add additional content to our eFaculty site
 
Hello Christine,

Please approve the following changes to the eFaculty site.

https://efaculty.phsc.edu/eteaching/community-practice/faculty-mentor-program

I. Create three additional pages, titled after each of the new mentors: 
Eddie Williams IV
Karen Lotz 
Jennifer Wiatrowski

 
II. Update the left-hand side navigation menu to reflect the following:
-eTeaching
-Community of practive
-Faculty Mentoring Program
-Jorge Gavillan
-Karen Lotz
-Jennifer Wiatrowski
-Eddie Williams IV
-Maria Witherell
 
 

Please let me know if you have any questions.

Thank you,
Maya

  |

**Comment by C13L0** [comment]
@jeppy64 Can you please quote how much time to build out Faculty Mentor Program? 

Buildout will be similar to Academic Success Center https://academic-success.phsc.edu/services/person-tutoring

https://efaculty.phsc.edu/eteaching/community-practice/faculty-mentor-program
**Fields for list view**
Image
Name
Campus
Trimmed body (bio)

https://efaculty.phsc.edu/eteaching/community-practice/faculty-mentor-program/jorge-gavillan
**Fields for Faculty Mentor Node**
Image
Name
Title
Campus
Office
Phone
Email
Bio



Mentor: Jorge Gavillan
Title: Asst. Professor, Mathematics
Location: East Campus
Office: A-138
Phone: 352-518-1287
Email: gavillj@phsc.edu

I am a former secondary mathematics teacher and currently an Assistant Professor of Mathematics on the East Campus of Pasco-Hernando State College. I have an associate degree from Valencia College, a bachelor’s degree from the University of Central Florida, and a master’s degree from Nova Southeastern University. I have also completed graduate mathematics courses at the Florida Institute of Technology, where I am currently pursuing a graduate degree. I have taken many online courses as a student and have also taught online courses ranging from Liberal Arts Mathematics through Calculus. My favorite courses to teach are developmental mathematics and the introductory statistics course.

M.S. Operations Research, Florida Institute of Technology (in progress)
M.S. Mathematics Education, Nova Southeastern University
B.S. Liberal Studies, University of Central Florida
A.A. Valencia Community College (Valencia College)

**Comment by C13L0** [comment]
Default bio image

![default-portrait](https://user-images.githubusercontent.com/3138019/45822582-ca12c700-bcb9-11e8-8a8b-4a6513850cd6.png)

**Comment by jeppy64** [comment]
@C13L0 

Estimated time to complete: 3 hours

**Comment by jeppy64** [comment]
@C13L0 

Time to complete: 3 hours. Ready for review and ticket close

**Comment by C13L0** [comment]
Completed
