### ISSUE TITLE
Adjunct Application Update

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#470]
Hi Cielo,

I need to update the application listed for our adjunct instructor positions. I am unable to locate the correct file under my Dashboard. The attached PDF document has the new application.

Thanks!

Pat

https://www.phsc.edu/sites/default/files/documents/bpe-1.pdf
[BPE-1+FRS CERT.pdf](https://github.com/phsc-edu/2018/files/2402581/BPE-1%2BFRS.CERT.pdf)

**Comment by C13L0** [comment]
@jeppy64 We are looking to delete https://www.phsc.edu/sites/default/files/documents/bpe-1.pdf and update it with a new file. However, I can't find it in the admin document view. Could you look at the view and adjust so we can edit this document?

Thanks!
Cielo

**Comment by C13L0** [comment]
Worked with @jeppy64 to delete old file to replace with updated version
