### ISSUE TITLE
Pilot Photo Website change

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#471]
From: Melanie Waxler
Sent: Friday, September 21, 2018 08:24 AM
To: Webmaster; Kevin Curtis
Subject: Fw: Pilot Photo Website change
 
Mark Aragon is asking that we "freshen up" the aviation page. New photos, add some video links from the TV coverage, etc...  Let me know if I can assist with anything.

Thank you!

Mel

Melanie Waxler

Associate Dean,

Marketing, Communications & Media Relations

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

727-816-3259 (office)

813-712-9024 (cell)

 

From: Mark Aragon
Sent: Thursday, September 20, 2018 3:46 PM
To: Melanie Waxler
Subject: Pilot Photo Website change
 
Melanie,

When will we be able to update the website for aviation?

Thanks,

**Comment by C13L0** [comment]
@curtiskphsc Which page do you want the video? Please provide the url.

**Comment by curtiskphsc** [comment]
@C13L0 Ideally we would want that capability in the hero as Oregon State's Drupal 8 site does with 0 WAVE errors reported. https://oregonstate.edu/

**Comment by C13L0** [comment]
@curtiskphsc Please provide the url on phsc.edu where you would like the video

**Comment by curtiskphsc** [comment]
@C13L0 Heroes are content types not URLs. So, Marketing would want video capabilities included as an option in the hero content type as stated above.

**Comment by C13L0** [comment]
@curtiskphsc 

Hero's are specific to a content type. In order to know which content type it is, I need the url to the specific page where you would like the video. Please provide the url on phsc.edu where you want the video in the Hero.

**Comment by C13L0** [comment]
From: Webmaster
Sent: Friday, September 21, 2018 10:30 AM
To: Kevin Curtis; Melanie Waxler
Cc: Melissa Harts
Subject: Re: Pilot Photo Website change | 471 | Open
 
Kevin,


As requested in the ticket, please provide the url on phsc.edu where you would like the video. I cannot move forward with your request until you provide the information requested.

**Comment by curtiskphsc** [comment]
@C13L0 So you want the URL of every page we want this capability on? Or do you want to know which content types we want this capability associated with? One page URL is not going to represent all of the content types we would like hero video capabilities available on. Here is a _representative_ list.
Campus content type-https://phsc.edu/about-phsc/campuses/east-campus
Department content type-https://phsc.edu/home
Event content type-https://www.phsc.edu/about-phsc/events/deadline/summer-term-iiib-last-day-to-withdraw-or-change-to-audit-0
Marketing Campaign content type-https://www.phsc.edu/home
Pages content type-https://www.phsc.edu/about-phsc
Program content type-https://www.phsc.edu/academics/degrees-and-programs/engineering-and-manufacturing
Ultimately, it would be our wish to showcase video on the following content types as well, but these do not currently have hero capabilities.
Career Study Path content type-https://www.phsc.edu/academics/degrees-and-programs/health-sciences/registered-nurse-rn
News content type-https://www.phsc.edu/about-phsc/news/media/new-program-first-florida-to-offer-drone-flying-degree

**Comment by C13L0** [comment]
@curtiskphsc I've created ticket #472 Add video to Hero and requested an estimate from Jay. 

In the meantime, you have several other options to highlight the video.

1. Create Hero and add a link to a video (see screenshot for example)
2. Add a video to the Program page
3. Add video link(s) to the body

<img width="863" alt="link-to-video-in-hero" src="https://user-images.githubusercontent.com/3138019/45901287-69b28100-bdb0-11e8-8ce7-6e8f8621051f.png">

**Comment by curtiskphsc** [comment]
@C13L0 The photo was changed the day the ticket came (it was the instrument panel of an airliner prior) and the unmanned ABC News video was added to the Aviation grouping page. As you are aware, we can't add videos to the individual program pages just yet.

**Comment by C13L0** [comment]
@curtiskphsc The feature request to add video to individual program pages is in ticket #472 . You can close out this ticket if the rest of the work was completed

**Comment by C13L0** [comment]
Closing. No need to have duplicated ticket for the same thing
