### ISSUE TITLE
remove page

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#480]
Please remove this page

https://phsc.edu/about-phsc/events/campus/collegewide-phi-beta-lambda-induction-ceremony

Collegewide Phi Beta Lambda Induction Ceremony | Pasco ...
phsc.edu
Phi Beta Lambda (PBL) is a national, state and local business organization for students interested in business. Members learn the value of competition at the district, state and national levels.

**Comment by C13L0** [comment]
completed
