### ISSUE TITLE
(No subject)

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#481]
I would like to have a sign up set up for the student life webpage for Intramural Basketball 3-on-3 League. I'd like the sign up to close on October 22. 

Intramural Basketball 3-on-3 League

East Campus

Wednesday afternoons from October 24 to November 14
 

Ahmy S. Arca
Coordinator of Student Life & Leadership

Pasco-Hernando State College, East Campus

352-518-1224

arcaa@phsc.edu

**Comment by C13L0** [comment]
From: Webmaster
Sent: Wednesday, October 3, 2018 04:06 PM
To: Ahmy Arca
Subject: Re: |481 | Open
 
Hi Ahmy,


Please provide the following information so I can build the sign-up form.


Fields (name, email, phone, etc...)
Which fields are required?
Email address the form should be submitted to

Thanks!

Cielo

**Comment by C13L0** [comment]
From: Ahmy Arca
Sent: Wednesday, October 3, 2018 04:37 PM
To: Webmaster
Subject: Re: |481 | Open
 
Name


Student Number


Email 


Home Campus


My email to submit.


Ahmy S. Arca
Coordinator of Student Life & Leadership

Pasco-Hernando State College, East Campus

352-518-1224

arcaa@phsc.edu

**Comment by C13L0** [comment]
This webform already exists as "Event_Signup". closing
