### ISSUE TITLE
Updated Web Pages

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#489]
Hi Cielo,

Good Afternoon! At Kevin's suggestion, I just wanted to email you so you are aware that I am no longer receiving an email when I submit a edit on the website for review.  Last time I submitted a change, I received an email.  

Thanks,
 
Tanya Weakland
Manager, Student Financial Services
_____________________________
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, Fl. 34654-5199
Phone: (727) 816-3481
Fax: (727) 816-3726

**Comment by C13L0** [comment]
completed
