### ISSUE TITLE
update PHCC link

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#492]
@curtiskphsc 

Please update phcc in link to phsc
https://phsc.edu/academics/continuing-education

> http://www.ed2go.com/phcc/ redirected to https://www.ed2go.com/phsc/
> This is a permanent redirect. The link should be updated.

<img width="1362" alt="phcc-in-link" src="https://user-images.githubusercontent.com/3138019/46496795-eac53b80-c7e6-11e8-95ce-9b7d3928c93e.png">

**Comment by curtiskphsc** [comment]
@C13L0 completed

**Comment by C13L0** [comment]
Completed
