### ISSUE TITLE
Bad quick link to testing services

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#493]
Please correct bad quick link
https://phsc.edu/student-life/academic-advising

<img width="1382" alt="bad-quick-link" src="https://user-images.githubusercontent.com/3138019/46497810-95d6f480-c7e9-11e8-8b3f-6bcfb2cbaa6d.png">

**Comment by curtiskphsc** [comment]
@C13L0 completed

**Comment by C13L0** [comment]
completed
