### ISSUE TITLE
Update Link within the Subdomain Leaderboard Menu

### ISSUE THREAD

**Issue by 10yson** [phsc-edu/2018#496]
Please update the Academic Calendar link within the sub-domain leaderboard menu to point to current term.  Link on main site looks good to me.  I think this only impacts the sub-domain sites.

**Comment by C13L0** [comment]
- [ ]  Academic Success Center 
- [ ]  Accessibility Services
- [ ]  Admissions 
- [ ]  Advising 
- [ ]  Athletics
- [ ]  Career Services
- [ ]  Educator Preparation Institute
- [ ]  eFaculty Support
- [ ]  Equity Services
- [ ]  eStudent Support
- [ ]  Financial Aid
- [ ]  Financial Services
- [ ]  Foundation
- [ ]  Legal Department
- [ ]  Safety and Security
- [ ]  Student Life
- [ ]  Testing Services
- [ ]  Writing Center

**Comment by C13L0** [comment]
@10yson Thank you for taking the time to notify me. This has been completed
