### ISSUE TITLE
password

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#497]
Hello, I need to submit a ticket only for access to add content to the PHSC website. I am the director of human services and my password that will allow me to add updates for the human services program is not working. I am also locked out. 

Eddie Williams, Ed.D, LMHC, NCC, MCAP, HS-BCP 

Program Director/Assistant Professor, Human Services

North Campus

11415 Ponce de Leon Blvd. Brooksville, FL 34601

Spring Hill Campus
450 Beverly Ct. Spring Hill, FL 34606

(352) 340-4865 Office
(352) 340-4968 Fax

**Comment by C13L0** [comment]
Completed
