### ISSUE TITLE
PHSC Alert image

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#499]
@curtiskphsc Please work with Jan and David on the following request

--------

From: Ingrid Purrenhage
Sent: Monday, October 8, 2018 09:12 AM
To: Webmaster; Karen Price
Subject: Re: PHSC Alert image
 
It is on the home page in WISE after you log in.  There is a page on the PHSC website which instructs folks to sign up (https://safety.phsc.edu/procedures) and has a button for "register now".

However, that button does not register anyone nor even take you to the page to regitster! It just gives more instructions:

https://safety.phsc.edu/procedures/phsc-alert

It tells people to click on the "PHSC Alert Image" in WISE... however it does not show you what this image looks like and the image in WISE is not labeled and is near other text so it is completely unclear what it does.

---------

From: Webmaster
Sent: Monday, October 8, 2018 9:01:18 AM
To: Karen Price
Cc: Ingrid Purrenhage
Subject: Re: PHSC Alert image
 
Good morning,
I will be happy to look into this for you. Can you please provide the website url where the alert image is?

--------

From: Karen Price
Sent: Monday, October 8, 2018 08:56 AM
To: Webmaster
Cc: Ingrid Purrenhage
Subject: PHSC Alert image
 

In preparing for the upcoming storm and so that we can help our students to be signed up for PHSCAlerts we discovered that the PHSCAlerts symbol in Wise is unlabeled in both chrome and IE.  Additionally the symbol is actually sitting next to a financial disclosure button, which is completely unrelated.  This is leading to some confusion by students.

**Comment by curtiskphsc** [comment]
@C13L0 "There is a page on the PHSC website which instructs folks to sign up (https://safety.phsc.edu/procedures) and has a button for "register now". **Language changed to "Learn how to register" to avoid confusion**
However, that button does not register anyone nor even take you to the page to regitster! It just gives more instructions: 
https://safety.phsc.edu/procedures/phsc-alertI
It tells people to click on the "PHSC Alert Image" in WISE... however it does not show you what this image looks like and the image in WISE is not labeled and is near other text so it is completely unclear what it does. **With Corey Long's permission, I have updated the WISE and MyBenefits PHSC Alert icon graphic to include the text "PHSC Alert" and Jan stated she would update them both as soon as possible.**

**Comment by C13L0** [comment]
From: Janice L Scott
Sent: Monday, October 8, 2018 07:40 PM
To: Ingrid Purrenhage; Karen Price; Webmaster
Cc: PHSC Marketing and Communications Office
Subject: Re: PHSC Alert image | 499 | Open
 
Hi Ingrid and Karen,   MIS takes care of WISE.  I am working with Marketing on a new ICON for the PHSC Alert.  I will have it updated tomorrow.

**Comment by C13L0** [comment]
@curtiskphsc The call to action on the front page also says "Register Now"

**Comment by C13L0** [comment]
From: Ingrid Purrenhage
Sent: Tuesday, October 9, 2018 12:24 PM
To: Janice L Scott; Karen Price; Webmaster
Cc: PHSC Marketing and Communications Office
Subject: Re: PHSC Alert image | 499 | Open
 
Hi Jan,


Thank so much. I meant to copy you on the last email I sent, but obviously didn't -- sorry. I appreciate the addition of the label in WISE. I had also wanted to alert our webmaster, as the instructions are also on the website and mention clicking on some icon, but do not show an image of it (also making it harder to know where one should click).


I saw the new icon with text -- I think that will be much easier for folks to find where they should be registering.


Thanks again -- you are awesome.


Ingrid

Ingrid Purrenhage

Associate Director PHSC Porter Campus Library

2727 Mansfield Boulevard

Wesley Chapel, FL 33543

813-527-6690

**Comment by C13L0** [comment]
Alert Image in WISE was updated. Directions were updated on the website. Images can be added to the hero. Marketing would have to provide an updated layout/design to add images to static pages. This can be requested as a Phase II feature request by Marketing.
