### ISSUE TITLE
Create Web Page 

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#502]
Ticket from dynamics365:

PHSC and USF World's Study Abroad program have signed a memorandum of understanding that will allow PHSC students to travel on USF Study Abroad trips and earn credit that will be transferred back to PHSC. We need an ad on the website and a landing page so students can get information. That page should be in the admissions subdomain. Content will be provided.

PHSC Help Desk Support

727-816-3311

helpdesk@phsc.edu

**Comment by C13L0** [comment]
Not enough information or contact info. Spoke to Harold ...whoever submitted the ticket should create a marketing request.
