### ISSUE TITLE
PHSC Foundation: Needs review - 2018 Employee Giving Campaign Flier

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#504]
Hello,

Could you assist us in getting links put on the Employee Giving page of the Foundation's subdomain? The location is under the ways to give tab. There are two documents which Jessica has just uploaded, but it appears on our end that we do not have access to edit that particular page.

Can you help? 

Thanks,
Claire.

**Comment by C13L0** [comment]
From: Webmaster
Sent: Wednesday, October 10, 2018 08:36 AM
To: Claire Cohn
Cc: Courtney Boettcher
Subject: Re: PHSC Foundation: Needs review - 2018 Employee Giving Campaign Flier
 
Good morning Claire,


I've verified that all Foundation department editors have permission to edit that page. Navigate to the page and choose "edit". Once the changes have been made, input a revision message and "Save for review". Once Marketing reviews it, they will publish the changes.


Thanks,

Cielo
