### ISSUE TITLE
Intranet message post request - HR Open Enrollment

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#505]
From: Bonnie Mason
Sent: Tuesday, October 9, 2018 04:32 PM
To: Webmaster
Subject: Intranet message post request - HR Open Enrollment
 
Please post the following message to the intranet with the pdf attachments.

2019 Annual Open Enrollment: October 15th through October 26th

Visit the Human Resources 2019 Open Enrollment web site, and read this important Benefits Memo to help familiarize yourself with your 2019 benefit choices.

Total plan changes: Learn more about the HRA - PPO 03359 health plan cancelation and two new HSA plans being offered. 

Open Enrollment benefit meetings: Monday, October 15th - see the attachment "It is Almost Time" for locations, times and Wise registration information.

The HR open enrollment web url is https://access.phsc.edu/departments/hr/2019OpenEnrollment2019.htm

Thank you.

Bonnie Mason

Marketing and Communications Coordinator

Pasco-Hernando State College

masonb@phsc.edu

727.816.3105

**Comment by Computerrat** [comment]
completed
