### ISSUE TITLE
Correction on Intranet please

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#506]
From: Bonnie Mason
Sent: Wednesday, October 10, 2018 08:30 AM
To: Webmaster
Subject: Correction on Intranet please
 
Can you please change 'Wed.' to 'Thurs.' before Oct. 25 in the Lunch and Learn posting?

Thank you!

Bonnie

Bonnie Mason

Marketing and Communications Coordinator

Pasco-Hernando State College

masonb@phsc.edu

727.816.3105

**Comment by Computerrat** [comment]
completed
