### ISSUE TITLE
Draggable views core 8.6 regression

### ISSUE THREAD

**Issue by jeppy64** [phsc-edu/2018#507]
@C13L0
 
Apparently the core 8.6 update is throwing a nasty error when trying to set up draggable views and its conflict with views ajax.

The patch rolled for this can be found here in this issue on D.O.

https://www.drupal.org/project/draggableviews/issues/2992430

Ticket reference #320

**Comment by C13L0** [comment]
@jeppy64 Please RTBC in the issue queue once tested. 
Applied patch and committed
