### ISSUE TITLE
repost flu information - intranet request

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#508]
From: Bonnie Mason
Sent: Wednesday, October 10, 2018 10:48 AM
To: Webmaster
Cc: David Velazquez
Subject: repost flu information - intranet request
 
Hello.  Please repost the flu message on the intranet to run through 10/25.  

Be a flu fighter! Get your Flu Shot on Campus!

Arm yourself with a flu shot. Caused by the influenza virus, the flu can cause mild to severe illnesses and can be deadly. Visit FluFreeFlorida for information on influenza and tips on how to prevent the spread of this contagious respiratory disease with other resources.

 

Porter Campus—Wednesday, October 10; 1-2 p.m. in building A, 3rd floor lobby

East Campus—Thursday, October 11; 2-3 p.m. in A240

Spring Hill—Wednesday, October 17; 2-3 p.m. in B105

North Campus—Friday, October 19; 2-3 p.m. in B104

West Campus—Thursday, October 25; 1-3 p.m. in B109

Bonnie Mason

Marketing and Communications Coordinator

Pasco-Hernando State College

masonb@phsc.edu

727.816.3105

**Comment by Computerrat** [comment]
completed
