### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#514]
@Computerrat Please comment out the links to the style guide as there is currently not a style guide available.

http://internal.phsc.edu/sitemap.php
http://internal.phsc.edu/resources/

------

From: Ann Bunting
Sent: Thursday, October 11, 2018 06:58 PM
To: Webmaster
Subject: Broken Link
 
The link to the PHSC Style Guide on the following page is broken. 

https://access.phsc.edu/sitemap.php

There is another link the the PHSC Style Guide on https://access.phsc.edu/resources/ in the left-hand column.  This is also broken.

Ann

Ann Bunting, Ph.D.

Professor, Language Arts

Pasco-Hernando State College

727 816-3331 (office)

727 514-2135 (cell)

**Comment by Computerrat** [comment]
completed
