### ISSUE TITLE
IMMS to Post

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#517]
@Computerrat files are in webmaster email =)

------

From: Pamela Nadolski
Sent: Thursday, October 11, 2018 04:31 PM
To: Webmaster
Subject: IMMS to Post
 
Cielo,

Please post the attached IMMs 2-32, 2-3, and 2-7.

Each of them are effective 10/8/2018. 

Thank you,

Pam 

Pamela A. Nadolski, FRP ACP
Advanced Certified Paralegal
Pasco-Hernando State College
10230 Ridge Road
New Port Richey, FL 34654
Phone: 727-816-3746
Fax: 727-816-3450
Email: nadolsp@phsc.edu

**Comment by Computerrat** [comment]
completed
