### ISSUE TITLE
Update Evening Administrator - October

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#519]
@Computerrat File is in webmaster email

--------

From: Laura Santomenno
Sent: Friday, October 12, 2018 08:25 AM
To: Webmaster
Subject: Update Evening Administrator - October
 
Please post this updated version to the webpage. Thank you.

Laura Santomenno

Administrative Assistant I, Dean of Academic Affairs and Institutional Accreditation

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

Phone: 727 816-3214

Fax: 727 816-3300

santoml@phsc.edu

**Comment by Computerrat** [comment]
completed
