### ISSUE TITLE
Intranet Update

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#520]
@Computerrat Document is in webmaster email.

---------

From: Marissa Binder
Sent: Friday, October 12, 2018 10:27 AM
To: Webmaster
Cc: Cara Curtis; Gerene Thompson
Subject: Intranet Update
 
Good morning,

Please see the attached document to be updated on the Intranet. The link is under "quick links" titled "Faculty qualification manual".

Thank you,
Marissa Binder
Executive Administrative Assistant,
Vice President of Academic Affairs and Faculty Development/College Provost
PHSC West Campus, Room A-121
10230 Ridge Road
New Port Richey, Fl 34654
(727) 816-3491

**Comment by Computerrat** [comment]
completed
