### ISSUE TITLE
Financial Services: Needs review - Delinquent Accounts & Collections

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#523]
Delinquent Accounts & Collections is ready for review
at https://financial-services.phsc.edu/node/48

Submitted by: weaklat on Friday - Oct 19, 2018 - 4:06 pm

Revision Log Message: the hyperlink for payconserve.com is
www.payconserve.com.  The link address is correct but when I click on it, it
doesn't work.

**Comment by C13L0** [comment]
I'm not able to replicate this issue using Chrome browser. The link is working correctly for me. I will need additional information, such as the browser and version that is being used. A screenshot would be helpful.

<img width="671" alt="payconserve" src="https://user-images.githubusercontent.com/3138019/47720572-8d28e100-dc24-11e8-8344-efb1fd8ba8d4.png">

**Comment by C13L0** [comment]
Closing this ticket...That was actually just a moderation revision comment of what was updated. =)
