### ISSUE TITLE
Intranet Page

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#524]
Hello Cielo,

Attached is a page I saw on the "Intranet" that needs to be updated. My boss, Brian Horn, attempted to update this page; however, he did not have complete access for the information to be updated. Please advise who I need to give this to so the information can be updated. (I left a message on your phone, and this was the purpose of my call to you today.)

   Thank you,

   Joyce

   Joyce A. Myers, MRA

Executive Administrative Assistant, Administration and Finance

Providing administrative support to

Brian Horn, VP, Finance and Auxiliary Services

Tony Rivas, AVP Facilities Mgmt and Administration

**Comment by Computerrat** [comment]
I was able to find the information from Remote Server, but am unsure how to update the personnel changes that are requested. Thanks

**Comment by C13L0** [comment]
From: Webmaster
Sent: Monday, October 29, 2018 12:38 PM
To: Brian Horn; PHSC Help Desk Faculty and Staff
Cc: Joyce Myers; Melissa Harts; Rick Sanders
Subject: Re: Intranet Page|524 |Open
 
Hi Brian,


Adding someone new to contribute would go through the help desk. I believe that Rick can assist in this process.


Thanks,

Cielo



From: Brian Horn
Sent: Monday, October 29, 2018 09:48 AM
To: Webmaster
Cc: Joyce Myers; Melissa Harts
Subject: Re: Intranet Page|524 |Open
 
Cielo,



Who has the capability to add access to contribute pages?




Brian S. Horn

Vice President of Finance and Auxiliary Services

Pasco-Hernando State College

10230 West Ridge Road

New Port Richey, FL 34654

(727) 816-3458
