### ISSUE TITLE
Adding Nursing to the Tutoring Subject Field for the Academic Success Center web page

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#528]
Since I've been getting more tutors from the nursing department, I would like to add Nursing to the tutoring subject field. Please let me know if this is possible. Thank you.

Benjamin Schultze

Academic Success Center Coordinator

Pasco Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

(727) 816-3237

**Comment by C13L0** [comment]
Nursing has been added to the following:
