### ISSUE TITLE
PHSC News Announcement FA landing page issue

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#541]
Hi Cielo and Kevin;

I am reviewing the updated posting and revisions to our web pages and noticed that the news-announcement on our landing page has been added twice? Now I am in a panic since you said we could not remove an announcement? I want the updated new items to read the FAQ announcement and the Mobile App update. 😐

I am not certain how the announcement was duplicated, but I do know that sometimes it takes a while for my submission for review to process and show it has been submitted to Marketing? 

Please help! 

Sincerely,

Kim Williams
Associate Director-Financial Aid
Pasco-Hernando State College 
10230 Ridge Road
New Port Richey, FL  34654
727.816.3195

**Comment by curtiskphsc** [comment]
@Computerrat Kim created two of the same pieces of content. node 171 and node 172 were exactly the same content. I deleted node 172.

**Comment by C13L0** [comment]
Completed
