### ISSUE TITLE
Reminder: Make your EADA Report available by October 15 - IMPORTANT

### ISSUE THREAD

**Issue by Computerrat** [phsc-edu/2018#547]
om: Steve Winterling
Sent: Tuesday, October 30, 2018 1:01:47 PM
To: Cielo Johnson; Webmaster
Cc: Dominique Phillips-Alvarez
Subject: Fw: EADA Report - PDF
 
Cielo,

This was sent to you on October 16th in PDF format by Dominique and I was copied on it.

Steve Winterling

Athletic Director

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

727-816-3362 (office)

727-816-3354 (fax)

From: Dominique Phillips-Alvarez
Sent: Tuesday, October 16, 2018 9:17 AM
To: Cielo Johnson
Cc: Steve Winterling
Subject: EADA Report - PDF
 
Cielo

Please see the attached report in a PDF format.

Have A Great Day!

Dominique Phillips-Alvarez, CCP

Senior Office Assistant Athletics

10230 Ridge Road, K123

New Port Richey, Florida 34654

(727) 816-3342 PH

(727) 816-3354 FX

1516113168094_PHSC_One-Line_2_Color.jpg

rom: Webmaster
Sent: Tuesday, October 30, 2018 12:22 PM
To: Steve Winterling
Subject: Re: Reminder: Make your EADA Report available by October 15 - IMPORTANT
 
Hi Steve,

This is a follow-up to the previous request.

From: Webmaster
Sent: Tuesday, October 16, 2018 08:24 AM
To: Steve Winterling
Subject: Re: Reminder: Make your EADA Report available by October 15 - IMPORTANT

Hi Steve,

Can you please provide the report in .pdf format?

Thanks,
Cielo

From: Webmaster
Sent: Tuesday, October 16, 2018 08:24 AM
To: Steve Winterling
Subject: Re: Reminder: Make your EADA Report available by October 15 - IMPORTANT
 
Hi Steve,

Can you please provide the report in .pdf format? 

Thanks!

Cielo

From: Steve Winterling
Sent: Tuesday, October 16, 2018 7:34:24 AM
To: Webmaster
Cc: Cielo Johnson
Subject: Fw: Reminder: Make your EADA Report available by October 15 - IMPORTANT
 
Cielo,

Attached you will find our Equity in Athletics Disclosure Act (EADA).  This report should have been posted on our college web page yesterday, but my email from two weeks ago must have stayed in the draft box.  Can you please put this up on the web page today?  This is a Federal Government requirement.  Just let me know where I can find it. 

Thanks for your help.

Steve Winterling

Athletic Director

Pasco-Hernando State College

10230 Ridge Road

New Port Richey, FL 34654

727-816-3362 (office)

727-816-3354 (fax)

From: eadahelp@westat.com <eadahelp@westat.com>
Sent: Monday, October 8, 2018 10:11 AM
To: Steve Winterling
Subject: Reminder: Make your EADA Report available by October 15
 
Institution Name: Pasco-Hernando State College (136400)
User ID: E1364001

To EADA Survey Administrator - 

This is a reminder that you are required to make your EADA Report available to your campus community by Monday, October 15, 2018. As stated in your registration packet, preparing your institution’s EADA Report and submitting the online EADA Survey are both required as conditions of your institution’s continued participation in the Federal student financial assistance programs.  

The EADA Report should be made available to students, prospective students and the public by October 15, 2018.  More information regarding the EADA Report can be found on page 2 of the EADA User’s Guide, and in Volume 2, Chapter 6 of the Federal Student Financial Aid Handbook beginning on page 2-127:  https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fifap.ed.gov%2Ffsahandbook%2Fattachments%2F1617FSAHbkVol2Ch6.pdf&amp;data=02%7C01%7Cwinters%40phsc.edu%7Ce6c1ba0346524e2289a008d62d27fa28%7C7dd6a106eb4c403cb72a817e4ca6a1b5%7C0%7C0%7C636746047073811069&amp;sdata=XH%2BUFdu%2BVKl4tmXw50E3K%2BSPKMUfqN1FyzZ2NJh1nlI%3D&amp;reserved=0

The EADA Report is separate from your EADA Survey.  You are required to enter your EADA data into the online EADA Survey by October 30, 2018.

Thank you,
EADA Help Desk
[Copy of EADA PHSC FY2017-18 Intercollegiate Athletics Report detail-to Steve for review (1).pdf](https://github.com/phsc-edu/2018/files/2530807/Copy.of.EADA.PHSC.FY2017-18.Intercollegiate.Athletics.Report.detail-to.Steve.for.review.1.pdf)

@curtiskphsc

**Comment by curtiskphsc** [comment]
@Computerrat completed

**Comment by Computerrat** [comment]
Completed
