### ISSUE TITLE
Accessibility issue - RN Job

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#548]
@curtiskphsc Please correct/work with the appropriate department to correct the accessibility issue on https://phsc.edu/jobs/regular-positions-open-until-filled/instructor-nursing-rn

<img width="684" alt="rn-position" src="https://user-images.githubusercontent.com/3138019/47740706-d68e2600-dc4e-11e8-88b8-a46941fc1fe7.png">

**Comment by curtiskphsc** [comment]
@C13L0 removed all caps, added click to call to telephone numbers in body copy.

**Comment by C13L0** [comment]
Completed
