### ISSUE TITLE
University Partners teaser/copy

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#90]
@curtiskphsc 

University Partners has now been themed. There is a new field called "Teaser" which only shows on the main list page. Please review the teaser copy and also interior copy. I'm also sending an email to Sonia Thorn to review and I will cc you on it.

https://advising.phsc.edu/transfer-programs/university-partners

**Comment by C13L0** [comment]
@curtiskphsc This is a follow to find out where you are with this ticket

> @curtiskphsc @boettcc Request was not completed
> 
> University Partners has now been themed. There is a new field called "Teaser" which only shows on the main list page. Please review the teaser copy and also interior copy. I'm also sending an email to Sonia Thorn to review and I will cc you on it.
> 
> https://advising.phsc.edu/transfer-programs/university-partners

**Comment by curtiskphsc** [comment]
@C13L0 All University Partners listed have teaser copy. As this verbiage is exactly what was on the old page, I have no edits. I will leave that up to Dean Thorn.

**Comment by curtiskphsc** [comment]
@C13L0 @boettcc To state this request was not completed is a total falsehood. I reviewed it and provided comment on March 22, 2018. This content needs to be written by the University Partners themselves and as Dean Thorn's office is the point of contact, they should be reaching out to them not us. Also, as they have been prompted several times to make edits, and they have not, I would assume they are okay with the content as is.

**Comment by curtiskphsc** [comment]
@C13L0 There is no update to provide at this time. I will provide further comment when this has been addressed.

**Comment by C13L0** [comment]
@curtiskphsc This is a follow-up to find out where you are with this ticket
